### ISSUE TITLE
The case-when-then construct does not quote enum values

### ISSUE THREAD

**Issue by stephaneeybert** [querydsl/querydsl#1021]
The PLANNED value should be quoted when used in:
NumberExpression<Integer> statusPlanned = qBTS.status.when(com.nsn.nitro.project.data.utils.BTSStatus.PLANNED).then(new Integer(1)).otherwise(new Integer(0));

Same in:
NumberExpression<Integer> statusPlanned = new CaseBuilder().when(qBTS.status.eq(com.nsn.nitro.project.data.utils.BTSStatus.PLANNED)).then(new Integer(1)).otherwise(new Integer(0));

The produced sql:
select distinct rollout0_.id as col_0_0_, count(bts3_.id) as col_1_0_, sum(case when bts3_.status=PLANNED then 1 else 0 end) as col_2_0_, sum(case when bts3_.status=COMPLETED then 1 else 0 end) as col_3_0_, sum(case when bts3_.status=COMPLETED then 1 else 0 end)/100*count(bts3_.id) as col_4_0_, rollout0_.id as id1_8_, rollout0_.version as version2_8_, rollout0_.country_id as country_8_8_, rollout0_.creation_datetime as creation3_8_, rollout0_.description as descript4_8_, rollout0_.end_datetime as end_date5_8_, rollout0_.name as name6_8_, rollout0_.operator_id as operator9_8_, rollout0_.start_datetime as start_da7_8_ from rollout rollout0_ cross join rollout_admin rolloutadm1_ cross join admin admin2_ cross join bts bts3_ where rolloutadm1_.rollout_id=rollout0_.id and rolloutadm1_.admin_id=admin2_.id and bts3_.rollout_id=rollout0_.id and admin2_.id=1 group by rollout0_.id

The actual value:
public enum BTSStatus {
    PLANNED("PLANNED"),

It is thus interpreted as an unknown column:
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'PLANNED' in 'field list'

**Comment by tanvirgh** [comment]
@timowest please have a look over this....QUery DSL is creating problem with case and enum values.

    After running the following query method....   
  

    @Query(value = "select s.owner, " +
                "count(case when s.status = 3 then 1 else null end) as agreed," +
                "count(case when s.status = 2 then 1 else null end) as rejected," +
                "count(case when s.status = 1 then 1 else null end) as pending " +
                "from Schedule s where (s.owner = ?1) " +
                "group by s.owner")

here status is fetched from a enum and i have a converter class for that.But during runtime it gives the below exception that while calling convertToDatabaseColumn on converter class com.orsbv.hcs.model.schedule.ScheduleStatus$TypeConverter with value 1.e

Any help regarding the issue will be very helpful.Seek experts attention.
    
This is the error log : 
    

    ReportQuery(referenceClass=Schedule jpql="select s.owner, count(case when s.status = 1 then 1 else null end) as agreed,count(case when s.status = 2 then 1 else null end) as rejected,count(case when s.status = 3 then 1 else null end) as pending from Schedule s where (s.owner = ?1) group by s.owner")
            at org.eclipse.persistence.exceptions.QueryException.prepareFailed(QueryException.java:1596)
            at org.eclipse.persistence.queries.DatabaseQuery.checkPrepare(DatabaseQuery.java:685)
            at org.eclipse.persistence.queries.ObjectLevelReadQuery.checkPrepare(ObjectLevelReadQuery.java:911)
            at org.eclipse.persistence.queries.DatabaseQuery.checkPrepare(DatabaseQuery.java:615)
            at org.eclipse.persistence.internal.jpa.EJBQueryImpl.buildEJBQLDatabaseQuery(EJBQueryImpl.java:194)
            at org.eclipse.persistence.internal.jpa.EJBQueryImpl.buildEJBQLDatabaseQuery(EJBQueryImpl.java:116)
            at org.eclipse.persistence.internal.jpa.EJBQueryImpl.<init>(EJBQueryImpl.java:102)
            at org.eclipse.persistence.internal.jpa.EJBQueryImpl.<init>(EJBQueryImpl.java:86)
            at org.eclipse.persistence.internal.jpa.EntityManagerImpl.createQuery(EntityManagerImpl.java:1614)
            at sun.reflect.GeneratedMethodAccessor86.invoke(Unknown Source)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:498)
            at org.springframework.orm.jpa.ExtendedEntityManagerCreator$ExtendedEntityManagerInvocationHandler.invoke(ExtendedEntityManagerCreator.java:344)
            at com.sun.proxy.$Proxy75.createQuery(Unknown Source)
            at org.springframework.data.jpa.repository.query.SimpleJpaQuery.validateQuery(SimpleJpaQuery.java:86)
            ... 48 more
    Caused by: javax.persistence.PersistenceException: An exception occurred while calling convertToDatabaseColumn on converter class com.orsbv.hcs.model.schedule.ScheduleStatus$TypeConverter with value 1

**Comment by thackel** [comment]
Thats not a QueryDSL problem.
You are using a "plain" JPA Query in a Spring Data JPA Repository.
