### ISSUE TITLE
clone does not work properly for unions for sql

### ISSUE THREAD

**Issue by dodgex** [querydsl/querydsl#1096]
i have something like this:

``` java
SQLSubQuery sub1 = new SQLSubQuery();
ListSubQuery<Tuple> list1=sub1.list(...);

SQLSubQuery sub2 = new SQLSubQuery();
ListSubQuery<Tuple> list2=sub2.list(...);

SQLQuery query = ... ;

query.union(list1, list2);
```

the execution of this query works but when i do

``` java
SQLQuery query2 = query.clone() ;
```

i get when trying to execute the new query (`firstUnionSubQuery == null`)

```
java.lang.NullPointerException: null
    at com.mysema.query.sql.ProjectableSQLQuery.serialize(ProjectableSQLQuery.java:514) ~[querydsl-sql-3.5.0.jar:na]
    at com.mysema.query.sql.AbstractSQLQuery.list(AbstractSQLQuery.java:289) ~[querydsl-sql-3.5.0.jar:na]
    at com.mysema.query.sql.ProjectableSQLQuery.list(ProjectableSQLQuery.java:313) ~[querydsl-sql-3.5.0.jar:na]
```

my code related to the cloned query works fine for querys that do not use union.

**Comment by timowest** [comment]
Released in 3.6.1
