### ISSUE TITLE
Unsupported constant error in case Expression with in Operator

### ISSUE THREAD

**Issue by wrungel** [querydsl/querydsl#1110]
Given the following JPA entity Foo:
```java
@Entity
public class Foo {
    @Id
    private Long id;

    @Enumerated
    private EnumType enumType;
}
```
and the following enum class:
```java
public enum EnumType {
    A, B, C
}
```
The following query:
```java
JPAQuery jpaQuery = new JPAQuery(em);
QFoo qFoo = QFoo.foo;
HashSet<EnumType> enumTypes = new HashSet<EnumType>();
enumTypes.add(EnumType.B);
enumTypes.add(EnumType.A);

SimpleExpression<String> caseExpression = new CaseBuilder().
    when(qFoo.enumType.in(enumTypes)).
    then(Expressions.constant("x")).
    otherwise(Expressions.constant("y"));

jpaQuery.from(qFoo).list(caseExpression);
```
 fails with:
<pre><code>
java.lang.IllegalArgumentException: Unsupported constant [A, B]
	at com.mysema.query.jpa.JPQLSerializer.visitLiteral(JPQLSerializer.java:320)
	at com.mysema.query.jpa.JPQLSerializer.visitConstant(JPQLSerializer.java:285)
	at com.mysema.query.support.SerializerBase.visit(SerializerBase.java:208)
	at com.mysema.query.support.SerializerBase.visit(SerializerBase.java:42)
	at com.mysema.query.types.ConstantImpl.accept(ConstantImpl.java:127)
	at com.mysema.query.support.SerializerBase.handle(SerializerBase.java:105)
	at com.mysema.query.support.SerializerBase.visitOperation(SerializerBase.java:283)
	at com.mysema.query.jpa.JPQLSerializer.visitPathInCollection(JPQLSerializer.java:488)
	at com.mysema.query.jpa.JPQLSerializer.visitOperation(JPQLSerializer.java:401)
	at com.mysema.query.support.SerializerBase.visit(SerializerBase.java:249)
	at com.mysema.query.support.SerializerBase.visit(SerializerBase.java:42)
	at com.mysema.query.types.OperationImpl.accept(OperationImpl.java:91)
	at com.mysema.query.support.SerializerBase.handle(SerializerBase.java:105)
	at com.mysema.query.support.SerializerBase.visitOperation(SerializerBase.java:278)
	at com.mysema.query.jpa.JPQLSerializer.visitOperation(JPQLSerializer.java:432)
	at com.mysema.query.support.SerializerBase.visit(SerializerBase.java:249)
	at com.mysema.query.support.SerializerBase.visit(SerializerBase.java:42)
	at com.mysema.query.types.OperationImpl.accept(OperationImpl.java:91)
	at com.mysema.query.support.SerializerBase.handle(SerializerBase.java:105)
	at com.mysema.query.support.SerializerBase.visitOperation(SerializerBase.java:280)
	at com.mysema.query.jpa.JPQLSerializer.visitOperation(JPQLSerializer.java:432)
	at com.mysema.query.support.SerializerBase.visit(SerializerBase.java:249)
	at com.mysema.query.support.SerializerBase.visit(SerializerBase.java:42)
	at com.mysema.query.types.OperationImpl.accept(OperationImpl.java:91)
	at com.mysema.query.support.SerializerBase.handle(SerializerBase.java:105)
	at com.mysema.query.support.SerializerBase.handle(SerializerBase.java:137)
	at com.mysema.query.jpa.JPQLSerializer.serialize(JPQLSerializer.java:194)
	at com.mysema.query.jpa.JPAQueryBase.serialize(JPAQueryBase.java:57)
	at com.mysema.query.jpa.impl.AbstractJPAQuery.createQuery(AbstractJPAQuery.java:124)
	at com.mysema.query.jpa.impl.AbstractJPAQuery.createQuery(AbstractJPAQuery.java:94)
	at com.mysema.query.jpa.impl.AbstractJPAQuery.list(AbstractJPAQuery.java:245)
	at frol.FooTest.caseExpression(FooTest.java:65)
</pre></code>
See also maven [Test project on GitHub](https://github.com/wrungel/qdsl-bugs/tree/master/case-in-3.6.0).

**Comment by wrungel** [comment]
Used QueryDsl version: **3.6.0**

**Comment by Shredder121** [comment]
Thank you for the report, although [we recently fixed this problem already](https://github.com/querydsl/querydsl/issues/1088).
Therefore I am closing this issue.
