### ISSUE TITLE
querydsl sql many-to-many-to-many 

### ISSUE THREAD

**Issue by ali-rezvani** [querydsl/querydsl#1115]
Hi
I am beginer in querydsl and sql and I want to implement many-to-many-to-many relation in my code with qbean class. This is my QBean classes:

``` java
final QBean<SecurableItemType> securableItemTypeBean = bean(SecurableItemType.class, securableItemType.all());
final QBean<SecurableItem> securableItemBean = bean(SecurableItem.class,
        securableItem.securableItemId,
        securableItem.name
        , securableItem.uniqueId, securableItem.position, securableItem.enabled
);

final QBean<RoleSecurableItem> roleSecurableItemBean = bean(RoleSecurableItem.class
        ,securableItemBean.as("securableItem")
);

final QBean<Role> roleBean = bean(Role.class, role.roleId, role.name
        , role.enabled, role.uniqueId, role.description
        , list(roleSecurableItemBean).as("roleSecurableItems")
);

final QBean<UserRole> userRoleBean = bean(UserRole.class
        , roleBean.as("role")
);



final QBean<AppUser> appUserBean = bean(AppUser.class, appUser.userId, appUser.personalCode
        , appUser.firstName, appUser.lastName, appUser.username, appUser.password, appUser.enabled
        , appUser.picture, appUser.organId, appUser.description, appUser.loginTry, appUser.userLocked
        , list(userRoleBean).as("roles")

);
```

and this is my query

``` java
return queryFactory
            .from(appUser)
            .fullJoin(appUser._fkuserRole472634, userRole)
            .fullJoin(userRole.fkuserRole820825, role)
            .fullJoin(role._fkroleSecur628757, roleSecurableItem)
            .fullJoin(roleSecurableItem.fkroleSecur233998, securableItem)
            .fullJoin(appUser._fkuserIpAd409749, userIpAddress)           
            .where(where)
            .transform(
                    GroupBy.groupBy(appUser.userId)
                            .list(appUserBean)
            )
            ;
```

but when i performing code this error occur:

```
java.lang.IllegalArgumentException: argument type mismatch
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_20-ea]
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_20-ea]
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_20-ea]
! at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_20-ea]
! at com.mysema.query.types.QBean.newInstance(QBean.java:268) ~[querydsl-core-3.5.1.jar:na]
! at com.mysema.query.types.FactoryExpressionUtils.compress(FactoryExpressionUtils.java:155) ~[querydsl-core-3.5.1.jar:na]
! at com.mysema.query.types.FactoryExpressionUtils.compress(FactoryExpressionUtils.java:154) ~[querydsl-core-3.5.1.jar:na]
! at com.mysema.query.types.FactoryExpressionUtils.access$100(FactoryExpressionUtils.java:28) ~[querydsl-core-3.5.1.jar:na]
! at com.mysema.query.types.FactoryExpressionUtils$FactoryExpressionAdapter.newInstance(FactoryExpressionUtils.java:58) ~[querydsl-core-3.5.1.jar:na]
! at com.mysema.query.group.AbstractGroupByTransformer$FactoryExpressionAdapter.newInstance(AbstractGroupByTransformer.java:61) ~[querydsl-core-3.5.1.jar:na]
! at com.mysema.query.types.FactoryExpressionUtils$FactoryExpressionAdapter.newInstance(FactoryExpressionUtils.java:58) ~[querydsl-core-3.5.1.jar:na]
! at com.mysema.query.sql.AbstractSQLQuery.newInstance(AbstractSQLQuery.java:420) ~[querydsl-sql-3.5.1.jar:na]
! at com.mysema.query.sql.AbstractSQLQuery.access$000(AbstractSQLQuery.java:42) ~[querydsl-sql-3.5.1.jar:na]
! at com.mysema.query.sql.AbstractSQLQuery$3.produceNext(AbstractSQLQuery.java:251) ~[querydsl-sql-3.5.1.jar:na]
! at com.mysema.query.sql.SQLResultIterator.next(SQLResultIterator.java:85) ~[querydsl-sql-3.5.1.jar:na]
```

thanks.

**Comment by timowest** [comment]
Could you debug for which setter invocation this exception is thrown?

**Comment by ali-rezvani** [comment]
Thanks for your attention timowest.
I debug this and ه noticed  when i setting roleSecurableItems this error occurs.
For simplicity i change my code to this:
QBean classes:
       

     final QBean<RoleSecurableItem> roleSecurableItemBean = bean(RoleSecurableItem.class
      );
    final QBean<Role> roleBean = bean(Role.class, role.roleId, role.name
            , role.enabled, role.uniqueId, role.description
            , list(roleSecurableItemBean).as("securableItems")
      );

    final QBean<UserRole> userRoleBean = bean(UserRole.class
            , roleBean.as("role")
      );

       final QBean<AppUser> appUserBean = bean(AppUser.class, appUser.userId, appUser.personalCode
            , appUser.firstName, appUser.lastName, appUser.username, appUser.password, appUser.enabled
            , appUser.picture, appUser.organId, appUser.description, appUser.loginTry, appUser.userLocked
            , list(userRoleBean).as("roles")
      );

and query:
    
      return queryFactory
                .from(appUser)
                .fullJoin(appUser._fkuserRole472634, userRole)
                .fullJoin(userRole.fkuserRole820825, role)
                .fullJoin(role._fkroleSecur628757, roleSecurableItem)
                .where(where)
                .transform(GroupBy.groupBy(appUser.userId).list(appUserBean));

**Comment by ali-rezvani** [comment]
this is my Role.java class
 
     public class Role{
       private BigInteger roleId;
       private String uniqueId;
       private String name;
       private String description;
       private Byte enabled;
       private List<RoleSecurableItem> securableItems;
       .
       .
       .
       /...setters and getters
