### ISSUE TITLE
Support Date Time literals serialization in case constructs

### ISSUE THREAD

**Issue by andrei-ivanov** [querydsl/querydsl#1205]
I'm trying to create a case expression like (simplified):
```java
new CaseBuilder()
	.when(medicalCheck.lastCheck.isNull()).then(MedicalCheckStatus.EXPIRED.ordinal())
	.when(medicalCheck.lastCheck.gt(lastCheckSoftLimit)).then(MedicalCheckStatus.VALID.ordinal())
	.otherwise(MedicalCheckStatus.PENDING.ordinal());
```

```java
import org.joda.time.LocalDate;

public class MedicalCheck implements Serializable {
	@Column(name = "last_check")
	private LocalDate lastCheck;
```

When executing this with JPA (Querydsl-3.6.1, Hibernate-4.3.8), I get this error:
```
java.lang.IllegalArgumentException: Unsupported constant 2014-02-22
	at com.mysema.query.jpa.JPQLSerializer.visitLiteral(JPQLSerializer.java:334)
	at com.mysema.query.jpa.JPQLSerializer.visitConstant(JPQLSerializer.java:298)
	at com.mysema.query.support.SerializerBase.visit(SerializerBase.java:208)
	at com.mysema.query.support.SerializerBase.visit(SerializerBase.java:42)
	at com.mysema.query.types.ConstantImpl.accept(ConstantImpl.java:127)
	at com.mysema.query.support.SerializerBase.handle(SerializerBase.java:105)
	at com.mysema.query.support.SerializerBase.visitOperation(SerializerBase.java:283)
	at com.mysema.query.jpa.JPQLSerializer.visitOperation(JPQLSerializer.java:440)
	at com.mysema.query.support.SerializerBase.visit(SerializerBase.java:249)
	at com.mysema.query.support.SerializerBase.visit(SerializerBase.java:42)
	at com.mysema.query.types.OperationImpl.accept(OperationImpl.java:90)
	at com.mysema.query.support.SerializerBase.handle(SerializerBase.java:105)
	at com.mysema.query.support.SerializerBase.visitOperation(SerializerBase.java:278)
	at com.mysema.query.jpa.JPQLSerializer.visitOperation(JPQLSerializer.java:443)
	at com.mysema.query.support.SerializerBase.visit(SerializerBase.java:249)
	at com.mysema.query.support.SerializerBase.visit(SerializerBase.java:42)
	at com.mysema.query.types.OperationImpl.accept(OperationImpl.java:90)
	at com.mysema.query.support.SerializerBase.handle(SerializerBase.java:105)
	at com.mysema.query.support.SerializerBase.visitOperation(SerializerBase.java:280)
	at com.mysema.query.jpa.JPQLSerializer.visitOperation(JPQLSerializer.java:443)
	at com.mysema.query.support.SerializerBase.visit(SerializerBase.java:249)
	at com.mysema.query.support.SerializerBase.visit(SerializerBase.java:42)
	at com.mysema.query.types.OperationImpl.accept(OperationImpl.java:90)
	at com.mysema.query.support.SerializerBase.handle(SerializerBase.java:105)
	at com.mysema.query.support.SerializerBase.visitOperation(SerializerBase.java:280)
	at com.mysema.query.jpa.JPQLSerializer.visitOperation(JPQLSerializer.java:443)
	at com.mysema.query.support.SerializerBase.visit(SerializerBase.java:249)
	at com.mysema.query.support.SerializerBase.visit(SerializerBase.java:42)
	at com.mysema.query.types.OperationImpl.accept(OperationImpl.java:90)
	at com.mysema.query.support.SerializerBase.handle(SerializerBase.java:105)
	at com.mysema.query.support.SerializerBase.visitOperation(SerializerBase.java:278)
	at com.mysema.query.jpa.JPQLSerializer.visitOperation(JPQLSerializer.java:443)
	at com.mysema.query.support.SerializerBase.visit(SerializerBase.java:249)
	at com.mysema.query.support.SerializerBase.visit(SerializerBase.java:42)
	at com.mysema.query.types.OperationImpl.accept(OperationImpl.java:90)
	at com.mysema.query.support.SerializerBase.handle(SerializerBase.java:105)
	at com.mysema.query.jpa.JPQLSerializer.serialize(JPQLSerializer.java:210)
	at com.mysema.query.jpa.JPAQueryBase.serialize(JPAQueryBase.java:57)
	at com.mysema.query.jpa.impl.AbstractJPAQuery.createQuery(AbstractJPAQuery.java:124)
	at com.mysema.query.jpa.impl.AbstractJPAQuery.count(AbstractJPAQuery.java:79)
	at org.springframework.data.jpa.repository.support.QueryDslJpaRepository.findAll(QueryDslJpaRepository.java:125)
```
I see that 41b73ea8166ea21e7063e8cb1dcc98c97b43dffd added a TODO for date times. Can you please complete this task? :)

**Comment by timowest** [comment]
The official JPQL Date/Time literals are unfortunately not supported in Hibernate https://hibernate.atlassian.net/browse/HHH-8653
