### ISSUE TITLE
Weird Behavior for byte[] array in Hibernate Objects

### ISSUE THREAD

**Issue by voor** [querydsl/querydsl#1431]
Attempting to utilize a class that has a field mapping byte[] to Blob.  Getting the following error:

```
[B cannot be cast to [Ljava.lang.Object;
! java.lang.ClassCastException: [B cannot be cast to [Ljava.lang.Object;
! at com.querydsl.jpa.hibernate.HibernateUtil.setValue(HibernateUtil.java:71) ~[querydsl-jpa-4.0.2.jar:na]
! at com.querydsl.jpa.hibernate.HibernateUtil.setConstants(HibernateUtil.java:63) ~[querydsl-jpa-4.0.2.jar:na]
! at com.querydsl.jpa.hibernate.AbstractHibernateQuery.createQuery(AbstractHibernateQuery.java:105) ~[querydsl-jpa-4.0.2.jar:na]
! at com.querydsl.jpa.hibernate.AbstractHibernateQuery.createQuery(AbstractHibernateQuery.java:97) ~[querydsl-jpa-4.0.2.jar:na]
! at com.querydsl.jpa.hibernate.AbstractHibernateQuery.fetch(AbstractHibernateQuery.java:174) ~[querydsl-jpa-4.0.2.jar:na]
```

**Comment by voor** [comment]
Looks like it's because a byte array is considered an array.

It's attempting to cast the array to an Object array, which you can't do with a byte array.

```java
    private static void setValue(Query query, String key, Object val) {
        if (val instanceof Collection<?>) {
            query.setParameterList(key, (Collection<?>) val);
        } else if (val.getClass().isArray()) {
            query.setParameterList(key, (Object[]) val);
        } else if (TYPES.containsKey(val.getClass())) {
            query.setParameter(key, val, TYPES.get(val.getClass()));
        } else {
            query.setParameter(key, val);
        }
    }
```

Would this possibly fix it?  (Or something similar)

```java
    private static void setValue(Query query, String key, Object val) {
        if (val instanceof Collection<?>) {
            query.setParameterList(key, (Collection<?>) val);
        } else if (val.getClass().equals(byte[].class)) {
            ...
        } else if (val.getClass().isArray()) {
            query.setParameterList(key, (Object[]) val);
        } else if (TYPES.containsKey(val.getClass())) {
            query.setParameter(key, val, TYPES.get(val.getClass()));
        } else {
            query.setParameter(key, val);
        }
    }
```

**Comment by Shredder121** [comment]
Sorry for not commenting earlier.
As for your PR, I think that it can be solved using the `TYPES` map (if we reorder the statements, there are HibernateTypes for byte arrays to blobs, so it can be handled by Hibernate).

I do need to ask whether it was @timowest's intention to make it customizable.

**Comment by voor** [comment]
No worries, this is just a showstopper for me, and I wanted to do whatever I could to help it get resolved.
