### ISSUE TITLE
Using StringPath(String var) with spring data 1.8.x or newer causes IllegalArgumentException

### ISSUE THREAD

**Issue by anaq1** [querydsl/querydsl#1486]
In spring data 1.8.x was changed the way of resolving sort property, now it requires a parent. When I use StringPath(String var) constructor, where no parent is specified, spring data throws this exception:
```
java.lang.IllegalArgumentException: Property must not null or empty!
	at org.springframework.data.domain.Sort$Order.<init>(Sort.java:320) ~[spring-data-commons-1.9.3.RELEASE.jar:na]
	at org.springframework.data.domain.Sort$Order.<init>(Sort.java:282) ~[spring-data-commons-1.9.3.RELEASE.jar:na]
	at org.springframework.data.domain.Sort$Order.<init>(Sort.java:304) ~[spring-data-commons-1.9.3.RELEASE.jar:na]
	at org.springframework.data.querydsl.QSort.toOrder(QSort.java:98) ~[spring-data-commons-1.9.3.RELEASE.jar:na]
	at org.springframework.data.querydsl.QSort.toOrders(QSort.java:76) ~[spring-data-commons-1.9.3.RELEASE.jar:na]
	at org.springframework.data.querydsl.QSort.<init>(QSort.java:59) ~[spring-data-commons-1.9.3.RELEASE.jar:na]
	at org.springframework.data.querydsl.QSort.<init>(QSort.java:50) ~[spring-data-commons-1.9.3.RELEASE.jar:na]
```

The change is in class org.springframework.data.querydsl.QSort in method toOrder(...). You can compare it here:

Version 1.7.x: https://github.com/spring-projects/spring-data-commons/blob/1.7.x/src/main/java/org/springframework/data/querydsl/QSort.java

Version 1.8.x: https://github.com/spring-projects/spring-data-commons/blob/1.8.x/src/main/java/org/springframework/data/querydsl/QSort.java

Tested on version 3.6.6. I looked also in sources of 4.0.3 and the way of constructing Path Metadata in PathMetadataFactory is the same (null parent), so I think the problem will be also in this version.

Michal

**Comment by Shredder121** [comment]
We are not the authors of QSort, that is Spring Data source.

To me though, it seems a little strange that when a sort target has no parent (think aliases, or unambiguous paths) the order just drops not only the variable name, but everything.
I think their recursive function returns too early.

Have you tried opening the issue at Spring Data? They use JIRA, but you can link back to here, if they want to coordinate or otherwise resolve this issue.

**Comment by anaq1** [comment]
I was not sure, if it's spring or querydsl related. Created jira https://jira.spring.io/browse/DATAJPA-778

**Comment by Shredder121** [comment]
Thank you, I have placed a comment that let's them know that we know about the issue.

**Comment by Shredder121** [comment]
Closing this issue in favor of Spring's JIRA.
