### ISSUE TITLE
JPAQueryBase.toString() throws IllegalArgumentException: "no joins given"

### ISSUE THREAD

**Issue by olivergierke** [querydsl/querydsl#1543]
In Querydsl 3.x the following worked:

```java
new JPAQuery<Object>(em).
  select(QUser.user).
  orderBy(QUser.user.firstname.desc()).
  toString();
```

In 4.0 this results in an `IllegalArgumentException`:

```
java.lang.IllegalArgumentException: No joins given
	at com.querydsl.jpa.JPAQueryBase.serialize(JPAQueryBase.java:48)
	at com.querydsl.jpa.JPAQueryBase.toString(JPAQueryBase.java:215)
	at org.springframework.data.jpa.repository.support.QuerydslIntegrationTests.testname(QuerydslIntegrationTests.java:77)
```

Isn't it a bit harsh to outright reject `toString()` calls on queries without a join? ;)

**Comment by timowest** [comment]
I agree that toString() shouldn't throw Exceptions in these cases.
