### ISSUE TITLE
Batch insert causes ORA-01000: maximum open cursors exceeded

### ISSUE THREAD

**Issue by holgerstolzenberg** [querydsl/querydsl#1545]
I had the following method inserting a bulk of objects by executing a insert foreach entry in the list. I am using spring transaction support in conjunction with querydsl.

```java
@Transactional
public void batchSave(final List<Instruction> instructions) {
  long idState = 5
  
  for (Instruction instruction : instructions) {
     queryFactory.insert(siJournal)
       .columns(siJournal.idState,siJournal.pkId,siJournal.pkVersion)
       .values(idState, instruction.getId(), instruction.getVersion())
       .execute();
  }
}
```

Everything works as expected, but performance wise, this is not desired. So I rewrote it using the querydsl batch support. I came up with the following code:

```java
@Transactional
public void batchSave(final List<Instruction> instructions) {
  long idState = 5

  SQLInsertClause insert=queryFactory.insert(siJournal);
  for (Instruction instruction : instructions) {
    insert
      .columns(siJournal.idExportState,siJournal.pkId,siJournal.pkVersion)
      .values(exportStateId, instruction.getId(), instruction.getVersion())
      .addBatch();
  }
  insert.execute();
}
```

I am running against a Oracle Express 11g on a virtual dev box. After approx 200 inserts, a `java.sql.SqlException` is thrown because of the underlying `ORA-01000`. If I understand the problem correctly, it seems I need to commit somewhere within the transaction, lets say after 100 rows to close up the underlying `PreparedStatements`? Please also see http://stackoverflow.com/questions/12192592/java-sql-sqlexception-ora-01000-maximum-open-cursors-exceeded.

Is the batch code above correct? Missed I some querydsl specific configuration. How can I commit after every 100th row? Or do I need to do the paging outside the transaction of the service method?

**Comment by timowest** [comment]
Sorry, I didn't yet have time to look into this. Your batch usage looks good though.

**Comment by timowest** [comment]
If you don't customize your Querydsl SQL configuration to serialize your literals in the SQL query, there will be only one prepared statement involved.

To commit after every 100th row, I'd partition the instructions into lists of 100 elements and persist those transactionally.

Could you provide the full stacktrace?

**Comment by holgerstolzenberg** [comment]
Sorry for the late response. At first, the full stacktrace as requested

```
org.springframework.jdbc.UncategorizedSQLException: ; uncategorized SQLException for SQL [insert into XXX (YYY) values (37, 173446927, 0)]; SQL state [60000]; error code [604]; ORA-00604: error occurred at recursive SQL level 1
ORA-01000: maximum open cursors exceeded
; nested exception is java.sql.SQLException: ORA-00604: error occurred at recursive SQL level 1
ORA-01000: maximum open cursors exceeded

  at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:84)
  at com.querydsl.sql.spring.SpringExceptionTranslator.translate(SpringExceptionTranslator.java:49)
  at com.querydsl.sql.Configuration.translate(Configuration.java:453)
  at com.querydsl.sql.dml.SQLInsertClause.execute(SQLInsertClause.java:396)
  at com.eex.bdwh.adp.persistence.appdata.SiJournalService.batchSave(SiJournalService.java:78)
  at com.eex.bdwh.adp.persistence.appdata.SiJournalService$$FastClassBySpringCGLIB$$a88bed1f.invoke(<generated>)
  at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
  at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)
  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
  at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
  at org.springframework.transactirceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
  at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
  at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)
  at com.eex.bdwh.adp.persistence.appdata.SiJournalService$$EnhancerBySpringCGLIB$$991631fd.batchSave(<generated>)
  at com.eex.bdwh.adp.export.smsssi.StoreJournalHandler.doHandle(StoreJournalHandler.java:32)
  at com.eex.bdwh.adp.export.common.AbstractHandler.handle(AbstractHandler.java:36)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:483)
  at org.apache.camel.component.bean.MethodInfo.invoke(MethodInfo.java:408)
  at org.apache.camel.component.bean.MethodInfo$1.doProceed(MethodInfo.java:279)
  at org.apache.camel.component.bean.MethodInfo$1.proceed(MethodInfo.java:252)
  at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:171)
  at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77)
  at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:448)
  at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109)
  at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:329)
  at org.apache.camel.processor.DefaultErrorHandler.process(DefaultErrorHandler.java:56)
  at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:166)
  at org.apache.camel.processor.Pipeline.process(Pipeline.java:118)
  at org.apache.camel.processor.Pipeline.process(Pipeline.java:80)
  at org.apache.camel.processor.Cocessor.process(ChoiceProcessor.java:111)
  at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77)
  at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:448)
  at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109)
  at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:329)
  at org.apache.camel.processor.DefaultErrorHandler.process(DefaultErrorHandler.java:56)
  at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:166)
  at org.apache.camel.processor.Pipeline.process(Pipeline.java:118)
  at org.apache.camel.processor.Pipeline.process(Pipeline.java:80)
  at org.apache.camel.processor.FilterProcessor.process(FilterProcessor.java:58)
  at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77)
  at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:448)
  at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109)
  at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:329)
  at org.apache.camel.processor.DefaultErrorHandler.process(DefaultErrorHandler.java:56)
  at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:166)
  at org.apache.camel.processor.Pipeline.process(Pipeline.java:118)
  at org.apache.camel.processor.Pipeline.process(Pipeline.java:80)
  at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:448)
  at org.apache.camel.spring.spi.TransactionErrorHandler.processByErrorHandler(TransactionErrorHandler.java:218)
  at org.apache.camel.spring.spi.TransactionErrorHandler.process(TransactionErrorHandler.java:99)
  at org.apache.camel.spring.spi.TransactionErrorHandler.process(TransactionErrorHandler.java:112)
  at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77)
  at org.apache.camel.processor.RedelrorHandler.process(RedeliveryErrorHandler.java:448)
  at org.apache.camel.spring.spi.TransactionErrorHandler.processByErrorHandler(TransactionErrorHandler.java:218)
  at org.apache.camel.spring.spi.TransactionErrorHandler$1.doInTransactionWithoutResult(TransactionErrorHandler.java:181)
  at org.springframework.transaction.support.TransactionCallbackWithoutResult.doInTransaction(TransactionCallbackWithoutResult.java:34)
  at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
  at org.apache.camel.spring.spi.TransactionErrorHandler.doInTransactionTemplate(TransactionErrorHandler.java:174)
  at org.apache.camel.spring.spi.TransactionErrorHandler.processInTransaction(TransactionErrorHandler.java:134)
  at org.apache.camel.spring.spi.TransactionErrorHandler.process(TransactionErrorHandler.java:103)
  at org.apache.camel.spring.spi.TransactionErrorHandler.process(TransactionErrorHandler.java:112)
  at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191)
  at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191)
  at org.apache.camel.component.direct.DirectProducer.process(DirectProducer.java:51)
  at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:129)
  at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77)
  at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:448)
  at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191)
  at org.apache.camel.processor.Pipeline.process(Pipeline.java:118)
  at org.apache.camel.processor.Pipeline.process(Pipeline.java:80)
  at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191)
  at org.apache.camel.component.direct.DirectProducer.process(DirectProducer.java:51)
  at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:129)
  at org.apache.camel.management.InstrumentationProcessor.process(IntationProcessor.java:77)
  at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:448)
  at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191)
  at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191)
  at org.apache.camel.processor.loadbalancer.QueueLoadBalancer.process(QueueLoadBalancer.java:44)
  at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109)
  at org.apache.camel.processor.loadbalancer.LoadBalancerSupport.process(LoadBalancerSupport.java:87)
  at org.apache.camel.component.quartz2.CamelJob.execute(CamelJob.java:56)
  at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
  at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.sql.SQLException: ORA-00604: error occurred at recursive SQL level 1
ORA-01000: maximum open cursors exceeded

  at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
  at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
  at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1059)
  at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:522)
  at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:257)
  at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:587)
  at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:225)
  at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:53)
  at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
  at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1150)
  at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:4798)
  at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:4875)
  at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
  at com.zaxxer.hikari.proxy.PreparedStatementProxy.executeUpdate(PreparedStatementPro:61)ava
  at com.zaxxer.hikari.proxy.PreparedStatementJavassistProxy.executeUpdate(PreparedStatementJavassistProxy.java)
  at com.querydsl.sql.dml.AbstractSQLClause.executeBatch(AbstractSQLClause.java:162)
  at com.querydsl.sql.dml.AbstractSQLClause.executeBatch(AbstractSQLClause.java:178)
  at com.querydsl.sql.dml.SQLInsertClause.execute(SQLInsertClause.java:390)
  ... 83 common frames omitted
```

**Comment by holgerstolzenberg** [comment]
Second, it is of course possible to partition the list into lists of a certain batch size, but I do not think that it should be done by the client application. This would mean I need to implement this partitioning everywhere a want to use batch clauses.

For me this should be done 'behind' the querydsl facade. The batch size should be configurable globally, e.g.

```java
final com.querydsl.sql.Configuration configuration =  new com.querydsl.sql.Configuration(dialect);
configuration.setBatchSize(100);
```

or it should be specified with the query, e.g.

```java
insert.execute(100);
```

or something similar.

**Comment by timowest** [comment]
I couldn't replicate this with normal batching, but with `setUseLiterals(true)` on. Based on your exception stacktrace it looks like you serialize literals also directly into the SQL.

Could you confirm how your configuration looks like concerning this?

**Comment by timowest** [comment]
Here is the stacktrace I got

```

com.querydsl.core.QueryException: Caught BatchUpdateException for insert into SURVEY (ID, NAME) values (2999, '2999')
	at com.querydsl.sql.support.JavaSE7SQLExceptionWrapper.wrap(JavaSE7SQLExceptionWrapper.java:41)
	at com.querydsl.sql.DefaultSQLExceptionTranslator.translate(DefaultSQLExceptionTranslator.java:48)
	at com.querydsl.sql.Configuration.translate(Configuration.java:453)
	at com.querydsl.sql.dml.SQLInsertClause.execute(SQLInsertClause.java:396)
	at com.querydsl.sql.InsertBase.Insert_Batch_Large(InsertBase.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:24)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
	Suppressed: java.sql.SQLException: ORA-01000: maximum open cursors exceeded

		at oracle.jdbc.driver.SQLStateMapping.newSQLException(SQLStateMapping.java:70)
		at oracle.jdbc.driver.DatabaseError.newSQLException(DatabaseError.java:133)
		at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:206)
		at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:455)
		at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:413)
		at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:1034)
		at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:194)
		at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:953)
		at oracle.jdbc.driver.OraclePreparedStatement.executeForRowsWithTimeout(OraclePreparedStatement.java:9215)
		at oracle.jdbc.driver.OraclePreparedStatement.executeBatch(OraclePreparedStatement.java:9315)
		at oracle.jdbc.driver.OracleStatementWrapper.executeBatch(OracleStatementWrapper.java:211)
		at com.querydsl.sql.dml.AbstractSQLClause.executeBatch(AbstractSQLClause.java:164)
		at com.querydsl.sql.dml.AbstractSQLClause.executeBatch(AbstractSQLClause.java:178)
		at com.querydsl.sql.dml.SQLInsertClause.execute(SQLInsertClause.java:390)
		... 38 more
Caused by: java.sql.BatchUpdateException: ORA-01000: maximum open cursors exceeded

	at oracle.jdbc.driver.DatabaseError.throwBatchUpdateException(DatabaseError.java:629)
	at oracle.jdbc.driver.OraclePreparedStatement.executeBatch(OraclePreparedStatement.java:9409)
	at oracle.jdbc.driver.OracleStatementWrapper.executeBatch(OracleStatementWrapper.java:211)
	at com.querydsl.sql.dml.AbstractSQLClause.executeBatch(AbstractSQLClause.java:164)
	at com.querydsl.sql.dml.AbstractSQLClause.executeBatch(AbstractSQLClause.java:178)
	at com.querydsl.sql.dml.SQLInsertClause.execute(SQLInsertClause.java:390)
	... 38 more
```

**Comment by holgerstolzenberg** [comment]
So here is my Spring setup:

```java
@Bean
  public SpringConnectionProvider springConnectionProvider(DataSource dataSource) {
    return new SpringConnectionProvider(dataSource);
  }

  @Bean
  public com.querydsl.sql.Configuration configuration(@Value("${schemas.x}") String x,
    @Value("${schemas.y}") String y, @Value("${schemas.z}") String z,
    @Value("${schemas.n}") String n) {

    final SQLTemplates dialect = OracleTemplates.builder().printSchema().build();

    final com.querydsl.sql.Configuration configuration =
      new com.querydsl.sql.Configuration(dialect);
    configuration.setExceptionTranslator(new SpringExceptionTranslator());
    configuration.setUseLiterals(true);

    registerSchemaOverride(configuration, X, x);
    registerSchemaOverride(configuration, Y, y);
    registerSchemaOverride(configuration, Z, z);
    registerSchemaOverride(configuration, N, n);

    return configuration;
  }

  @Bean
  public SQLQueryFactory queryFactory(com.querydsl.sql.Configuration configuration,
    SpringConnectionProvider provider) {
    return new SQLQueryFactory(configuration, provider);
  }
```

So yes, I am using `setUseLiterals(true)`. But shouldn´t that make any difference. I just got the Spring config somewhere from the web. I am not sure if really need `setUseLiterals(true)` though. The method javadoc is not very helpful ;-)

**Comment by timowest** [comment]
setUserLiterals(true) will force the serialization of the literals directly into the query. So the batch will only be emulated. I'll improve the javadocs in a PR.
