### ISSUE TITLE
Problems with contains in 3.6.7

### ISSUE THREAD

**Issue by leofromgroza** [querydsl/querydsl#1554]
I have such code:
```
// Model
class User {
...
@ElementCollection(fetch = FetchType.EAGER)
@MapKeyColumn(name = "name")
@Column(name = "value")
@CollectionTable(name = "property", joinColumns = @JoinColumn(name = "user_id") )
private Map<String, String> properties = new HashMap<String, String>();
...
}
// DAO
return query.from(QUser.user).where(QUser.user.properties.contains(propertyName, propertyValue)).list(QUser.user);
```
and such DB structure:
```
Table user(id,first_name,last_name,...)
Table properties(user_id,name,value)
```
It is perfectly working in 3.5.1, but after updating QueryDSL to 3.6.7, it start throwing such exception
> java.lang.IllegalArgumentException: org.hibernate.hql.ast.QuerySyntaxException: unexpected AST node:  [select user from org.package.User User
  inner join user.properties as user_properties_781c6 with key(user_properties_781c6) = ?1
where user_properties_781c6 = ?2]
Looks like a bug.

**Comment by timowest** [comment]
Could you provide the full stacktrace?

**Comment by leofromgroza** [comment]
Full Exception stacktrace:
>org.hibernate.hql.ast.QuerySyntaxException: unexpected AST node:  [select user from org.package.User user
  inner join user.properties as user_properties_5d0f0 with key(user_properties_5d0f0) = ?1 where user_properties_5d0f0 = ?2]
	at org.hibernate.hql.ast.QuerySyntaxException.convert(QuerySyntaxException.java:54) [hibernate-core-3.6.10.Final.jar:3.6.10.Final]
	at org.hibernate.hql.ast.QuerySyntaxException.convert(QuerySyntaxException.java:47) [hibernate-core-3.6.10.Final.jar:3.6.10.Final]
	at org.hibernate.hql.ast.ErrorCounter.throwQueryException(ErrorCounter.java:82) [hibernate-core-3.6.10.Final.jar:3.6.10.Final]
	at org.hibernate.hql.ast.QueryTranslatorImpl.analyze(QueryTranslatorImpl.java:263) [hibernate-core-3.6.10.Final.jar:3.6.10.Final]
	at org.hibernate.hql.ast.QueryTranslatorImpl.doCompile(QueryTranslatorImpl.java:187) [hibernate-core-3.6.10.Final.jar:3.6.10.Final]
	at org.hibernate.hql.ast.QueryTranslatorImpl.compile(QueryTranslatorImpl.java:138) [hibernate-core-3.6.10.Final.jar:3.6.10.Final]
	at org.hibernate.engine.query.HQLQueryPlan.<init>(HQLQueryPlan.java:101) [hibernate-core-3.6.10.Final.jar:3.6.10.Final]
	at org.hibernate.engine.query.HQLQueryPlan.<init>(HQLQueryPlan.java:80) [hibernate-core-3.6.10.Final.jar:3.6.10.Final]
	at org.hibernate.engine.query.QueryPlanCache.getHQLQueryPlan(QueryPlanCache.java:124) [hibernate-core-3.6.10.Final.jar:3.6.10.Final]
	at org.hibernate.impl.AbstractSessionImpl.getHQLQueryPlan(AbstractSessionImpl.java:156) [hibernate-core-3.6.10.Final.jar:3.6.10.Final]
	at org.hibernate.impl.AbstractSessionImpl.createQuery(AbstractSessionImpl.java:135) [hibernate-core-3.6.10.Final.jar:3.6.10.Final]
	at org.hibernate.impl.SessionImpl.createQuery(SessionImpl.java:1770) [hibernate-core-3.6.10.Final.jar:3.6.10.Final]
	at org.hibernate.ejb.AbstractEntityManagerImpl.createQuery(AbstractEntityManagerImpl.java:277) [hibernate-entitymanager-3.6.10.Final.jar:3.6.10.Final]

**Comment by timowest** [comment]
The syntax is valid, but it looks like KEY and VALUE are not implemented in your Hibernate version https://hibernate.atlassian.net/browse/HHH-5396

**Comment by timowest** [comment]
Consider upgrading to a new Hibernate version.

**Comment by timowest** [comment]
Closing, since this is fixed in a newer Hibernate version. Please reopen, if this turns out to be something else.
