### ISSUE TITLE
HibernateDomainExporter not compatible with Hibernate 5 Configuration

### ISSUE THREAD

**Issue by tpischke** [querydsl/querydsl#1621]
Using Hibernate 5.0.2 and QueryDsl Tool 4.0.5, we have the following Problem.  The Hibernate 5 Configuration object no longer has the getMappedSuperclassMappings method.

```
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:183)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    ... 26 more
Caused by: org.apache.maven.plugin.PluginContainerException: An API incompatibility was encountered while executing: ****

SNAPSHOT:generate: java.lang.NoSuchMethodError: org.hibernate.cfg.Configuration.getMappedSuperclassMappings()Ljava/util/Iterator;
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:181)
    ... 27 more
Caused by: java.lang.NoSuchMethodError: org.hibernate.cfg.Configuration.getMappedSuperclassMappings()Ljava/util/Iterator;
    at com.querydsl.jpa.codegen.HibernateDomainExporter.collectTypes(HibernateDomainExporter.java:148)
    at com.querydsl.jpa.codegen.AbstractDomainExporter.execute(AbstractDomainExporter.java:116)
    at ch.bedag.gba.maven.plugin.querydsl.HibernateExportMojo.execute(HibernateExportMojo.java:62)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    ... 27 more
```

**Comment by tpischke** [comment]
Configuration configuration = new Configuration();
        if (hibernateConfiguration != null) {
            configuration.configure(hibernateConfiguration);
        }

        if (hibernateMappingFiles != null) {
            for (File configFile : hibernateMappingFiles) {
                configuration.addFile(configFile);
            }
        }

        try {
            HibernateDomainExporter exporter = new HibernateDomainExporter(prefix, targetFolder, configuration);
            exporter.execute();
        } catch (Exception e) {
            throw new MojoExecutionException("Cannot execute HibernateDomainExporter", e);
        }

**Comment by Shredder121** [comment]
For reference, it seems they moved
`org.hibernate.cfg.Configuration.getMappedSuperclassMappings()` to [`org.hibernate.boot.spi.MetadataImplementor.getMappedSuperclassMappingsCopy()`](https://github.com/hibernate/hibernate-orm/blob/master/hibernate-core/src/main/java/org/hibernate/boot/spi/MetadataImplementor.java#L42).

**Comment by tpischke** [comment]
Maybe we need to use JPADomainExporter instead?

**Comment by timowest** [comment]
Yes, JPADomainerExporter is a valid alternative.

**Comment by zenbones** [comment]
Been over a year and this is still a problem. If I were to use JPADomainExporter, hwo do I get hold of the Metamodle which is it's 3rd constructor parameter?

**Comment by jwgmeligmeyling** [comment]
Recommend using the `JPADomainExporter ` indeed.
