### ISSUE TITLE
ExceptionInInitializerError after upgrading from 3.6.0 to 3.6.9

### ISSUE THREAD

**Issue by CSchulz** [querydsl/querydsl#1657]
I have upgraded from querydsl 3.6.0 to 3.6.9 and some queries are failing with  _ExceptionInInitializerError_.  
I have double checked all entities, they have at least a protected empty constructor. I have tried to debug it, but didn't find at least anything helpful.

```
Position -> Order -> ProfitCenter
```

Query

```
new JPAQuery(em).from(QPosition.position).list(QPosition.position)
```

The stack trace

```
java.lang.ExceptionInInitializerError
    at de.company.prodplan.position.QPosition.<init>(QPosition.java:147)
    at de.company.prodplan.position.QPosition.<init>(QPosition.java:126)
    at de.company.prodplan.position.QPosition.<clinit>(QPosition.java:23)
    at de.company.prodplan.position.PositionRepository.findPositionFrom(PositionRepository.java:262)
    at de.company.prodplan.position.PositionRepositoryTest.shouldFindPositionWithOneDimensionInWidthOrHeight(PositionRepositoryTest.java:540)
Caused by: java.lang.NullPointerException
    at de.company.core.QProfitcenterName.<init>(QProfitcenterName.java:31)
    at de.company.prodplan.data.company.QProfitcenter.<init>(QProfitcenter.java:38)
    at de.company.prodplan.data.company.QProfitcenter.<init>(QProfitcenter.java:61)
    at de.company.prodplan.order.QOrder.<init>(QOrder.java:96)
    at de.company.prodplan.order.QOrder.<init>(QOrder.java:75)
    at de.company.prodplan.order.QOrder.<clinit>(QOrder.java:23)
    ... 39 more
```

**Comment by Shredder121** [comment]
Could you add the sources of the Q-classes?
Maybe also the sources of the accompanying domain model classes.

You can also make a small reproduction project of course.
