### ISSUE TITLE
executeWithKey and MySQL throw SQLException

### ISSUE THREAD

**Issue by serphacker** [querydsl/querydsl#1670]
executeWithKey return the following exception : 

```
Exception in thread "main" com.querydsl.core.QueryException: Caught SQLException for insert into `user` (`email`)
values (?)
	at com.querydsl.sql.DefaultSQLExceptionTranslator.translate(DefaultSQLExceptionTranslator.java:50)
	at com.querydsl.sql.Configuration.translate(Configuration.java:453)
	at com.querydsl.sql.dml.SQLInsertClause.executeWithKeys(SQLInsertClause.java:364)
	at com.querydsl.sql.dml.SQLInsertClause.executeWithKey(SQLInsertClause.java:172)
	at com.querydsl.sql.dml.SQLInsertClause.executeWithKey(SQLInsertClause.java:153)
	at com.serphacker.qdslbug.App.main(App.java:33)
Caused by: java.sql.SQLException: getGeneratedKeys error. Statement.RETURN_GENERATED_KEYS must be precised on connection.prepareStatement(String sql, int autoGeneratedKeys) or statement.executeUpdate(String sql, int autoGeneratedKeys)
	at org.mariadb.jdbc.MariaDbStatement.getGeneratedKeys(MariaDbStatement.java:800)
	at com.querydsl.sql.dml.SQLInsertClause.executeWithKeys(SQLInsertClause.java:351)
	... 3 more
```

Tested with querydsl 4.0.6 

```
        drop table if exists `user`;
        create table `user` (
            id int primary key auto_increment,
            email varchar(255)
        );
```

```
        Configuration conf = new Configuration(new MySQLTemplates());
        QUser t_user = QUser.user;

        Integer key = new SQLInsertClause(connection, conf, t_user)
            .set(t_user.email, "email")
            .executeWithKey(t_user.id);
```

Related to #1040

**Comment by timowest** [comment]
Which version of the Maria driver do you use?

**Comment by timowest** [comment]
Also do you use it with MySQL or MariaDB and which version?

**Comment by serphacker** [comment]
@timowest I tested against mariadb 10.0.22 but it looks like it's a mariadb driver issue : 

mariadb-java-client 1.3.x : exception triggered
mariadb-java-client <= 1.2.x : ok, return generated keys
mysql-connector-java 5.1.37 : ok, return generated keys

**Comment by serphacker** [comment]
https://mariadb.com/kb/en/mariadb/mariadb-connector-j-130-release-notes/

maybe it is related to : 
```
Notable changes and additions : Prepared statement on server side.
```

because the exception tell : 

```
Caused by: java.sql.SQLException: getGeneratedKeys error. Statement.RETURN_GENERATED_KEYS must be precised on connection.prepareStatement(String sql, int autoGeneratedKeys) or statement.executeUpdate(String sql, int autoGeneratedKeys)
```

**Comment by timowest** [comment]
Looks like a bug in the driver
https://github.com/MariaDB/mariadb-connector-j/blob/1.3.0/src/main/java/org/mariadb/jdbc/MariaDbConnection.java#L359

The flag Statement.RETURN_GENERATED_KEYS is missing.

**Comment by timowest** [comment]
@serphacker You should report that bug to MariaDB or switch to the MySQL driver.
