### ISSUE TITLE
fetchOne method

### ISSUE THREAD

**Issue by ali-rezvani** [querydsl/querydsl#1696]
Hi timo.
I am using  version 4.0.5 for sql module
I have an object named contractLc with contractLcId as pk
my query is this:
---
        queryFactory.select(contractGridQBean)
                .from(contractLc)
                .rightJoin(requestInquiry)
                .on(requestInquiry.requestInquiryId.eq(contractLc.requestInquiryId))
                .rightJoin(credit)
                .on(contractLc.contractLcId.eq(credit.contractLcId))
                .rightJoin(changeContractStatus)
                .on(contractLc.contractLcId.eq(changeContractStatus.contractLcId))
                .leftJoin(otherInfoContract)
                .on(contractLc.contractLcId.eq(otherInfoContract.contractLcId))
                .where(contractLc.contractLcId.eq(contractLcId))
                .fetchOne();     

When I run this query this error was ocured:
---
       com.querydsl.core.NonUniqueResultException: Only one result is allowed for fetchOne calls
	at com.querydsl.core.support.FetchableQueryBase.uniqueResult(FetchableQueryBase.java:64)
	at com.querydsl.sql.ProjectableSQLQuery.fetchOne(ProjectableSQLQuery.java:373)
	at ir.tejaratbank.loan.repository.impl.QueryDSLContractLcRepository.findGridDtoByContractLcId(QueryDSLContractLcRepository.java:311)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:201)
	at com.sun.proxy.$Proxy44.findGridDtoByContractLcId(Unknown Source)

**Comment by timowest** [comment]
fetchOne() includes a single row result check, if you just want the first row use fetchFirst() instead.

**Comment by Shredder121** [comment]
>`where(contractLc.contractLcId.eq(contractLcId))`

I think this should return only one row, since it's filtered on primary key.

@timowest are you sure this is right?

**Comment by timowest** [comment]
There are lots of joins which might increase the result row count.

**Comment by Shredder121** [comment]
They might indeed.
Then I retract my statement.

**Comment by ali-rezvani** [comment]
Thank you timowest and Shredder
I used fetchFirst()
