### ISSUE TITLE
BadSqlGrammar error on insert with HSQLDB

### ISSUE THREAD

**Issue by morungos** [querydsl/querydsl#1699]
I've just ported the `querydsl-examples-sql-spring` to use HSQLDB, and it seems to generate bad SQL, where the H2 version is fine. 

The error is:

    org.springframework.jdbc.BadSqlGrammarException: ; bad SQL grammar [insert into CUSTOMER_ADDRESS
    values ()]; nested exception is java.sql.SQLSyntaxErrorException: unexpected token: ) : line: 2

And the relevant backtrace for location is:

    Caused by: java.sql.SQLSyntaxErrorException: unexpected token: ) : line: 2
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.<init>(Unknown Source)
	at org.hsqldb.jdbc.JDBCConnection.prepareStatement(Unknown Source)
	at com.jolbox.bonecp.ConnectionHandle.prepareStatement(ConnectionHandle.java:1070)
	at com.querydsl.sql.dml.SQLInsertClause.prepareStatementAndSetParameters(SQLInsertClause.java:311)
	at com.querydsl.sql.dml.SQLInsertClause.createStatement(SQLInsertClause.java:237)
	at com.querydsl.sql.dml.SQLInsertClause.execute(SQLInsertClause.java:378)
	at com.querydsl.example.dao.CustomerDaoImpl.save(CustomerDaoImpl.java:91)

I've made this in a commit in a fork at: https://github.com/morungos/querydsl/commit/9f81ac2962ad3bb633558363a20f3846045b4121.

It seems to be related to the batch handling, but even when I remove that, it's generating array index errors at more or less the same location, so it's not easily workaroundable.

**Comment by johnktims** [comment]
Try switching `H2Templates` to `HSQLDBTemplates` in `JdbcConfiguration.java`.

**Comment by morungos** [comment]
Cool, that certainly got past that -- sorry, I'm more friendly with XML configuration, as annotations kind of make it all happen by magic for me. 

The example still doesn't work for HSQLDB, but that seems to be the tests' assumptions that the autogenerated values for ids will be mostly start at 1, where HSQLDB doesn't reset the serials on rollback, so that doesn't work. 

It'd be easier for me if the example didn't rely on this assumption: would that kind of a PR be of interest?

**Comment by timowest** [comment]
@morungos Sure, feel free to provide a PR.
