### ISSUE TITLE
Inheritance across maven projects / EclipseLink-JPA / generate-sources / "Found no type for ..."

### ISSUE THREAD

**Issue by hartmut27** [querydsl/querydsl#1726]
How can I achieve inheritance of JPA entity classes across maven projects, in combination with querydsl?

My case: In one maven project ("library") I've definied a mapped superclass for JPA Entites:
```
@MappedSuperclass
public abstract class BmEntity implements Serializable {
   @Version
   @Column
   public int version = 1;

   @Column
   public LocalDateTime created01;
}
```

In a second maven project ("usecase"), I derived the class:
```
public class BmUserAccountUnionEntity extends BmEntity {

   @ManyToOne(targetEntity = BmUserE.class)
   @JoinColumn(name = "userNumber", nullable = false)
   public BmUserE user;
}
```

pom.xml is definied as:
```
            <plugin>
                <groupId>com.mysema.maven</groupId>
                <artifactId>apt-maven-plugin</artifactId>
                <version>1.1.3</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>process</goal>
                        </goals>
                        <configuration>
                            <sourceEncoding>${project.build.sourceEncoding}</sourceEncoding>
                            <outputDirectory>target/generated-sources/java</outputDirectory>
                            <processor>com.mysema.query.apt.jpa.JPAAnnotationProcessor</processor>
                            <options>
                                <querydsl.prefix>Qdsl</querydsl.prefix>
                            </options>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```
When running maven, I receive an error:
```
java.lang.RuntimeException: java.lang.IllegalStateException: Found no type for BmEntity (com.mysema.maven:apt-maven-plugin:1.1.3:process:default:generate-sources)

org.apache.maven.plugin.MojoExecutionException: java.lang.RuntimeException: java.lang.IllegalStateException: Found no type for BmEntity
	at com.mysema.maven.apt.AbstractProcessorMojo.execute(AbstractProcessorMojo.java:362)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:331)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1362)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1360)
	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:52)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:137)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:172)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1$1.call(MavenBuilder.java:115)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1.call(MavenBuilder.java:105)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:86)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:200)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:205)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:245)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:300)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:359)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:382)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.IllegalStateException: Found no type for BmEntity
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.mysema.maven.apt.AbstractProcessorMojo.execute(AbstractProcessorMojo.java:346)
	... 32 more
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: Found no type for BmEntity
	at com.sun.tools.javac.main.Main.compile(Main.java:553)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Found no type for BmEntity
	at com.mysema.query.apt.AbstractQuerydslProcessor.addExternalParents(AbstractQuerydslProcessor.java:188)
	at com.mysema.query.apt.AbstractQuerydslProcessor.processAnnotations(AbstractQuerydslProcessor.java:159)
	at com.mysema.query.apt.AbstractQuerydslProcessor.process(AbstractQuerydslProcessor.java:98)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
	... 7 more
	pom.xml	/bmj	line 47	Maven Build Problem
```

That means, "mvn generate-sources" fails on the second project. What could I do to fix this problem?
Thanks for Your help

**Comment by Shredder121** [comment]
Could you maybe make an example project?

**Comment by timowest** [comment]
Do you generate also the entity types for the first module or only the second one?

**Comment by timowest** [comment]
In case the references project doesn't have the APT plugin configured you can declare external types to be mapped to Q-types via the `@QueryEntities`annotation, e.g. on package level.

**Comment by timowest** [comment]
Feel free to reopen, if your issue isn't fixed yet

**Comment by hartmut27** [comment]
Very sorry for the big delay. Thank You all for the help.

In the meantime I found the presumeable reason for my error case I guess.
The situation has been wired. My project dependencies were wrong: The project-to-project-dependency was definied via an explicit Eclipse build path entry.

The Maven-project-to-maven-project-dependency in the pom.xml file was missing at all.

If someone else falls into this problem also, perhaps this info could help.
