### ISSUE TITLE
QueryDSL-SQL Column Aliasing on Oracle

### ISSUE THREAD

**Issue by Redattack34** [querydsl/querydsl#1742]
The following query generates incorrect SQL on Oracle, but works for H2 and PostgreSQL.

    Configuration config = new Configuration( OracleTemplates.DEFAULT )
    SQLQuery<Boolean> query = new SQLQuery<>( conn, config )
                    .select( Expressions.FALSE.as( "TEST" ) )
                    .from( QWorkspace.workspace );

On Oracle, this generates the following query (notice no AS in the first line):

    select false TEST
    from workspace workspace

If I change the config to use PostgreSQLTemplates.DEFAULT or H2Templates.DEFAULT, it generates the correct query:

    select false as TEST
    from workspace workspace

**Comment by timowest** [comment]
What error do you get with the first query?

**Comment by Redattack34** [comment]
ORA-00904: "FALSE": invalid identifier

Here's the complete exception:

    Caused by: java.sql.SQLSyntaxErrorException: ORA-00904: "FALSE": invalid identifier
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:445)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:879)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:450)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:192)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:207)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:884)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1167)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1289)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3584)
	at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3628)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1493)
	at com.querydsl.sql.AbstractSQLQuery.fetch(AbstractSQLQuery.java:446)
	... 24 more

**Comment by Redattack34** [comment]
I forgot to mention - I tested this with QueryDSL 4.0.7.

**Comment by timowest** [comment]
Fixed by https://github.com/querydsl/querydsl/pull/1826
