### ISSUE TITLE
querydsl-jdo build error in Travis CI.

### ISSUE THREAD

**Issue by ghost** [querydsl/querydsl#1777]
Sometime below build error occured in Travis CI.
In my case, I have experienced this situation 3 ~ 5 times already.

```
[INFO] Querydsl - JDO support ............................. FAILURE [ 36.529 s]

[ERROR] --------------------
[ERROR]  Standard error from the DataNucleus tool + org.datanucleus.enhancer.DataNucleusEnhancer :
[ERROR] --------------------
[ERROR] log4j:ERROR Could not read configuration file from URL [file:src/test/resources/log4j.properties].
java.io.FileNotFoundException: src/test/resources/log4j.properties (No such file or directory)
    at java.io.FileInputStream.open0(Native Method)
    at java.io.FileInputStream.open(FileInputStream.java:195)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at java.io.FileInputStream.<init>(FileInputStream.java:93)
    at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
    at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
    at java.net.URL.openStream(URL.java:1038)
    at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:433)
    at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:468)
    at org.apache.log4j.LogManager.<clinit>(LogManager.java:122)
    at org.apache.log4j.Logger.getLogger(Logger.java:104)
    at org.datanucleus.util.Log4JLogger.<init>(Log4JLogger.java:49)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at org.datanucleus.util.NucleusLogger.getLoggerInstance(NucleusLogger.java:237)
    at org.datanucleus.util.NucleusLogger.<clinit>(NucleusLogger.java:205)
    at org.datanucleus.enhancer.DataNucleusEnhancer.<clinit>(DataNucleusEnhancer.java:86)
log4j:ERROR Ignoring configuration file [file:src/test/resources/log4j.properties].
log4j:WARN No appenders could be found for logger (DataNucleus.General).
log4j:WARN Please initialize the log4j system properly.
[ERROR] --------------------
[INFO] 
[INFO] --- maven-surefire-plugin:2.18:test (default-test) @ querydsl-jdo ---
[INFO] Surefire report directory: /home/travis/build/querydsl/querydsl/querydsl-jdo/target/surefire-reports
[INFO] Using configured provider org.apache.maven.surefire.junitcore.JUnitCoreProvider
[INFO] parallel='none', perCoreThreadCount=true, threadCount=0, useUnlimitedThreads=false, threadCountSuites=0, threadCountClasses=0, threadCountMethods=0, parallelOptimized=true
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
tests1454239238984
Running tests
Success with 362 tests
fetchCount
countDistinct
iterate
iterateDistinct
list
distinct fetch
fetchResults
distinct fetchResults
fetchOne
1800.0
1200.0
1600.0
200.0
800.0
1400.0
0.0
1000.0
600.0
400.0
1200.0
1600.0
200.0
800.0
1400.0
0.0
1000.0
600.0
400.0
Failed tests: 
  BasicsTest.list_distinct_two_sources:97 expected:<[[Product : Sony Discman [A standard discman from Sony], Product : Sony Discman [A standard discman from Sony]], [Product : Sony Discman [A standard discman from Sony], Book : JRR Tolkien - Lord of the Rings by Tolkien], [Product : Lord of the Rings by Tolkien [The classic story], Product : Sony Discman [A standard discman from Sony]], [Product : Lord of the Rings by Tolkien [The classic story], Product : Lord of the Rings by Tolkien [The classic story]]]> but was:<[[Product : Sony Discman [A standard discman from Sony], Product : Sony Discman [A standard discman from Sony]], [Product : Sony Discman [A standard discman from Sony], Product : Lord of the Rings by Tolkien [The classic story]], [Product : Lord of the Rings by Tolkien [The classic story], Product : Sony Discman [A standard discman from Sony]], [Product : Lord of the Rings by Tolkien [The classic story], Product : Lord of the Rings by Tolkien [The classic story]]]>

```

https://travis-ci.org/querydsl/querydsl/jobs/106007787

**Comment by Shredder121** [comment]
We do already know about this, but thanks for reporting anyway.
Then we have an issue to close once we fix it.

**Comment by jwgmeligmeyling** [comment]
Not using the travis builds anymore and the Github Action builds don't seem to suffer from this issue.
