### ISSUE TITLE
NullPointerException with NumberExpression.in

### ISSUE THREAD

**Issue by ThijsWouters** [querydsl/querydsl#1781]
I want to express the following SQL expression: 

```sql
select * from table where table.number_column in (1, 2, null);
```

When I try this with Querydsl like this:

```java
factory
    .select(table.all())
    .from(table)
    .where(table.numberColumn.in(asList(1, 2, null)));
```

Then a `NullPointerException` is thrown.

```java
java.lang.NullPointerException
	at com.querydsl.core.util.MathUtils.cast(MathUtils.java:52)
	at com.querydsl.core.types.dsl.NumberExpression.convert(NumberExpression.java:777)
	at com.querydsl.core.types.dsl.NumberExpression.in(NumberExpression.java:766)
	at com.querydsl.core.types.dsl.NumberExpression.in(NumberExpression.java:33)
```

I am using version 4.0.3 of Querydsl.

**Comment by ThijsWouters** [comment]
4.0.7 also has this issue.

**Comment by Shredder121** [comment]
Yeah, hmm.. maybe I could have removed the `closes` keyword. :sweat_smile: 
Reopening for the issue starter to comment.

**Comment by Shredder121** [comment]
(In light of the one-element `in` clause => `eq` translation.)

**Comment by ThijsWouters** [comment]
There are still problems with this version.

1. With one element: `eq(null) is not allowed. Use isNull() instead`

2. With multiple elements, there is still a `NullPointerException`:

```
java.lang.NullPointerException
	at com.querydsl.sql.Configuration.set(Configuration.java:239)
	at com.querydsl.sql.AbstractSQLQuery.set(AbstractSQLQuery.java:210)
	at com.querydsl.sql.AbstractSQLQuery.setParameters(AbstractSQLQuery.java:584)
	at com.querydsl.sql.AbstractSQLQuery.fetch(AbstractSQLQuery.java:441)
```

**Comment by ThijsWouters** [comment]
I am trying to fix issue 1. from above. I tried two options:

1. I remove the `IllegalArgumentException` and return `isNull()`, then it works.

2. When I remove the check that there is only one element, I get the same `NullPointerException` as in 2. above.

So, what is the correct solution? I like option 2 better, because from tests I have done, `column = 1` and `column in (1)` generate the same plan. So there is no reason to handle it differently.
