### ISSUE TITLE
Failed to execute goal com.querydsl:querydsl-maven-plugin:4.0.9.BUILD-SNAPSHOT:export

### ISSUE THREAD

**Issue by ThijsWouters** [querydsl/querydsl#1788]
I'm getting this error when I try to build my project with the version in master.

This is the full stack trace:

```
[ERROR] Failed to execute goal com.querydsl:querydsl-maven-plugin:4.0.9.BUILD-SNAPSHOT:export (default) on project xxx: Unable to parse configuration of mojo com.querydsl:querydsl-maven-plugin:4.0.9.BUILD-SNAPSHOT:export: Cannot find setter, adder nor field in com.querydsl.maven.MetadataExportMojo for 'maven.querydsl.skip' -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.querydsl:querydsl-maven-plugin:4.0.9.BUILD-SNAPSHOT:export (default) on project xxx: Unable to parse configuration of mojo com.querydsl:querydsl-maven-plugin:4.0.9.BUILD-SNAPSHOT:export: Cannot find setter, adder nor field in com.querydsl.maven.MetadataExportMojo for 'maven.querydsl.skip'
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:221)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginConfigurationException: Unable to parse configuration of mojo com.querydsl:querydsl-maven-plugin:4.0.9.BUILD-SNAPSHOT:export: Cannot find setter, adder nor field in com.querydsl.maven.MetadataExportMojo for 'maven.querydsl.skip'
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.populatePluginFields(DefaultMavenPluginManager.java:597)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:529)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:92)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: org.codehaus.plexus.component.configurator.ComponentConfigurationException: Cannot find setter, adder nor field in com.querydsl.maven.MetadataExportMojo for 'maven.querydsl.skip'
	at org.codehaus.plexus.component.configurator.converters.ComponentValueSetter.<init>(ComponentValueSetter.java:95)
	at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.processConfiguration(ObjectWithFieldsConverter.java:158)
	at org.codehaus.plexus.component.configurator.BasicComponentConfigurator.configureComponent(BasicComponentConfigurator.java:56)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.populatePluginFields(DefaultMavenPluginManager.java:567)
	... 22 more
```

The only change I made was update the version number for Querydsl. Both for the maven plugin and the library.

**Comment by ThijsWouters** [comment]
There is no issue with version 4.0.8.

**Comment by Shredder121** [comment]
Are you sure you enabled `snapshots` for your `<pluginRepository />`?
Could you share a minimalistic project?

**Comment by ThijsWouters** [comment]
I did not download it from the repository, I built this from the master branch.

I can share a project tomorrow.

**Comment by Shredder121** [comment]
Okay, if you could also then share any configuration (Maven version etc) for us to look into.

**Comment by Shredder121** [comment]
Have you had time to set up a project?
Also, could you share what tip your `HEAD` is at, so that I build the same thing as you?

**Comment by ThijsWouters** [comment]
No, I have been too busy at work.

My head is at 7bf13ccc93b2e4f557b287e557389eb2339f239a.

**Comment by hylkevds** [comment]
I get the same error:
```
mvn --version
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.8.0_91, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "3.19.0-49-generic", arch: "amd64", family: "unix"
```


On an empty directory with just this pom that doesn't even have a configuration part for the querydsl maven plugin any more. I just kept cutting bits out, error stayed the same.
```
<?xml version="1.0" encoding="UTF-8"?>
<project
    xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>test</groupId>
    <artifactId>test</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>war</packaging>

    <name>test</name>

    <properties>
        <querydsl.version>4.1.3.BUILD-SNAPSHOT</querydsl.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.querydsl</groupId>
            <artifactId>querydsl-sql-codegen</artifactId>
            <version>${querydsl.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.querydsl</groupId>
            <artifactId>querydsl-sql</artifactId>
            <version>${querydsl.version}</version>
        </dependency>
        <dependency>
            <groupId>com.querydsl</groupId>
            <artifactId>querydsl-sql-spatial</artifactId>
            <version>${querydsl.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>com.querydsl</groupId>
                <artifactId>querydsl-maven-plugin</artifactId>
                <version>${querydsl.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>export</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
```

**Comment by Shredder121** [comment]
What message does it give you?
On my machine, it says
```
Failed to execute goal com.querydsl:querydsl-maven-plugin:4.1.3.BUILD-SNAPSHOT:export (default) on project test: The parameters 'targetFolder', 'packageName' for goal com.querydsl:querydsl-maven-plugin:4.1.3.BUILD-SNAPSHOT:export are missing or invalid -> [Help 1]
```

Since it wasn't configured, like you said.

**Comment by hylkevds** [comment]
I get a different error:
`[ERROR] Failed to execute goal com.querydsl:querydsl-maven-plugin:4.1.3.BUILD-SNAPSHOT:export (default) on project test: Unable to parse configuration of mojo com.querydsl:querydsl-maven-plugin:4.1.3.BUILD-SNAPSHOT:export: Cannot find setter, adder nor field in com.querydsl.maven.MetadataExportMojo for 'maven.querydsl.skip' -> [Help 1]
`
like the original poster.

**Comment by Shredder121** [comment]
Currently at 2492722f903ad8e87170e7ac4d9c046ecb173ca8.
```
Apache Maven 3.0.5 (r01de14724cdef164cd33c7c8c2fe155faf9602da; 2013-02-19 14:51:28+0100)
Maven home: X:\Program Files\NetBeans 8.1\java\maven
Java version: 1.8.0_60, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_60\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "dos"

... the build itself

Failed to execute goal com.querydsl:querydsl-maven-plugin:4.1.3.BUILD-SNAPSHOT:export (default) on project test: The parameters 'targetFolder', 'packageName' for goal com.querydsl:querydsl-maven-plugin:4.1.3.BUILD-SNAPSHOT:export are missing or invalid -> [Help 1]
```

**Comment by hylkevds** [comment]
Here's the output.
still the weird error:

[output.txt](https://github.com/querydsl/querydsl/files/325830/output.txt)

**Comment by Shredder121** [comment]
Hmm, FWIW, I can reproduce it on a Linux box.
```
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.8.0_45-internal, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.19.0-22-generic", arch: "amd64", family: "unix"

...

[ERROR] Failed to execute goal com.querydsl:querydsl-maven-plugin:4.1.3.BUILD-SNAPSHOT:export (default) on project test: Unable to parse configuration of mojo com.querydsl:querydsl-maven-plugin:4.1.3.BUILD-SNAPSHOT:export: Cannot find setter, adder nor field in com.querydsl.maven.MetadataExportMojo for 'maven.querydsl.skip' -> [Help 1]

```

**Comment by Shredder121** [comment]
@querydsl/developers Can someone with a Mac also try?

**Comment by timowest** [comment]
I couldn't reproduce it on Mac. @Shredder121 It worked for you in Windows?

**Comment by Shredder121** [comment]
Yes, it worked for me on Windows.
I am now debugging on Linux. This is what Plexus sees on Linux:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <beanAddFullConstructor default-value="false"/>
  <beanAddToString default-value="false"/>
  <beanPrintSupertype default-value="false"/>
  <columnAnnotations default-value="false"/>
  <createScalaSources default-value="false"/>
  <exportAll default-value="false"/>
  <exportBeans default-value="false"/>
  <exportDirectForeignKeys default-value="true"/>
  <exportForeignKeys default-value="true"/>
  <exportInverseForeignKeys default-value="true"/>
  <exportPrimaryKeys default-value="true"/>
  <exportTables default-value="true"/>
  <exportViews default-value="true"/>
  <innerClassesForKeys default-value="false"/>
  <lowerCase default-value="false"/>
  <namePrefix default-value="Q"/>
  <project default-value="${project}"/>
  <schemaToPackage default-value="false"/>
  <maven.querydsl.skip default-value="false"/>
  <spatial default-value="false"/>
  <validationAnnotations default-value="false"/>
</configuration>
```

**Comment by Shredder121** [comment]
_Huh_ Interesting.
It seems to be a build-time error.

In `META-INF/maven/plugin.xml` I spotted this.

```
 970         <parameter>
 971           <name>maven.querydsl.skip</name>
 972           <type>boolean</type>
 973           <required>false</required>
 974           <editable>true</editable>
 975           <description>Whether to skip the exporting execution</description>
 976         </parameter>
```

@hylkevds Could you maybe verify that you see the same?

**Comment by Shredder121** [comment]
Actually, it's only about the root configuration:

```xml
<configuration>
  <beanAddFullConstructor implementation="boolean" default-value="false"/>
  <beanAddToString implementation="boolean" default-value="false"/>
  <beanPrintSupertype implementation="boolean" default-value="false"/>
  <columnAnnotations implementation="boolean" default-value="false"/>
  <createScalaSources implementation="boolean" default-value="false"/>
  <exportAll implementation="boolean" default-value="false"/>
  <exportBeans implementation="boolean" default-value="false"/>
  <exportDirectForeignKeys implementation="boolean" default-value="true"/>
  <exportForeignKeys implementation="boolean" default-value="true"/>
  <exportInverseForeignKeys implementation="boolean" default-value="true"/>
  <exportPrimaryKeys implementation="boolean" default-value="true"/>
  <exportTables implementation="boolean" default-value="true"/>
  <exportViews implementation="boolean" default-value="true"/>
  <innerClassesForKeys implementation="boolean" default-value="false"/>
  <lowerCase implementation="boolean" default-value="false"/>
  <namePrefix implementation="java.lang.String" default-value="Q"/>
  <project implementation="org.apache.maven.project.MavenProject" default-value="${project}"/>
  <schemaToPackage implementation="boolean" default-value="false"/>
  <maven.querydsl.skip implementation="boolean" default-value="false"/>
  <spatial implementation="boolean" default-value="false"/>
  <validationAnnotations implementation="boolean" default-value="false"/>
</configuration>
```

This should be:
```xml
<configuration>
  <beanAddFullConstructor implementation="boolean" default-value="false"/>
  <beanAddToString implementation="boolean" default-value="false"/>
  <beanPrintSupertype implementation="boolean" default-value="false"/>
  <columnAnnotations implementation="boolean" default-value="false"/>
  <createScalaSources implementation="boolean" default-value="false"/>
  <exportAll implementation="boolean" default-value="false"/>
  <exportBeans implementation="boolean" default-value="false"/>
  <exportDirectForeignKeys implementation="boolean" default-value="true"/>
  <exportForeignKeys implementation="boolean" default-value="true"/>
  <exportInverseForeignKeys implementation="boolean" default-value="true"/>
  <exportPrimaryKeys implementation="boolean" default-value="true"/>
  <exportTables implementation="boolean" default-value="true"/>
  <exportViews implementation="boolean" default-value="true"/>
  <innerClassesForKeys implementation="boolean" default-value="false"/>
  <lowerCase implementation="boolean" default-value="false"/>
  <namePrefix implementation="java.lang.String" default-value="Q"/>
  <project implementation="org.apache.maven.project.MavenProject" default-value="${project}"/>
  <schemaToPackage implementation="boolean" default-value="false"/>
  <skip implementation="boolean" default-value="false">${maven.querydsl.skip}</skip>
  <spatial implementation="boolean" default-value="false"/>
  <validationAnnotations implementation="boolean" default-value="false"/>
</configuration>
```

**Comment by Shredder121** [comment]
Okay, after some digging, I also see it now.
I wasn't thorough enough it seems.
Looking into it (looks like a problem in a Maven dependency).

**Comment by Shredder121** [comment]
I found that Maven by default includes the (ancient) 2.9 version of `maven-plugin-plugin`
http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugin-plugin/

In the meantime, there were some more releases, which fixed a small issue where it would take the `property=` name of the `@parameter` verbatim as property name.

@hylkevds Could you maybe verify if this fixes the issue? For me it does.

```
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.8.0_45-internal, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.19.0-22-generic", arch: "amd64", family: "unix"

...

[ERROR] Failed to execute goal com.querydsl:querydsl-maven-plugin:4.1.3.BUILD-SNAPSHOT:export (default) on project test: The parameters 'targetFolder', 'packageName' for goal com.querydsl:querydsl-maven-plugin:4.1.3.BUILD-SNAPSHOT:export are missing or invalid -> [Help 1]

```

**Comment by hylkevds** [comment]
Yes, cdf5e11 works. The test fails with the expected error and with this version I can also build my normal projects.

Odd that this only happened on Linux

**Comment by Shredder121** [comment]
Later I also happened to notice it, but at first building it with 3.0.5 didn't do anything.
I did have to change some dependencies to effectively debug it, but maybe that way the classpaths lined up more and made it also fail on Windows like it did on Linux 
But yes, very strange indeed.
