### ISSUE TITLE
QueryDSL generates JPQL instead of SQL for SQLDialect

### ISSUE THREAD

**Issue by somasundaramsekar** [querydsl/querydsl#1864]
Trying to get QueryDSL up for native SQL below is the Spring boot POM snippet

   ```
<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.3.3.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>1.7</java.version>
        <querydsl.version>4.0.1</querydsl.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jdbc</artifactId>
        </dependency>
        <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-validator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.hsqldb</groupId>
            <artifactId>hsqldb</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>com.querydsl</groupId>
            <artifactId>querydsl-sql</artifactId>
            <version>${querydsl.version}</version>
        </dependency>
        <dependency>
            <groupId>com.querydsl</groupId>
            <artifactId>querydsl-sql-codegen</artifactId>
            <version>${querydsl.version}</version>
            <scope>provided</scope>
        </dependency> 
    </dependencies>

    <build>
        <plugins>

             .....

            <plugin>
                <groupId>com.querydsl</groupId>
                <artifactId>querydsl-maven-plugin</artifactId>
                <version>${querydsl.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>export</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <jdbcDriver>org.hsqldb.jdbc.JDBCDriver</jdbcDriver>
                    <jdbcUrl>jdbc:hsqldb:file:${project.basedir}/db/init;files_readonly=true</jdbcUrl>
                    <jdbcUser>sa</jdbcUser>
                    <schemaPattern>PUBLIC</schemaPattern>
                    <packageName>com.example.domain</packageName>
                    <targetFolder>${project.basedir}/src/generated/java</targetFolder>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.hsqldb</groupId>
                        <artifactId>hsqldb</artifactId>
                        <version>2.2.4</version>
                    </dependency>
                    <dependency>
                        <groupId>ch.qos.logback</groupId>
                        <artifactId>logback-classic</artifactId>
                        <version>1.1.5</version>
                    </dependency>
                </dependencies>
            </plugin>

        </plugins>
    </build>
```
The code for executing the query

```
void test() throws Exception {
    QCustomer customer = QCustomer.customer;
    System.out.println(dataSource.getConnection().getMetaData().getDatabaseProductName());
    SQLTemplates dialect = SQLTemplates.DEFAULT;
    SQLQuery query = new SQLQuery(dataSource.getConnection(), dialect);
    System.out.println(query.from(customer.count()).fetch());
}
```
The execution results in SQLException as library generates JPQL(or HQL) instead of Native SQL

```
Exception in thread "main" com.querydsl.core.QueryException: Caught SQLSyntaxErrorException for 
from count(CUSTOMER.ID)
    at com.querydsl.sql.DefaultSQLExceptionTranslator.translate(DefaultSQLExceptionTranslator.java:50)
    at com.querydsl.sql.Configuration.translate(Configuration.java:451)
    at com.querydsl.sql.AbstractSQLQuery.fetch(AbstractSQLQuery.java:399)
    at com.example.DemoApplication$Test.test(DemoApplication.java:55)
    at com.example.DemoApplication.main(DemoApplication.java:36)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.sql.SQLSyntaxErrorException: unexpected token: FROM
```

**Comment by Shredder121** [comment]
The proper syntax should be:
```java
query.select(customer.count())
    .from(customer)
    .fetch()
```

**Comment by somasundaramsekar** [comment]
Thanks @Shredder121 that worked, however the reference documentation doesn't reflect this, should I keep this thread open to get that fixed?
http://www.querydsl.com/static/querydsl/3.2.2/reference/html/ch02s03.html#d0e639

**Comment by Shredder121** [comment]
Alternatively:
```java
query.from(customer)
    .fetchCount()
```

Also, you're linking the Querydsl 3 documentation.
Could you maybe comment what could be improved on the latest documentation?
http://www.querydsl.com/static/querydsl/latest/reference/html/ch02s03.html#d0e1145

**Comment by somasundaramsekar** [comment]
Thanks
