### ISSUE TITLE
Setting the beanSerializerClass to ExtendedBeanSerializer  causes Null Pointer exception when running querydsl-maven-plugin 

### ISSUE THREAD

**Issue by tomforster** [querydsl/querydsl#1868]
This seems to be related to there being no annotation on the properties in the model generated via a sql file. Everything works fine with the standard serializer, but unfortunately I need the hashcode and equals methods.

Maven Configuration:
```
<groupId>com.querydsl</groupId>
<artifactId>querydsl-maven-plugin</artifactId>
<version>4.0.9</version>
<executions>
   <execution>
      <goals>
         <goal>export</goal>
      </goals>
   </execution>
</executions>
<configuration>
   <jdbcDriver>org.h2.Driver</jdbcDriver>
   <jdbcUrl>jdbc:h2:mem:DBNAME;INIT=create schema if not exists PROJECTNAME\;runscript from '${unixBasedir}/src/main/resources/querydsl/schema.sql'</jdbcUrl>
   <packageName>PKGNAME</packageName>
   <targetFolder>${project.basedir}/target/generated-sources/java</targetFolder>
   <beanSerializerClass>com.querydsl.sql.codegen.ExtendedBeanSerializer</beanSerializerClass>
   <exportBeans>true</exportBeans>
</configuration>
<dependencies>
   <dependency>
      <groupId>com.h2database</groupId>
      <artifactId>h2</artifactId>
      <version>1.4.191</version>
   </dependency>
</dependencies>
</plugin>
```

Error
```
java.lang.NullPointerException
	at com.querydsl.sql.codegen.ExtendedBeanSerializer.bodyEnd(ExtendedBeanSerializer.java:50)
	at com.querydsl.codegen.BeanSerializer.serialize(BeanSerializer.java:181)
	at com.querydsl.sql.codegen.MetaDataExporter.write(MetaDataExporter.java:422)
	at com.querydsl.sql.codegen.MetaDataExporter.serialize(MetaDataExporter.java:400)
	at com.querydsl.sql.codegen.MetaDataExporter.handleTable(MetaDataExporter.java:380)
	at com.querydsl.sql.codegen.MetaDataExporter.handleTables(MetaDataExporter.java:256)
	at com.querydsl.sql.codegen.MetaDataExporter.export(MetaDataExporter.java:247)
	at com.querydsl.maven.AbstractMetaDataExportMojo.execute(AbstractMetaDataExportMojo.java:529)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	... 20 more
```

**Comment by Shredder121** [comment]
What querydsl version?
Could you make a reproduction project?

**Comment by tomforster** [comment]
Version is 4.0.9, I will create a test case against 4.1.0 tomorrow.

**Comment by tomforster** [comment]
Have fixed it by setting columnAnnotations to true in the maven configuration. I have submitted a pull request adding this information to the documentation as I think this is a little opaque.

**Comment by Shredder121** [comment]
Yeah, that's it.
I think it makes sense to add the note.
