### ISSUE TITLE
Use containsKey on an @ElementCollection Map field generate a bad query

### ISSUE THREAD

**Issue by vincentlejeune** [querydsl/querydsl#1897]
Hi,

I have an entity with a map inside to manage the internationalization part of the entity:

```
@Entity(name="Foo")
class Foo implements Identifiable<String> {

    @Id
    private String id;

    @ElementCollection
    private Map<Locale, I18n> i18n = new HashMap<>();

    protected Foo(){}

    public Foo(String id) {
        this.id = id;
    }

    @Override
    public String getId() {
        return id;
    }


    public Map<Locale, I18n> getI18n() {
        return this.i18n;
    }

    public void setI18n(Map<Locale, I18n> i18n) {
        this.i18n = i18n;
    }

    @Embeddable
    public static class I18n implements java.io.Serializable {

        private String description;

        private String label;

        @Column
        public String getDescription() {
            return this.description;
        }

        public I18n setDescription(String description) {
            this.description = description;
            return this;
        }

        @Column
        public String getLabel() {
            return label;
        }

        public I18n setLabel(String label) {
            this.label = label;
            return this;
        }
    }
}
```

When a use the query below :

`HibernateQuery<Foo> query= f.selectFrom(QFoo.foo).where(QFoo.foo.i18n.containsKey(Locale.FRENCH));`

I get the errors:

```
org.hibernate.HibernateException: SqlNode's text did not reference expected number of columns
    at org.hibernate.hql.internal.ast.tree.AbstractNullnessCheckNode.extractMutationTexts(AbstractNullnessCheckNode.java:151)
    at org.hibernate.hql.internal.ast.tree.AbstractNullnessCheckNode.mutateRowValueConstructorSyntax(AbstractNullnessCheckNode.java:85)
    at org.hibernate.hql.internal.ast.tree.AbstractNullnessCheckNode.initialize(AbstractNullnessCheckNode.java:55)
    at org.hibernate.hql.internal.ast.HqlSqlWalker.prepareLogicOperator(HqlSqlWalker.java:1301)
    at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.comparisonExpr(HqlSqlBaseWalker.java:4630)
    at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.logicalExpr(HqlSqlBaseWalker.java:2104)
    at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.whereClause(HqlSqlBaseWalker.java:796)
    at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.query(HqlSqlBaseWalker.java:597)
    at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.selectStatement(HqlSqlBaseWalker.java:301)
    at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.statement(HqlSqlBaseWalker.java:249)
    at org.hibernate.hql.internal.ast.QueryTranslatorImpl.analyze(QueryTranslatorImpl.java:278)
    at org.hibernate.hql.internal.ast.QueryTranslatorImpl.doCompile(QueryTranslatorImpl.java:206)
    at org.hibernate.hql.internal.ast.QueryTranslatorImpl.compile(QueryTranslatorImpl.java:158)
    at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:131)
    at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:93)
    at org.hibernate.engine.query.spi.QueryPlanCache.getHQLQueryPlan(QueryPlanCache.java:167)
    at org.hibernate.internal.AbstractSessionImpl.getHQLQueryPlan(AbstractSessionImpl.java:301)
    at org.hibernate.internal.AbstractSessionImpl.createQuery(AbstractSessionImpl.java:236)
    at org.hibernate.internal.SessionImpl.createQuery(SessionImpl.java:1800)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.hibernate.context.internal.ThreadLocalSessionContext$TransactionProtectionWrapper.invoke(ThreadLocalSessionContext.java:356)
    at com.sun.proxy.$Proxy13.createQuery(Unknown Source)
```

The generated query is 

```
select foo
from Foo foo
  left join foo.i18n as foo_i18n_2121399967 with key(foo_i18n_2121399967) = ?1
where foo_i18n_2121399967 is not null
```

If i remove the where condition it solve the issue.

> Querydsl version 4.0.2

**Comment by xzchaoo** [comment]
It seems that hibernate cannot well understand "where foo_i18n_2121399967 is not null", thus Embeddable object cannot fit into this query.
If you change your Embeddable I18n to a Scalar Value, it works.
You can write your own query instead of using querydsl in this situation.
