### ISSUE TITLE
db2 querydsl-maven-plugin export error

### ISSUE THREAD

**Issue by frankpolkm** [querydsl/querydsl#1928]
Hi, got the following exception. Any idea? 

```
Description Resource    Path    Location    Type
[jcc][10150][10300][4.15.82] Invalid parameter: Unknown column name TABLE_CAT. ERRORCODE=-4460, SQLSTATE=null (com.mysema.querydsl:querydsl-maven-plugin:3.7.3:export:default:generate-sources)

org.apache.maven.plugin.MojoExecutionException: [jcc][10150][10300][4.15.82] Invalid parameter: Unknown column name TABLE_CAT. ERRORCODE=-4460, SQLSTATE=null
    at com.mysema.query.maven.AbstractMetaDataExportMojo.execute(AbstractMetaDataExportMojo.java:442)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:331)
    at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1362)
    at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1)
    at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
    at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
    at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1360)
    at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:52)
    at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:137)
    at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:172)
    at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
    at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1$1.call(MavenBuilder.java:115)
    at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
    at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
    at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1.call(MavenBuilder.java:105)
    at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
    at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
    at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
    at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:86)
    at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:200)
    at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:205)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:245)
    at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:300)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
    at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:359)
    at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:382)
    at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
    at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: com.ibm.db2.jcc.am.SqlException: [jcc][10150][10300][4.15.82] Invalid parameter: Unknown column name TABLE_CAT. ERRORCODE=-4460, SQLSTATE=null
    at com.ibm.db2.jcc.am.fd.a(fd.java:680)
    at com.ibm.db2.jcc.am.fd.a(fd.java:60)
    at com.ibm.db2.jcc.am.fd.a(fd.java:103)
    at com.ibm.db2.jcc.am.gb.a(gb.java:2121)
    at com.ibm.db2.jcc.am.ResultSet.findColumnX(ResultSet.java:1932)
    at com.ibm.db2.jcc.am.ResultSet.getString(ResultSet.java:1704)
    at com.mysema.query.sql.codegen.MetaDataExporter.handleTable(MetaDataExporter.java:310)
    at com.mysema.query.sql.codegen.MetaDataExporter.export(MetaDataExporter.java:242)
    at com.mysema.query.maven.AbstractMetaDataExportMojo.execute(AbstractMetaDataExportMojo.java:433)
    ... 32 more
    pom.xml /test2  line 24 Maven Build Problem



```

**Comment by timowest** [comment]
Looks like the DB2 driver doesn't support the result sets for JDBC metadata properly.

**Comment by frankpolkm** [comment]
I'm using db2jcc4.jar, and already tried useJDBC4ColumnNameAndLabelSemantics=2 doesn't work. Do you have any working example for db2? Thanks.

**Comment by frankpolkm** [comment]
hi, any plan to fix this issue?

**Comment by Shredder121** [comment]
> Looks like **the DB2 driver doesn't support** the result sets for JDBC metadata **properly**.

@frankpolkm What is it that we should fix?
We rely on the driver supplying us with the data.

I think that raising this issue at the driver manufacturer is probably your best bet.
Maybe you can set up a minimal reproduction case, so we can look if it's really not anything we can fix.

Other than that there isn't much we can do I'm afraid.
