### ISSUE TITLE
SqlQuery to allow setting of null paramexpressions for select

### ISSUE THREAD

**Issue by haffar** [querydsl/querydsl#1943]
For update, we can set a path parameter to null:

		sqlQueryFactory.update(USAGE_GET)
		.setNull(USAGE_GET.foo);

However for select, there is no such method. For example:

                public static final Param<Array> v_foo = new Param<>(Array.class, "v_foo");
		StringTemplate strTemplate = Expressions.stringTemplate("UsageGet ( {0} )", v_foo);
		sqlQueryFactory.select(USAGE_GET)
				.from(strTemplate)
				.set(v_foo, aArray)
				.fetch();

Setting aArray to null causes an exception to be thrown, and there is no setNull() method.

**Comment by tan31989** [comment]
@haffar  Could you provide more insight on the terms used? USAGE_GET and also the Exception that you got?

**Comment by haffar** [comment]
@tan31989 USAGE_GET is an instance of QUsageGet, defined as:
	private static final QUsageGet USAGE_GET = QUsageGet.usageget;

QUsageGet is a class I created which defines all the columns being returned by the UsageGet stored procedure. It looks like this:

public class QUsageGet extends com.querydsl.sql.RelationalPathBase<Usage> {
	private static final long serialVersionUID = 393399721;
	public static final QUsageGet usageget = new QUsageGet("UsageGet");
	public final NumberPath<Integer> usercount = createNumber("usercount", Integer.class);
// more code
}

If I set the parameter v_foo to null, such as:
sqlQueryFactory.select(USAGE_GET)
            .from(strTemplate)
            .set(v_foo, null)
            .fetch();

This is the exception:
Caused by: java.lang.NullPointerException: null value in entry: {v_foo}=null
	at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:33) ~[guava-18.0.jar:?]
	at com.google.common.collect.SingletonImmutableBiMap.<init>(SingletonImmutableBiMap.java:39) ~[guava-18.0.jar:?]
	at com.google.common.collect.ImmutableBiMap.of(ImmutableBiMap.java:57) ~[guava-18.0.jar:?]
	at com.google.common.collect.ImmutableMap.of(ImmutableMap.java:80) ~[guava-18.0.jar:?]
	at com.querydsl.core.util.CollectionUtils.put(CollectionUtils.java:119) ~[querydsl-core-4.0.9.jar:?]
	at com.querydsl.core.DefaultQueryMetadata.setParam(DefaultQueryMetadata.java:331) ~[querydsl-core-4.0.9.jar:?]
	at com.querydsl.core.support.QueryMixin.set(QueryMixin.java:384) ~[querydsl-core-4.0.9.jar:?]
	at com.querydsl.core.support.QueryBase.set(QueryBase.java:176) ~[querydsl-core-4.0.9.jar:?]

**Comment by tan31989** [comment]
Just a confirmation @haffar are you using querydsl-sql?

This is due to the fact that, `set` uses, an `ImmutableMap` to save the key and its value to update.
Now, given the fact the `ImmutableMap` is from a library `com.google.common.collect`, they have a valid reason for not using `ImmutableMap` for setting a null value. 
In the first case (if I am right that you are using querydsl-sql), the `setNull` uses a normal java util `Map` to save the updates.

@timowest any reason for `setParam` in `DefaultQueryMetadata` (`querydsl-core`), points to `CollectionUtils` which uses the `ImmutableMap` to store the key value to set. I think, setParam could have used Map other than google's ImmutableMap, because it could be a set null in this case right?

**Comment by haffar** [comment]
@tan31989 yes I am using querydsl-sql

**Comment by Shredder121** [comment]
Mostly immutability reasons.
