### ISSUE TITLE
QueryDSL Collections join query does not work with Scala vars

### ISSUE THREAD

**Issue by bkempe** [querydsl/querydsl#1963]
When using standard Scala classes with `var`s (common for JPA usage) in a querydsl-collections join query, the following exception is thrown:

<details>
<summary>

`Exception in thread "main" com.mysema.codegen.CodegenException`</summary>

```
Exception in thread "main" com.mysema.codegen.CodegenException: Compilation of public class Q_02078139909_65821278_1275614662 {

    public static java.util.List<Object[]> eval(Iterable<Cat> cat1_) {
java.util.List<Object[]> rv = new java.util.ArrayList<Object[]>();
for (Cat cat1 : cat1_) {
for (Cat cat2 : com.querydsl.collections.CollQueryFunctions.<java.util.List>get(cat1, "kittens")) {
rv.add(new Object[]{cat1,cat2});
}
}
return rv;    }

}

 failed.
/Q_02078139909_65821278_1275614662.java:6: error: incompatible types: Object cannot be converted to Cat
for (Cat cat2 : com.querydsl.collections.CollQueryFunctions.<java.util.List>get(cat1, "kittens")) {
                                                                               ^
1 error

    at com.mysema.codegen.JDKEvaluatorFactory.compile(JDKEvaluatorFactory.java:74)
    at com.mysema.codegen.AbstractEvaluatorFactory.createEvaluator(AbstractEvaluatorFactory.java:128)
    at com.querydsl.collections.DefaultEvaluatorFactory.createEvaluator(DefaultEvaluatorFactory.java:262)
    at com.querydsl.collections.DefaultQueryEngine.evaluateMultipleSources(DefaultQueryEngine.java:109)
    at com.querydsl.collections.DefaultQueryEngine.list(DefaultQueryEngine.java:82)
    at com.querydsl.collections.AbstractCollQuery.fetch(AbstractCollQuery.java:182)
    at ScalaMain$.delayedEndpoint$ScalaMain$1(Main.scala:13)
    at ScalaMain$delayedInit$body.apply(Main.scala:7)
    at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
    at scala.App$$anonfun$main$1.apply(App.scala:76)
    at scala.App$$anonfun$main$1.apply(App.scala:76)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
    at scala.App$class.main(App.scala:76)
    at ScalaMain$.main(Main.scala:7)
    at ScalaMain.main(Main.scala)
```

</details>

<details>
<summary>

Code for `ScalaMain.scala`</summary>

 

``` scala
import java.util
import java.util.Collections

import com.querydsl.collections.CollQueryFactory
import com.querydsl.core.alias.Alias.{$, alias}

object ScalaMain extends App {
  val cc = alias(classOf[Cat], "cat1")
  val ck = alias(classOf[Cat], "cat2")
  CollQueryFactory
    .from($(cc), Collections.emptyList[Cat]())
    .innerJoin($(cc.kittens), $(ck))
    .fetch
}

class Cat {
  var kittens: util.List[Cat] = _
}
```

</details>

The reason is that [CollQuerySerializer#getAccessor](https://github.com/querydsl/querydsl/blob/master/querydsl-collections/src/main/java/com/querydsl/collections/CollQuerySerializer.java#L136) doesn't support Scala `var`s. `var` creates a private field and public accessor of the same name. Using Scala's `@BeanProperty` annotation on each field fixes the issue, but it would be nicer to have `getAccessor` also check for a method of the same name as the property.
I can provide a PR if that helps.

Unfortunately, the [field access by reflection](https://github.com/querydsl/querydsl/blob/master/querydsl-collections/src/main/java/com/querydsl/collections/CollQuerySerializer.java#L99) alternative currently doesn't work either (see exception), because the path type does not provide the correct collection type parameter.

**Comment by timowest** [comment]
Thanks for the bug report @bkempe. A PR would be most welcome.
