### ISSUE TITLE
null check for joined entity not working

### ISSUE THREAD

**Issue by Kernle32DLL** [querydsl/querydsl#1982]
Hi there,

we encountered a strange problem while performing null checks with QueryDSL 3.7.4. Boiled down to its simplest form, we build a query like this:

```Java
JPAQuery testQuery = new JPAQuery(em);
testQuery.from(QPerson.person);
testQuery.where(QPerson.person.radiationExposedPerson.isNotNull());
```

Which yields the following JPQL query:

```SQL
select person
from person person
where person.radiationExposedPerson is not null
```

The Java classes are (condensed) like this:

```Java
@Entity(name = "person")
public class Person {

...

@OneToOne(mappedBy= "person", optional = true)
private RadiationExposedPerson radiationExposedPerson;

...

}

@Entity(name = "radiationexposedperson")
public class RadiationExposedPerson  {

...

@OneToOne
private Person person;

...

}
```

radiationExposedPerson is a mapped attribute in Person, and can be null. RadiationExposedPerson "owns" the one-to-one association to a Person (this makes sense in our case - keep in mind that this is a condensed version for the problem at hand). We were however not able to verify if this impacts the issue.

The expected output of the query above would be to show all persons, in which the radiationExposedPerson is not null. However, this does not work, and returns **all elements**. When the same query is modified to a "isNull" check, an **empty result** is returned. We verified that our database contains persons where radiationExposedPerson is null, and others where it is set.

Another thing. If the null check is used as an expression for ordering, we run into an AST Exception from hibernate:

```Java
JPAQuery testQuery = new JPAQuery(em);
testQuery.from(QPerson.person);
testQuery.orderBy(new OrderSpecifier<>(Order.ASC, QPerson.person.radiationExposedPerson.isNotNull()));
```
```SQL
select person
from person person
order by person.radiationExposedPerson is not null asc
```
```
org.hibernate.hql.internal.ast.QuerySyntaxException: unexpected AST node: is not null [select person
from de.com.steep.radoclid2.model.entities.Person person
order by person.radiationExposedPerson is not null asc]
	at org.hibernate.hql.internal.ast.QuerySyntaxException.convert(QuerySyntaxException.java:91)
	at org.hibernate.hql.internal.ast.ErrorCounter.throwQueryException(ErrorCounter.java:109)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.analyze(QueryTranslatorImpl.java:284)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.doCompile(QueryTranslatorImpl.java:206)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.compile(QueryTranslatorImpl.java:158)
	at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:131)
	at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:93)
	at org.hibernate.engine.query.spi.QueryPlanCache.getHQLQueryPlan(QueryPlanCache.java:167)
	at org.hibernate.internal.AbstractSessionImpl.getHQLQueryPlan(AbstractSessionImpl.java:301)
	at org.hibernate.internal.AbstractSessionImpl.createQuery(AbstractSessionImpl.java:236)
	at org.hibernate.internal.SessionImpl.createQuery(SessionImpl.java:1836)
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.createQuery(AbstractEntityManagerImpl.java:328)
	at sun.reflect.GeneratedMethodAccessor100.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.orm.jpa.ExtendedEntityManagerCreator$ExtendedEntityManagerInvocationHandler.invoke(ExtendedEntityManagerCreator.java:344)
	at com.sun.proxy.$Proxy144.createQuery(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor100.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:294)
	at com.sun.proxy.$Proxy144.createQuery(Unknown Source)
	at com.mysema.query.jpa.impl.AbstractJPAQuery.createQuery(AbstractJPAQuery.java:129)
	at com.mysema.query.jpa.impl.AbstractJPAQuery.createQuery(AbstractJPAQuery.java:96)
	at com.mysema.query.jpa.impl.AbstractJPAQuery.list(AbstractJPAQuery.java:248)
	at de.com.steep.radoclid2.application.ui.web.mvc.controller.IndexController.index(IndexController.java:105)
	at de.com.steep.radoclid2.application.ui.web.mvc.controller.IndexController$$FastClassBySpringCGLIB$$76d43e53.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.interceptor.AbstractTraceInterceptor.invoke(AbstractTraceInterceptor.java:115)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
	at de.com.steep.radoclid2.application.ui.web.mvc.controller.IndexController$$EnhancerBySpringCGLIB$$bd210a5b.index(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:817)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:731)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:968)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:859)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:844)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration$ApplicationContextHeaderFilter.doFilterInternal(EndpointWebMvcAutoConfiguration.java:237)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at de.com.steep.radoclid2.application.filter.HeaderManipulationFilter.doFilter(HeaderManipulationFilter.java:58)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:112)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:316)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:122)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:169)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:48)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:205)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:120)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:53)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at de.com.steep.radoclid2.application.filter.HeaderManipulationFilter.doFilter(HeaderManipulationFilter.java:58)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:213)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:176)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:103)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:614)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

```

I gonna admit, this looks like valid JPQL, but I'm no expert here. If this is indeed correct, I might need to investigate the hibernate side of things.

**Comment by Kernle32DLL** [comment]
Confirmed same result with 4.1.3.

**Comment by timowest** [comment]
I believe the first issue is caused by Hibernate, maybe the OneToOne can't be properly handled. At least ManyToOne works well, see the attached PR.

**Comment by Kernle32DLL** [comment]
We might hack this via ManyToOne - results will follow. Thanks for the heads up.

I really hope this is not an hibernate issue. We are using hibernate 4.3 and unable to update to 5.X atm. So I'm unable to verify if this might be resolved in a later hibernate version. Will keep you posted.

**Comment by Kernle32DLL** [comment]
I found whats causing the issue. At least for the first issue with the where part. QueryDSL generates incorrect JPQL for this case.

Since the radiationExposedPerson field in the Person entity is a mapped field, a simple null check is not sufficient. The foreign entity must be joined, and this join must be null / not null checked. The following JPQL yields the correct result:

```SQL
select person
from person person
left join person.radiationExposedPerson as person_radiationExposedPerson
where person_radiationExposedPerson is null
```

The second issue (with order by) is not resolved so easily. When using "order by person_radiationExposedPerson is null asc", I still get an AST node exception (a different one however).

**Comment by timowest** [comment]
The following two queries are quite different

```
select person
from person person
where person.radiationExposedPerson is not null

select person
from person person
left join person.radiationExposedPerson as person_radiationExposedPerson
where person_radiationExposedPerson is null
```

Both can be expressed using Querydsl.

**Comment by Kernle32DLL** [comment]
Why are they different? I'm no JPQL expert, so I would presume them to give the same result.

Nevertheless, what would be the code for generating the second query? I would presume the code from the initial post to be correct?

```Java
JPAQuery testQuery = new JPAQuery(em);
testQuery.from(QPerson.person);
testQuery.where(QPerson.person.radiationExposedPerson.isNotNull());
```

**Comment by timowest** [comment]
The first one has an implict inner join to person.readiationExposedPerson and the where condition changes from is not null to is null.

The second query can be expressed as
```
JPAQuery testQuery = new JPAQuery(em);
testQuery.from(QPerson.person);
testQuery.leftJoin(person.radiationExposedPerson, radiationExposedPerson);
testQuery.where(radiationExposedPerson.isNull());
```

**Comment by Kernle32DLL** [comment]
Ah... sorry for mixing up null and notNull. Its not really important if a null or not null check is done, since this is toggable via the ui. I mixed them up, since as stated in the initial post, they both produced (imo) wrong results.

Still - i don't think ...

```Java
testQuery.where(QPerson.person.radiationExposedPerson.isNotNull());
```

... should result in an inner join. In which scenario does this make sense? Are there any tests to this statement?

**Comment by Kernle32DLL** [comment]
Investigating further, I have the feeling the resolves around the mapping.

```Java
@OneToOne(mappedBy= "person", optional = true)
private RadiationExposedPerson radiationExposedPerson;
```

The OneToOne Mapping is optional. This is why an inner join does not make sense at this point (because it excludes all entries which don't have an RadiationExposedPerson). So null-checking is useless here - this only makes sense with an left join. And as such, I wouldn't expect the need to join manually (furthermore - in our case it is not possible, because we build our filter expressions without an concrete JPAQuery to join against).

**Comment by timowest** [comment]
Querydsl preserves long property paths (e.g. QPerson.person.radiationExposedPerson) in the serialization, JPA engines map these then into inner joins.

**Comment by timowest** [comment]
order by is null expressions is unfortunately not supported in the JPA spec, it seems that some Hibernate versions support it though.

**Comment by Kernle32DLL** [comment]
Could you give a source as reference? I think this is quite interesting to know, since this behavior is not expected.

**Comment by Kernle32DLL** [comment]
This issue can be closed. The correct answer was so obvious that we didn't see it.

Instead of checking against the entity itself, checking against the joined entities primary key did the trick:

```Java
testQuery.where(QPerson.person.radiationExposedPerson.id.isNotNull());
```

Sorry for bothering this on the issue tracker, next time this will go to SO first.

**Comment by Shredder121** [comment]
Oh, good to hear that you have it resolved.

**Comment by spyro2000** [comment]
Had the same problem where a join-fetched sub-entity was always 'not null' even if it clearly was data-wise. When I changed the path to the ID of the sub-entity instead, it worked like expected...
