### ISSUE TITLE
JPA @Table without table name: StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by cdalexndr** [querydsl/querydsl#2109]
@Table may be used only do declare a unique constraint, ex:
`@Table(uniqueConstraints = @UniqueConstraint(columnNames = {"shop_id", "url"}))`
In this condition, `NativeSQLSerializer.handleJoinTarget(JoinExpression)` doesn't check if name is present, and  results in StringIndexOutOfBoundsException.

Call Stack:
```
java.lang.StringIndexOutOfBoundsException: String index out of range: 0

	at java.lang.String.charAt(String.java:658)
	at com.querydsl.sql.SQLTemplates.requiresQuotes(SQLTemplates.java:823)
	at com.querydsl.sql.SQLTemplates.quoteIdentifier(SQLTemplates.java:813)
	at com.querydsl.sql.SQLSerializer.appendTableName(SQLSerializer.java:108)
	at com.querydsl.jpa.NativeSQLSerializer.handleJoinTarget(NativeSQLSerializer.java:83)
	at com.querydsl.sql.SQLSerializer.serializeSources(SQLSerializer.java:656)
	at com.querydsl.sql.SQLSerializer.serializeForQuery(SQLSerializer.java:348)
	at com.querydsl.sql.SQLTemplates.serialize(SQLTemplates.java:844)
	at com.querydsl.sql.SQLSerializer.serialize(SQLSerializer.java:221)
	at com.querydsl.jpa.NativeSQLSerializer.serialize(NativeSQLSerializer.java:181)
	at com.querydsl.sql.ProjectableSQLQuery.serialize(ProjectableSQLQuery.java:490)
	at com.querydsl.jpa.sql.AbstractJPASQLQuery.createQuery(AbstractJPASQLQuery.java:98)
	at com.querydsl.jpa.sql.AbstractJPASQLQuery.createQuery(AbstractJPASQLQuery.java:94)
	at com.querydsl.jpa.sql.AbstractJPASQLQuery.fetchOne(AbstractJPASQLQuery.java:296)
```

**Comment by cdalexndr** [comment]
Using QueryDSL version 4.1.4

**Comment by MitchelNijdam-Rockstars** [comment]
3 years and still present in version 4.3.1 when using `@Table` without a `name` parameter

```
java.lang.StringIndexOutOfBoundsException: String index out of range: 0

	at java.lang.String.charAt(String.java:658)
	at com.querydsl.sql.SQLTemplates.requiresQuotes(SQLTemplates.java:823)
	at com.querydsl.sql.SQLTemplates.quoteIdentifier(SQLTemplates.java:813)
	at com.querydsl.sql.SQLSerializer.appendTableName(SQLSerializer.java:108)
	at com.querydsl.jpa.NativeSQLSerializer.handleJoinTarget(NativeSQLSerializer.java:83)
	at com.querydsl.sql.SQLSerializer.serializeSources(SQLSerializer.java:656)
	at com.querydsl.sql.SQLSerializer.serializeForQuery(SQLSerializer.java:348)
	at com.querydsl.sql.SQLTemplates.serialize(SQLTemplates.java:844)
	at com.querydsl.sql.SQLSerializer.serialize(SQLSerializer.java:221)
	at com.querydsl.jpa.NativeSQLSerializer.serialize(NativeSQLSerializer.java:181)
	at com.querydsl.sql.ProjectableSQLQuery.serialize(ProjectableSQLQuery.java:490)
	at com.querydsl.jpa.sql.AbstractJPASQLQuery.createQuery(AbstractJPASQLQuery.java:98)
	at com.querydsl.jpa.sql.AbstractJPASQLQuery.createQuery(AbstractJPASQLQuery.java:94)
	at com.querydsl.jpa.sql.AbstractJPASQLQuery.fetchOne(AbstractJPASQLQuery.java:296)
```

**Comment by cdalexndr** [comment]
querydsl died in the meantime and was recently ressurected... I've moved to JOOQ.
