### ISSUE TITLE
Symmetricity contract broken for equals for some Expression types

### ISSUE THREAD

**Issue by catharsis** [querydsl/querydsl#2229]
While writing a test case for some predicate building code, I ran into this issue:

```
import com.querydsl.core.types.Ops;
import com.querydsl.core.types.dsl.BooleanExpression;
import com.querydsl.core.types.dsl.Expressions;
import org.junit.Assert;
import org.junit.Test;

public class QuerydslEqualsTest {
  @Test
  public void testQuerydslEqualsSymmetricity() {
    BooleanExpression x = Expressions.predicate(Ops.EQ, Expressions.constant(42), Expressions.constant(42));
    BooleanExpression y = Expressions.predicate(Ops.EQ, Expressions.constant(42), Expressions.asNumber(Integer.parseInt("42")));
    Assert.assertEquals(x, y);
    Assert.assertEquals(y, x);
  }
}
```

This test fails the second assertion (but not the first!):
```

java.lang.AssertionError: expected: com.querydsl.core.types.dsl.BooleanOperation<42 = 42> but was: com.querydsl.core.types.dsl.BooleanOperation<42 = 42>
Expected :com.querydsl.core.types.dsl.BooleanOperation<42 = 42> 
Actual   :com.querydsl.core.types.dsl.BooleanOperation<42 = 42>

	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at QuerydslEqualsTest.testQuerydslEqualsSymmetricity(QuerydslEqualsTest.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


Process finished with exit code 255
```

Of course, this makes `equals()` asymmetric for some Expression types, which it should not be:

```
...
The equals method implements an equivalence relation on non-null object references: 
[...]
It is symmetric: for any non-null reference values x and y, x.equals(y) should return true if and only if y.equals(x) returns true. 
[...]
```
https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html#equals-java.lang.Object-

I haven't dug very deep into this, so I'm not sure what types exhibit this behavior - maybe it just affects `ConstantImpl`?

querydsl version: 4.1.4

**Comment by catharsis** [comment]
This is probably a more illustrative test case:

```
    @Test
    public void equalityIsSymmetric() {
        Expression<Integer> x = Expressions.constant(42);
        Expression<Integer> y = Expressions.asNumber(42);
        assertEquals(x.equals(y), y.equals(x));
    }
```
This fails like so:
```

java.lang.AssertionError: 
Expected :false
Actual   :true
 <Click to see difference>


	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.querydsl.core.types.dsl.BooleanExpressionTest.equalityIsSymmetric(BooleanExpressionTest.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


Process finished with exit code 255
```

**Comment by catharsis** [comment]
I'm unsure whether this is a terrible idea or not, but the following patch resolves this particular issue at least:

```
diff --git a/querydsl-core/src/main/java/com/querydsl/core/types/ConstantImpl.java b/querydsl-core/src/main/java/com/querydsl/core/types/ConstantImpl.java
index 2157ac187..4013bc63d 100644
--- a/querydsl-core/src/main/java/com/querydsl/core/types/ConstantImpl.java
+++ b/querydsl-core/src/main/java/com/querydsl/core/types/ConstantImpl.java
@@ -13,6 +13,7 @@
  */
 package com.querydsl.core.types;
 
+import com.querydsl.core.types.dsl.DslExpression;
 import javax.annotation.concurrent.Immutable;
 
 /**
@@ -146,6 +147,8 @@ public final class ConstantImpl<T> extends ExpressionBase<T> implements Constant
             return true;
         } else if (o instanceof Constant<?>) {
             return ((Constant<?>) o).getConstant().equals(constant);
+        } else if (o instanceof DslExpression<?>) {
+            return o.equals(this);
         } else {
             return false;
         }
```

**Comment by reegnz** [comment]
Just a hint about what problems you face here (effective java chapter 3):
https://www.slideshare.net/ibrahimkurce/effective-java-chapter-3-methods-common-to-all-objects
> There is no way to extend an instantiable class and add a value component while preserving the equals contract unless you are willing to forego the benefits of object-oriented abstraction.

Workaround is to follow composition over inheritance.

The root cause is the inheritance of ExpressionBase and that inheritance is what's messing up the entire equals contract.
