### ISSUE TITLE
QueryDslPredicateExecutor generates error constantly!!!

### ISSUE THREAD

**Issue by jess-park** [querydsl/querydsl#2272]
**I just add implementation from QueryDslPredicateExecutor with JpaRepository.
But the error is generated.**

please, give me the way to deal with this problem. the code worked very well before i put "QueryDslPredicateExecutor" in my repository with JpaRepository. 
Is there any possibility to "QueryDslPredicateExecutor" conflict with "JpaRepository"????
I ve already search so many information at the google. but I coundln't find any information about it.
So i post this issues attached with A.entity, B. service, C.repository and D.error log.
my development enviroument is "java8" and "query dsl 4.1.3".
Thanks anyway

**A. entity**
@Data
@Setter(AccessLevel.PRIVATE)
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name="MX_GROUP")
public class Group {
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "group_sq", nullable = false, unique = true, updatable = false)
	private Long groupSeq;
	
	@Column(name = "p_group_sq", nullable = true, unique = false, updatable = true)
	private Long pGroupSeq;
	
	@Embedded
	GroupInfo groupInfo;
	
	@ElementCollection(fetch = FetchType.EAGER)
	@CollectionTable(name = "MX_MANAGE_GROUP_ASSIGN", joinColumns = @JoinColumn(name = "group_sq"))
	@Column(name = "user_sq")
	private List<Long> manageMemberList = new ArrayList<Long>();
	
	@ElementCollection
	@CollectionTable(name = "MX_USER", joinColumns = @JoinColumn(name = "group_sq"))
	@Column(name = "user_sq")
	private List<Long> memberList = new ArrayList<Long>();
	
	public Group(Long groupSeq) {
		super();
		this.groupSeq = groupSeq;
	}
	
	public Group(Long pGroupSeq, GroupInfo groupInfo) {
		super();
		this.pGroupSeq = pGroupSeq;
		this.groupInfo = groupInfo;
	}
	
	public void changeGroupInfo(GroupInfo groupInfo) {
		this.groupInfo = groupInfo;
	}

	public void changeManageMemberList(List<Long> manageMemberList) {	
		this.manageMemberList = manageMemberList;
	}
	
	public void changeMemberList(List<Long> memberList) {	
		this.memberList = memberList;
	}

	public void changePGroupSeq(Long pGroupSeq) {
		this.pGroupSeq = pGroupSeq;
	}

}

**B. sevice**
in service, there is no logic about querydsl. The only thing i did is just add querydsl implemetation at the repository which is operated very well.

**C. repository**

**public interface GroupRepository extends JpaRepository<Group, Long>, QueryDslPredicateExecutor<Group>**
(i dont' know why "<<G.r.o.u.p.>>" has been disappeared at the last of interface. There is a "<<.G.r.o.u.p>>")

**D. error**
2018-03-16 21:52:18 [ERROR] [SpringApplication.java]reportFailure(771) : Application startup failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'groupService': Unsatisfied dependency expressed through field 'getCurrentUserService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'getCurrentUserService': Unsatisfied dependency expressed through field 'userRepository'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userRepository': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Failed to create query method public abstract java.lang.Iterable org.springframework.data.querydsl.QueryDslPredicateExecutor.findAll(com.querydsl.core.types.OrderSpecifier[])! No property findAll found for type User!
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:588)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
	at com.sds.maxigent.ResourceServerApplication.main(ResourceServerApplication.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'getCurrentUserService': Unsatisfied dependency expressed through field 'userRepository'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userRepository': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Failed to create query method public abstract java.lang.Iterable org.springframework.data.querydsl.QueryDslPredicateExecutor.findAll(com.querydsl.core.types.OrderSpecifier[])! No property findAll found for type User!
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:588)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:585)
	... 24 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userRepository': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Failed to create query method public abstract java.lang.Iterable org.springframework.data.querydsl.QueryDslPredicateExecutor.findAll(com.querydsl.core.types.OrderSpecifier[])! No property findAll found for type User!
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1628)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:585)
	... 37 common frames omitted
Caused by: java.lang.IllegalArgumentException: Failed to create query method public abstract java.lang.Iterable org.springframework.data.querydsl.QueryDslPredicateExecutor.findAll(com.querydsl.core.types.OrderSpecifier[])! No property findAll found for type User!
	at org.springframework.data.jpa.repository.query.PartTreeJpaQuery.<init>(PartTreeJpaQuery.java:76)
	at org.springframework.data.jpa.repository.query.JpaQueryLookupStrategy$CreateQueryLookupStrategy.resolveQuery(JpaQueryLookupStrategy.java:101)
	at org.springframework.data.jpa.repository.query.JpaQueryLookupStrategy$CreateIfNotFoundQueryLookupStrategy.resolveQuery(JpaQueryLookupStrategy.java:207)
	at org.springframework.data.jpa.repository.query.JpaQueryLookupStrategy$AbstractQueryLookupStrategy.resolveQuery(JpaQueryLookupStrategy.java:77)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.<init>(RepositoryFactorySupport.java:451)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:224)
	at org.springframework.data.envers.repository.support.EnversRevisionRepositoryFactoryBean$RevisionRepositoryFactory.getRepository(EnversRevisionRepositoryFactoryBean.java:140)
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.initAndReturn(RepositoryFactoryBeanSupport.java:277)
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:263)
	at org.springframework.data.jpa.repository.support.JpaRepositoryFactoryBean.afterPropertiesSet(JpaRepositoryFactoryBean.java:101)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624)
	... 47 common frames omitted
Caused by: org.springframework.data.mapping.PropertyReferenceException: No property findAll found for type User!
	at org.springframework.data.mapping.PropertyPath.<init>(PropertyPath.java:77)
	at org.springframework.data.mapping.PropertyPath.create(PropertyPath.java:329)
	at org.springframework.data.mapping.PropertyPath.create(PropertyPath.java:309)
	at org.springframework.data.mapping.PropertyPath.from(PropertyPath.java:272)
	at org.springframework.data.mapping.PropertyPath.from(PropertyPath.java:243)
	at org.springframework.data.repository.query.parser.Part.<init>(Part.java:76)
	at org.springframework.data.repository.query.parser.PartTree$OrPart.<init>(PartTree.java:247)
	at org.springframework.data.repository.query.parser.PartTree$Predicate.buildTree(PartTree.java:398)
	at org.springframework.data.repository.query.parser.PartTree$Predicate.<init>(PartTree.java:378)
	at org.springframework.data.repository.query.parser.PartTree.<init>(PartTree.java:86)
	at org.springframework.data.jpa.repository.query.PartTreeJpaQuery.<init>(PartTreeJpaQuery.java:70)
	... 58 common frames omitted

**Comment by Shredder121** [comment]
Could you report this to spring data?
Not quite sure how to fix this.
(Sent from phone)

**Comment by thackel** [comment]
Pretty sure this is no Spring Data or QueryDsl Bug.

The exception clear states:

> No property findAll found for type User!

So fix your `UserRepository`.

**Comment by jess-park** [comment]
Actually, "findAll" is abstract function. not property. The thing is that spring consider "findAll" which doesn't make sense

**Comment by thackel** [comment]
It makes sense, its the "Query Derivation" where Spring Data tries to create a Query from the method name.
User Custom Repositories to implement own extended queries by yourself.

**Comment by aprilfish** [comment]
I was using spring-data-jpa-extra,so i added 
```
@EnableJpaRepositories(repositoryFactoryBeanClass = GenericJpaRepositoryFactoryBean.class)
```
when I remove that,QueryDSL works fine.
