### ISSUE TITLE
Lamda search in Map<K,V> generates wrong JPQL

### ISSUE THREAD

**Issue by ptahchiev** [querydsl/querydsl#2304]
Hello,
I'm using querydsl-4.1.4 and here's my setup:

````
@Entity(name = Product.NAME)
public class Product {

    public static final String NAME = "product";

    @Id
    private Long id;

    @OrderColumn(name = Category.NAME + "_order")
    @ManyToMany(targetEntity = Category.class)
    @JoinTable(name = Category.NAME + "_" + NAME + "_entries", joinColumns = @JoinColumn(name = NAME + "_id"), inverseJoinColumns = @JoinColumn(name =
                    Category.NAME + "_id"), indexes = {
                    @Index(name = "idx_" + Category.NAME + "_" + NAME, columnList = NAME + "_id") }, foreignKey = @ForeignKey(name = "fk_" + Category.NAME + "_"
                    + NAME + "_entries" + "_" + NAME), inverseForeignKey = @ForeignKey(name = "fk_" + Category.NAME + "_" + NAME + "_entries" + "_"
                    + Category.NAME))
    private List<Category> categories;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public List<Category> getCategories() {
        return categories;
    }

    public void setCategories(List<Category> categories) {
        this.categories = categories;
    }
}
````

and `Category`:
````
@Entity(name = Category.NAME)
public class Category {

    public static final String NAME = "category";

    @Id
    private Long id;

    @ElementCollection(targetClass = LocalizedValue.class)
    @CollectionTable(name = NAME + "_name_lv", joinColumns = @JoinColumn(name = NAME + "_id"), indexes = {
                    @Index(name = "idx_" + NAME + "_name_lv", columnList = NAME + "_id") }, foreignKey = @ForeignKey(name = "fk_" + NAME + "_name_lv"))
    @MapKeyColumn(name = "locale")
    private Map<String, LocalizedValue> name;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Map<String, LocalizedValue> getName() {
        return name;
    }

    public void setName(Map<String, LocalizedValue> name) {
        this.name = name;
    }
}
````
Now I'm trying to execute this query:
```
        QCategory any = QProduct.product.categories.any();
        BooleanExpression expected = any.name.get("en").value.eq("test");
```
which results in this JPQL query:
`````
select productEntity from product productEntity 
                left join productEntity.categories as productEntity_categories  
                left join any(productEntity_categories) as productEntity_categories  // LEFT JOIN ANY() ???
                left join productEntity_categories.name as productEntity_categories_name_0 with key(productEntity_categories_name_0) = ?1 
               where productEntity_categories_name_0.value = ?2
`````

and apparently Hibernate does not think it's a valid JPQL:
````
Caused by: org.hibernate.hql.internal.ast.QuerySyntaxException: unexpected token: any near line 4, column 13 [select productEntity
from product productEntity
  left join productEntity.categories as productEntity_categories
  left join any(productEntity_categories) as productEntity_categories
  left join productEntity_categories.name as productEntity_categories_name_0 with key(productEntity_categories_name_0) = ?1
where productEntity_categories_name_0.value = ?2]
	at org.hibernate.hql.internal.ast.QuerySyntaxException.convert(QuerySyntaxException.java:74)
	at org.hibernate.hql.internal.ast.ErrorCounter.throwQueryException(ErrorCounter.java:91)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.parse(QueryTranslatorImpl.java:291)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.doCompile(QueryTranslatorImpl.java:186)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.compile(QueryTranslatorImpl.java:141)

````

I am not an expert but is `left join any(` a valid syntax?

**Comment by jwgmeligmeyling** [comment]
`left join any(` is not valid syntax. What did the query builder look like?
