### ISSUE TITLE
Query Projection do not group all the children under same parent id when used with order by parent name

### ISSUE THREAD

**Issue by shrds** [querydsl/querydsl#2331]
I have below query to read a list of objects containing parent child relationship

```
 OrderSpecifier<String> orderBy;
    if (SortOrder.ASC.equals(order)) {
      orderBy = definition.id.upper().asc();
    } else {
      orderBy = definition.id.upper().desc();
    }

newQuery().distinct().from(definition)
        .where(definition.clientId.in(clientId))
        .where(definition.id.in(ids))
        .orderBy(orderBy)
       .leftJoin(definition.aliases, alias)
        .transform(
            groupBy(definition.id).list(
                Projections.fields(
                    GroupDefinitionEntity.class,
                    definition.id,
                    definition.clientId,
                    definition.name,
                    definition.groupType,
                    definition.mnemonic,
                    definition.opaqueId,
                    list(Projections.fields(
                        AliasEntity.class,
                        alias.clientId,
                        alias.aliasId,
                        alias.aliasType,
                        alias.assigningAuthority,
                        alias.source).skipNulls())
                        .as(definition.aliases),
                    definition.createdDtTm,
                    definition.updatedDtTm)
                    .skipNulls()));
```

##### though when I execute this it doesn't group all the children together and I get 2 objects with the same parent id

```
{
      "id": "958f-ba7f8897b890",
      "client_id": "9346-666d6ff39329",
      "name": " 00Testgrouppleaseignore-1",
      "group_type": "MULTIVALUED",
      "mnemonic": "UNKNOWN",
      "members": [],
      "aliases": [
        {
          "alias_id": "3214345",
          "assigning_authority": "9346-666d6ff39329",
          "source_type": "43db-b2ae-361aba8da88f",
          "alias_type": "EXTERNAL"
        },
        {
          "alias_id": "543114",
          "assigning_authority": "9346-666d6ff39329",
          "source_type": "43db-b2ae-361aba8da88f",
          "alias_type": "EXTERNAL"
        },
        {
          "alias_id": "98765431148",
          "assigning_authority": "9346-666d6ff39329",
          "source_type": "43db-b2ae-361aba8da88f",
          "alias_type": "EXTERNAL"
        },
        {
          "alias_id": "9876543114123",
          "assigning_authority": "9346-666d6ff39329",
          "source_type": "43db-b2ae-361aba8da88f",
          "alias_type": "EXTERNAL"
        }
      ],
      "tags": [],
      "created_at": "2018-06-28T21:15:17Z",
      "updated_at": "2018-06-28T21:15:17Z"
    }
```

### and 
```
{
      "id": "18420125-3f71-44f8-958f-ba7f8897b890",
      "client_id": "9346-666d6ff39329",
      "name": " 00Testgrouppleaseignore-1",
      "group_type": "MULTIVALUED",
      "mnemonic": "UNKNOWN",
      "members": [],
      "aliases": [
        {
          "alias_id": "9876543214",
          "assigning_authority": "451a-9346-666d6ff39329",
          "source_type": "43db-b2ae-361aba8da88f",
          "alias_type": "EXTERNAL"
        },
        {
          "alias_id": "98765432149",
          "assigning_authority": "9346-666d6ff39329",
          "source_type": "43db-b2ae-361aba8da88f",
          "alias_type": "EXTERNAL"
        }
      ],
      "tags": [],
      "created_at": "2018-06-28T21:15:17Z",
      "updated_at": "2018-06-28T21:15:17Z"
    }
```

I think the issue is with order by clause. I am ordering by on definition name which is a string. 
is this a known issue?

**Comment by gravitywp** [comment]
list(Projections.fields(
                        AliasEntity.class,
                        alias.clientId,
                        alias.aliasId,
                        alias.aliasType,
                        alias.assigningAuthority,
                        alias.source).skipNulls())
                        .as(definition.aliases),


what is "list" ?

**Comment by shrds** [comment]
@Shredder121 can you please take a look at this and suggest if I am missing anything. 
I dug more into it. I see the issue only when I am using Projections and transforming the resultset. If I create my query like below and fetch all the columns I don't see the similar issue. 

```
OrderSpecifier<String> orderBy;
    if (SortOrder.ASC.equals(order)) {
      orderBy = definition.name.upper().asc();
    } else {
      orderBy = definition.name.upper().desc();
    }

newQuery().distinct().from(definition)
        .where(definition.clientId.in(clientId))
        .where(definition.id.in(ids))
        .orderBy(orderBy).fetch();
```

**Comment by shrds** [comment]
Another finding the issue happens only when the field I am ordering by has duplicate values.

**Comment by shrds** [comment]
I would really appreciate anybody from QueryDSL team help me to resolve this issue.
As I mentioned when I use Projections with OrderBy clause and use a String field which may contain duplicate values I get unexpected results with children not being added to same parent group id where they belong and I get duplicate group of objects with parent ids.

 I changed the OrderBy to use Expression and used asString like below 

```
 OrderSpecifier<String> orderBy;
    
    if (SortOrder.ASC.equals(order)) {
      orderBy = Expressions.asString("name").asc();
    } else {
      orderBy = Expressions.asString("name").asc();
    }
```
Doing so doesn't even sort the resultset the way it should and I get non sorted resultset.

![screen shot 2018-07-02 at 1 37 44 pm](https://user-images.githubusercontent.com/10283896/42180561-5a0978fa-7dfd-11e8-888e-1ebe7f8e7a0e.png)


If you see the above image it puts name "Bbb Ddd" first even though I am sorting it ascending by name.

I tried to debug but I cant see how its fetching the result set and program flow directly goes to implementation of transform() in  [GroupByList.java](https://github.com/petrkotek/querydsl/blob/7258df0c10fcfeee7cea10c5113676445c02c9b4/querydsl-core/src/main/java/com/querydsl/core/group/GroupByList.java#L43)



CC:  
@Shredder121 
@timowest  
@johnktims 
@robertandrewbain

**Comment by shrds** [comment]
```

OrderSpecifier orderSpecifier;
    if (SortOrder.ASC.equals(order)) {
      orderSpecifier = Expressions.asString("name").asc();
    } else {
      orderSpecifier = Expressions.asString("name").asc();
    }

List<GroupDefinitionEntity> groupEntities = newQuery().distinct().from(definition)
        .where(definition.clientId.in(clientId))
        .where(definition.id.in(ids)).leftJoin(definition.aliases, alias)
        .orderBy(orderSpecifier)
        .transform(
            groupBy(definition.id).list(
                Projections.fields(
                    GroupDefinitionEntity.class,
                    definition.id,
                    definition.clientId,
                    definition.name,
                    definition.groupType,
                    definition.mnemonic,
                    definition.opaqueId,
                    list(Projections.fields(
                        AliasEntity.class,
                        alias.clientId,
                        alias.aliasId,
                        alias.aliasType,
                        alias.assigningAuthority,
                        alias.source).skipNulls())
                        .as(definition.aliases),
                    definition.createdDtTm,
                    definition.updatedDtTm)
                    .skipNulls()));
```

When I use Expressions to construct order by and use projection like above, I get below error:
```
Caused by: org.hsqldb.HsqlException: data type cast needed for parameter or null literal
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.ExpressionOrderBy.resolveTypes(Unknown Source)
	at org.hsqldb.QuerySpecification.resolveExpressionTypes(Unknown Source)
	at org.hsqldb.QuerySpecification.resolveTypesPartOne(Unknown Source)
	at org.hsqldb.QueryExpression.resolve(Unknown Source)
	at org.hsqldb.ParserDQL.compileCursorSpecification(Unknown Source)
	at org.hsqldb.ParserCommand.compilePart(Unknown Source)
	at org.hsqldb.ParserCommand.compileStatement(Unknown Source)
	at org.hsqldb.Session.compileStatement(Unknown Source)
	at org.hsqldb.StatementManager.compile(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 89 more
```
The hibernate query it generates
```select
	distinct groupdefin0_.id as col_0_0_,
	groupdefin0_.id as col_1_0_,
	groupdefin0_.client_id as col_2_0_,
	groupdefin0_.name as col_3_0_,
	groupdefin0_.group_type as col_4_0_,
	groupdefin0_.mnemonic as col_5_0_,
	groupdefin0_.opaque_id as col_6_0_,
	aliasentit2_.client_id as col_7_0_,
	aliasentit2_.alias_id as col_8_0_,
	aliasentit2_.alias_type as col_9_0_,
	aliasentit2_.assigning_authority as col_10_0_,
	aliasentit2_.source as col_11_0_,
	groupdefin0_.created_dt_tm as col_12_0_,
	groupdefin0_.updated_dt_tm as col_13_0_
from
	group_definitions groupdefin0_
left outer join group_definitions_aliases aliases1_ on
	groupdefin0_.opaque_id = aliases1_.GroupDefinitionEntity_opaque_id
left outer join aliases aliasentit2_ on
	aliases1_.aliases_opaque_id = aliasentit2_.opaque_id
where
	groupdefin0_.client_id =?
	and(
		groupdefin0_.id in(
			?,
			?,
			?,
			?,
			?
		)
	)
order by
	? asc
``` 

Its not generating the order by clause correctly.

**Comment by shrds** [comment]
https://github.com/querydsl/querydsl/blob/master/querydsl-core/src/main/java/com/querydsl/core/group/GroupByList.java#L58-L70

I feel this is a bug that its not maintaining the previously read IDs from the resultset and creating a new group while iterating over the list. 
```
final CloseableIterator<Tuple> iter = query.select(expr).iterate();

        List<V> list = Lists.newArrayList();
        GroupImpl group = null;
        K groupId = null;
        while (iter.hasNext()) {
            @SuppressWarnings("unchecked") //This type is mandated by the key type
            K[] row = (K[]) iter.next().toArray();
            if (group == null) {
                group = new GroupImpl(groupExpressions, maps);
                groupId = row[0];
            } else if (!Objects.equal(groupId, row[0])) {
                list.add(transform(group));
                group = new GroupImpl(groupExpressions, maps);
                groupId = row[0];
            }
            group.add(row);
        }
```

**Comment by shrds** [comment]
Update on this issue. 

I have verified by adding this unit test

add a DummyFetchableQuery to [AbstractGroupByTest.java](https://github.com/querydsl/querydsl/blob/master/querydsl-core/src/test/java/com/querydsl/core/group/AbstractGroupByTest.java)
```
  protected static final DummyFetchableQuery<Tuple> USERS_W_UNORDERED_ROWS = projectable(
        row(null, "null post", 7, "comment 7"),
        row(1, "post 1", 1, "comment 1"),
        row(1, "post 1", 2, "comment 2"),
        row(1, "post 1", 3, "comment 3"),
        row(null, "null post", 8, "comment 8"),
        row(2, "post 2", 4, "comment 4"),
        row(2, "post 2", 5, "comment 5"),
        row(3, "post 3", 6, "comment 6")
    );
```

Then add below to [GroupByListTest.java](https://github.com/querydsl/querydsl/blob/master/querydsl-core/src/test/java/com/querydsl/core/group/GroupByListTest.java)
```
@Test
    public void group_order_with_unordered_rows() {
        List<Group> results = USERS_W_UNORDERED_ROWS
            .transform(groupBy(postId).list(postName, set(commentId)));

        assertEquals(4, results.size());
    }
```

The test fails with below error 
```
java.lang.AssertionError: 
Expected :4
Actual   :5
 <Click to see difference>


	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.querydsl.core.group.GroupByListTest.group_order_with_unordered_rows(GroupByListTest.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


Process finished with exit code 255
```

There are two solutions to resolve the issue.
1. Ideal fix is to update the querydsl code to preserve the previously read row before creating a new Group object 
```
 @Override
    public List<V> transform(FetchableQuery<?,?> query) {
        // create groups
        FactoryExpression<Tuple> expr = FactoryExpressionUtils.wrap(Projections.tuple(expressions));
        boolean hasGroups = false;
        for (Expression<?> e : expr.getArgs()) {
            hasGroups |= e instanceof GroupExpression;
        }
        if (hasGroups) {
            expr = withoutGroupExpressions(expr);
        }
        final CloseableIterator<Tuple> iter = query.select(expr).iterate();

        List<V> list = Lists.newArrayList();
        List<K> previouslyReadIds = Lists.newArrayList();
        GroupImpl group = null;
        K groupId = null;
        while (iter.hasNext()) {
            @SuppressWarnings("unchecked") //This type is mandated by the key type
            K[] row = (K[]) iter.next().toArray();
            if (group == null) {
                group = new GroupImpl(groupExpressions, maps);
                groupId = row[0];
                previouslyReadIds.add(row[0]);
            } else if (!Objects.equal(groupId, row[0]) && !previouslyReadIds.contains(row[0])) {
                list.add(transform(group));
                group = new GroupImpl(groupExpressions, maps);
                groupId = row[0];
                previouslyReadIds.add(row[0]);
            }
            group.add(row);
        }
        if (group != null) {
            list.add(transform(group));
        }
        iter.close();
        return list;
    }
```
this fixes the tests. 
![screen shot 2018-07-05 at 9 29 48 am](https://user-images.githubusercontent.com/10283896/42329333-0e62b8f4-8036-11e8-8c33-c8ff6bf06555.png)



OR
2. Add another OrderBy in your query to order by ids with the field you are sorting the results.

```
OrderSpecifier<String> orderBy = null;
    boolean descending = order.equals(SortOrder.DESC);
    if (sort != null) {
      switch (sort) {
        case ID:
          orderBy = descending ? group.id.desc() : group.id.asc();
          break;
        case MNEMONIC:
          orderBy = descending ? group.mnemonic.desc() : group.mnemonic.asc();
          break;
        case NAME:
          orderBy = descending ? group.name.lower().desc() : group.name.lower().asc();
      }
    } else {
      orderBy = descending ? group.id.desc() : group.id.asc();
    }

List<GroupEntity> groupEntities = newQuery().distinct().from(group)
        .where(group.clientId.in(clientId))
        .where(group.id.in(ids))
        .orderBy(orderBy)
        .leftJoin(group.aliases, alias)
        .orderBy(group.id
            .asc()) //this is necessary to maintain the resultset order when its grouped by field other than id
        .transform(
            groupBy(group.id).list(
                Projections.fields(
                    GroupEntity.class,
                    group.id,
                    group.rawGroupId,
                    group.definitionGroupId,
                    group.groupViewId,
                    group.name,
                    group.clientId,
                    group.groupType,
                    group.mnemonic,
                    group.opaqueId,
                    group.groupTypeUniquenessId,
                    list(Projections.fields(
                        AliasEntity.class,
                        alias.clientId,
                        alias.aliasId,
                        alias.aliasType,
                        alias.assigningAuthority,
                        alias.source).skipNulls())
                        .as(group.aliases),
                    group.createdDtTm,
                    group.updatedDtTm)
                    .skipNulls()));
```

**Comment by jokefaker** [comment]
Same issue, @shrds will ```previouslyReadIds.contains(row[0])``` cause performance issue if the size is big

**Comment by jwgmeligmeyling** [comment]
This issue is supposedly fixed by https://github.com/querydsl/querydsl/pull/2330 (according to the author of this issue). That pull request is now merged.  Please reopen or file an new issue if the issue remains.
