### ISSUE TITLE
Datediff fails with querydsl jpa

### ISSUE THREAD

**Issue by khauser** [querydsl/querydsl#2400]
We are using querydsl-jpa-4.2.1 together with spring data (spring-data-jpa-2.0.9, spring-boot-2.0.4) on a H2 database.
All entity classes a transformed into these Q-files and now we are able to execute queries like:

```
    public TestSuite queryOneById(Long testSuiteId)
    {
        QTestSuite testSuite = QTestSuite.testSuite;
        QTestCase testCase = QTestCase.testCase;

        BooleanExpression equalTestPlanId = testSuite.id.eq(testSuiteId);
        return from(testSuite).distinct().where(equalTestPlanId).leftJoin(testSuite.testCases, testCase).fetchJoin()
                        .fetchOne();
    }
```

As always new requirements come in and something gets boken :(.

We need to calculate date difference on one of our objects. I somehow was coming to these lines:

```
    public List<Tuple> averageDurationMinutes(Collection<Long> testPlanIds, String environment)
    {
        QTestSuite testSuite = QTestSuite.testSuite;

        NumberOperation<Double> timeDiffExpr = Expressions.numberOperation(Double.class, Ops.DateTimeOps.DIFF_MINUTES,
                        testSuite.startDateTime, testSuite.endDateTime);

        return from(testSuite)
                        .select(testSuite.suiteName, timeDiffExpr).fetch();

    }
```
Which are failing with:

```
org.springframework.dao.InvalidDataAccessApiUsageException: org.hibernate.QueryException: No data type for node: org.hibernate.hql.internal.ast.tree.MethodNode 
 \-[METHOD_CALL] MethodNode: '('
    +-[METHOD_NAME] IdentNode: 'diff_minutes' {originalText=diff_minutes}
    \-[EXPR_LIST] SqlNode: 'exprList'
       +-[DOT] DotNode: 'testsuite0_.start_date_time' {propertyName=startDateTime,dereferenceType=PRIMITIVE,getPropertyPath=startDateTime,path=testSuite.startDateTime,tableAlias=testsuite0_,className=....execution.persistence.TestSuite,classAlias=testSuite}
       |  +-[ALIAS_REF] IdentNode: 'testsuite0_.id' {alias=testSuite, className=....execution.persistence.TestSuite, tableAlias=testsuite0_}
       |  \-[IDENT] IdentNode: 'startDateTime' {originalText=startDateTime}
       \-[DOT] DotNode: 'testsuite0_.end_date_time' {propertyName=endDateTime,dereferenceType=PRIMITIVE,getPropertyPath=endDateTime,path=testSuite.endDateTime,tableAlias=testsuite0_,className=....execution.persistence.TestSuite,classAlias=testSuite}
          +-[ALIAS_REF] IdentNode: 'testsuite0_.id' {alias=testSuite, className=....execution.persistence.TestSuite, tableAlias=testsuite0_}
          \-[IDENT] IdentNode: 'endDateTime' {originalText=endDateTime}
 [select testSuite.suiteName, diff_minutes(testSuite.startDateTime,testSuite.endDateTime)
from ....execution.persistence.TestSuite testSuite]; nested exception is java.lang.IllegalArgumentException: org.hibernate.QueryException: No data type for node: org.hibernate.hql.internal.ast.tree.MethodNode 
 \-[METHOD_CALL] MethodNode: '('
    +-[METHOD_NAME] IdentNode: 'diff_minutes' {originalText=diff_minutes}
    \-[EXPR_LIST] SqlNode: 'exprList'
       +-[DOT] DotNode: 'testsuite0_.start_date_time' {propertyName=startDateTime,dereferenceType=PRIMITIVE,getPropertyPath=startDateTime,path=testSuite.startDateTime,tableAlias=testsuite0_,className=....execution.persistence.TestSuite,classAlias=testSuite}
       |  +-[ALIAS_REF] IdentNode: 'testsuite0_.id' {alias=testSuite, className=....execution.persistence.TestSuite, tableAlias=testsuite0_}
       |  \-[IDENT] IdentNode: 'startDateTime' {originalText=startDateTime}
       \-[DOT] DotNode: 'testsuite0_.end_date_time' {propertyName=endDateTime,dereferenceType=PRIMITIVE,getPropertyPath=endDateTime,path=testSuite.endDateTime,tableAlias=testsuite0_,className=....execution.persistence.TestSuite,classAlias=testSuite}
          +-[ALIAS_REF] IdentNode: 'testsuite0_.id' {alias=testSuite, className=....execution.persistence.TestSuite, tableAlias=testsuite0_}
          \-[IDENT] IdentNode: 'endDateTime' {originalText=endDateTime}
 [select testSuite.suiteName, diff_minutes(testSuite.startDateTime,testSuite.endDateTime)
from ....execution.persistence.TestSuite testSuite]
	at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:367)
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:227)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:527)
	at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
	at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:153)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at ....execution.repository.TestSuiteRepositoryCustomImpl$$EnhancerBySpringCGLIB$$15b7407d.averageDurationMinutes(<generated>)
```

What is happening here?
I assume that normally diff_minutes will be transformed in the H2 Dialect datediff function.

 Or is there another approach to reach my goal?

Thanks
Karsten

**Comment by khauser** [comment]
I now use
`Expressions.booleanTemplate("datediff({0}, {1})", testSuite.startDateTime, testSuite.endDateTime)`

With a adjusted dialect it seems to work:
```
public class CustomH2Dialect extends H2Dialect
{
    public CustomH2Dialect() {
        super();
        //registerFunction( "datediff", new SQLFunctionTemplate( StandardBasicTypes.INTEGER, "datediff(interval, ?1, ?2)" ) );
        registerFunction("datediff", new SQLFunctionTemplate(StandardBasicTypes.LONG, "datediff('MINUTE', ?2, ?1)"));
    }
}
```
