### ISSUE TITLE
No value specified for parameter when inserting with templates

### ISSUE THREAD

**Issue by hylkevds** [querydsl/querydsl#2423]
Problem demo project here: https://github.com/hylkevds/QueryDslTests

```
QTesttable2 qt = QTesttable2.testtable2;
createQueryFactory().insert(qt)
    .set(qt.colstring, ExpressionUtils.template(String.class, "?::text", "Templated variable"))
    .set(qt.id, 1L)
    .execute();
```
Gives:
```
com.querydsl.core.QueryException: Caught PSQLException for insert into "testtable2" ("colstring", "id")
values (someFunction(?), ?)
	at com.querydsl.sql.DefaultSQLExceptionTranslator.translate(DefaultSQLExceptionTranslator.java:50)
	at com.querydsl.sql.Configuration.translate(Configuration.java:508)
	at com.querydsl.sql.dml.AbstractSQLInsertClause.execute(AbstractSQLInsertClause.java:436)
	at querydsl.SubstringTest.testInsert(SubstringTest.java:115)
...

Caused by: org.postgresql.util.PSQLException: No value specified for parameter 2.
	at org.postgresql.core.v3.SimpleParameterList.checkAllParametersSet(SimpleParameterList.java:257)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:292)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:120)
	at com.querydsl.sql.dml.AbstractSQLInsertClause.execute(AbstractSQLInsertClause.java:414)
	... 31 more
```
The generated query is correct, but the parameter value of the templated variable gets lost. Only the constant makes it to `AbstractSQLClause.setParameters()`.

Or is this the wrong way to go about calling functions or casts when inserting data?

**Comment by hylkevds** [comment]
Doh, the QueryDSL parameter placeholder is `{0}`, not `?`
