### ISSUE TITLE
More than one row returned by a subquery - PostgresSQL

### ISSUE THREAD

**Issue by adboy316** [querydsl/querydsl#2518]
I'm trying to run the following subquery using the com.querydsl.sql.SQLExpressions class:

```sql

.select(Expressions.stringTemplate("group_concat({0}, ' & ')", QSoilAmendment.soilAmendment.code))
            .from(QTreatmentSoilAmendment.treatmentSoilAmendment)
            .join(QSoilAmendment.soilAmendment).on(QTreatmentSoilAmendment.treatmentSoilAmendment.pk.soilAmendmentId.eq(QSoilAmendment.soilAmendment.soilAmendmentId))
            .where(QTreatmentSoilAmendment.treatmentSoilAmendment.pk.plantingTreatment.treatmentId.eq(QPlantingTreatment.plantingTreatment.treatmentId))
            .as(Expressions.stringPath("soilAmendment")), true),

```

But I am getting the following error:

```
Caused by: org.postgresql.util.PSQLException: ERROR: more than one row returned by a subquery used as an expression
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:150)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:113)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:60)
```

I understand that the subquery is trying to return more than one row, which is indeed what I want. This exact code has worked for me with MYSQL, but when I try it with a Postgres db I get the error above. 

Any ideas/suggestions?

**Comment by jwgmeligmeyling** [comment]
Please provide the generated SQL query. I suspect this is a Hibernate issue.
