### ISSUE TITLE
Problem grouping (post processing)

### ISSUE THREAD

**Issue by barbatchov** [querydsl/querydsl#2529]
Hello. I'm trying to fetch data grouping, and it gives me an error, . 

```java
package org.project.services;

import com.querydsl.jpa.sql.JPASQLQuery;
import java.util.Set;
import javax.persistence.PersistenceContext;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.project.sqlentities.dbo.QEtapa.Etapa;
import org.project.sqlentities.dbo.QFase.Fase;
import org.project.sqlentities.dbo.QOperacao.Operacao;
import org.project.sqlentities.dbo.QOperacaoUF.OperacaoUF;

@Service
public class TestQueruDSL {
    @PersistenceContext private EntityManager entityManager;
    @Autowired private SQLTemplates sqlTemplate;

    public JPASQLQuery<ResultDTO> fetch() {
        final JPASQLQuery<ResultDTO> query = new JPASQLQuery<>(entityManager,sqlTemplate);
        query
            .from(Operacao)
            .leftJoin(Fase).on(Operacao.idFase.eq(Fase.idFase))
            .leftJoin(Etapa).on(Operacao.idEtapa.eq(Etapa.idEtapa))
            .leftJoin(OperacaoUF).on(OperacaoUF.idOperacao.eq(Operacao.idOperacao))
            .transform(GroupBy.groupBy(Operacao.idOperacao).list(Projections.bean(
                ResultDTO.class,
                Operacao.idDadosGerais.as("id"),
                GroupBy.set(OperacaoUF.sigUf).as("stateList")
            )))
        ;
        return query;
    }
}

class ResultDTO {
    private Integer id;
    private Set<String> stateList;

    public void setId(final Integer id) { this.id = id; }
    public void setStateList(final Set<String> stateList) { this.stateList = stateList; }
    public Integer getId() { return id; }
    public Set<String> getStateList() { return stateList; }
}
```

In my test, it gives me an Tupple error. It is trying to convert an object array to Tupple then to array again in GroupByList.java:60 as follows:
```sql
Hibernate: select
    Operacao.IdOperacao,
    Operacao.IdDadosGerais as id,
    Operacao_UF.SigUf
from dbo.Operacao Operacao
left join dbo.Fase Fase on Operacao.IdFase = Fase.IdFase
left join dbo.Etapa Etapa on Operacao.IdEtapa = Etapa.IdEtapa
left join dbo.Operacao_UF Operacao_UF on Operacao_UF.IdOperacao = Operacao.IdOperacao
```

```log
java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to com.querydsl.core.Tuple

	at com.querydsl.core.group.GroupByList.transform(GroupByList.java:60)
	at com.querydsl.core.group.GroupByList.transform(GroupByList.java:36)
	at com.querydsl.core.support.FetchableQueryBase.transform(FetchableQueryBase.java:55)
	at org.project.services.TestQueruDSL.fetch(TestQueruDSL.java:24)
	at org.project.services.TestQueruDSL.fetch(TestQueruDSL.java:12)
	at org.project.services.TestQueruDSLTest.testarQuery(TestQueruDSLTest.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by windchopper** [comment]
bug still exists
