### ISSUE TITLE
Syntax error in SQL statement

### ISSUE THREAD

**Issue by marrhub** [querydsl/querydsl#2538]
Hi,
I got DB schema as on the ERD below:
![EVENT_NOTES](https://user-images.githubusercontent.com/18379923/75634277-90632100-5c0c-11ea-93cd-a2909221c083.png)
It's just relevant part of much bigger project which I can't share so please see the important bits below.

I try to translate following working (on H2) SQL query:

```sql
SELECT e.*, n.*, nd.* FROM EVENT e
LEFT JOIN EVENT_NOTES en ON e.ID = en.ENTITY_ID
LEFT JOIN NOTE n on en.NOTE_ID = n.ID
LEFT JOIN NOTE_DEFAULT nd ON n.ID = nd.ID
WHERE n.NOTE like '%work%'
OR nd.NOTE2 like '%work%';
```
to QueryDSL as follows:

```java
QueryResults<Event> results = from(QEvent.event)
    .leftJoin(QEvent.event.notes)
    .leftJoin(QNote.note1)
    .leftJoin(QDefaultNote.defaultNote)
    .where(
        QNote.note1.note.toLowerCase().contains(note)
        .or(QDefaultNote.defaultNote.note2.toLowerCase().contains(note))
    ).fetchResults();
```

but it fails with following runtime error:

```
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT COUNT(EVENT0_.ID) AS COL_0_0_ FROM EVENT EVENT0_ LEFT OUTER JOIN EVENT_NOTES NOTES1_ ON EVENT0_.ID=NOTES1_.ENTITY_ID LEFT OUTER JOIN NOTE NOTE2_ ON NOTES1_.NOTE_ID=NOTE2_.ID LEFT OUTER JOIN NOTE NOTE3_ ON LEFT OUTER[*] JOIN (NOTE_DEFAULT DEFAULTNOT4_ INNER JOIN NOTE DEFAULTNOT4_1_ ON DEFAULTNOT4_.ID=DEFAULTNOT4_1_.ID) ON WHERE LOWER(NOTE3_.NOTE) LIKE ? ESCAPE '!' OR LOWER(DEFAULTNOT4_.NOTE2) LIKE ? ESCAPE '!' "; SQL statement:
select count(event0_.id) as col_0_0_ from event event0_ left outer join event_notes notes1_ on event0_.id=notes1_.entity_id left outer join note note2_ on notes1_.note_id=note2_.id left outer join note note3_ on left outer join (note_default defaultnot4_ inner join note defaultnot4_1_ on defaultnot4_.id=defaultnot4_1_.id) on where lower(note3_.note) like ? escape '!' or lower(defaultnot4_.note2) like ? escape '!' [42000-197]
    at org.h2.message.DbException.getJdbcSQLException(DbException.java:357) ~[h2-1.4.197.jar:1.4.197]
```

I've narrowed down the QueryDSL query to following minimal working query:

```java
QueryResults<Event> results = from(QEvent.event)
    .leftJoin(QEvent.event.notes)
    .fetchResults();
```

which generates SQL:

```sql
select count(event0_.id) as col_0_0_
from event event0_
         left outer join event_notes notes1_ on event0_.id = notes1_.entity_id
         left outer join note note2_ on notes1_.note_id = note2_.id
```

and following minimal not working query:

```java
QueryResults<Event> results = from(QEvent.event)
    .leftJoin(QEvent.event.notes)
    .leftJoin(QNote.note1)
    .fetchResults();
```

failing with:
```
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement
"SELECT COUNT(EVENT0_.ID) AS COL_0_0_ FROM EVENT EVENT0_ LEFT OUTER JOIN EVENT_NOTES NOTES1_ ON EVENT0_.ID=NOTES1_.ENTITY_ID LEFT OUTER JOIN NOTE NOTE2_ ON NOTES1_.NOTE_ID=NOTE2_.ID LEFT OUTER JOIN NOTE NOTE3_ ON [*]"; expected "NOT, EXISTS, INTERSECTS"; SQL statement:
select count(event0_.id) as col_0_0_ from event event0_ left outer join event_notes notes1_ on event0_.id=notes1_.entity_id left outer join note note2_ on notes1_.note_id=note2_.id left outer join note note3_ on [42001-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357) ~[h2-1.4.197.jar:1.4.197]
```

```java
@Entity
@Inheritance(strategy=InheritanceType.JOINED)
public abstract class Event extends AnnotatedAuditedEntity {...}

@MappedSuperclass
public class AnnotatedAuditedEntity extends AuditedEntity {
    @ManyToMany(cascade = CascadeType.ALL)
    @MapKey(name = "key")
    @JoinTable(
            joinColumns=@JoinColumn(name="entity_id", referencedColumnName="id"),
            inverseJoinColumns=@JoinColumn(name="note_id", referencedColumnName="id"))
    Map<String, Note> notes = newHashMap();
}

@Entity
@Inheritance(strategy = InheritanceType.JOINED)
public class Note {
    @Column(length = SHORT_MAX_LENGTH)
    private String note;
}

@Entity
public class DefaultNote extends Note {
    @Column(length = DEFAULT_MAX_LENGTH)
    private String note2;
}
```

What's wrong?

**Comment by jwgmeligmeyling** [comment]
You're mixing up entity joins and collection joins. As per JPA 2.1 specification, entity joins require an ON clause, even if its just `1=1`.

However, the join you're creating is unnecessary with JPA. When `InheritanceType.JOINED` is used for `Note`, any association join to `Note` will automatically join `DefaultNote` so that `DefaultNotes` are returned as `DefaultNote` and not as `Note` instance. 

So just 

```java
QueryResults results = from(QEvent.event)
.leftJoin(QEvent.event.notes)
.fetchResults();
```
will actually generate the join you want...
