### ISSUE TITLE
Failed to process classes when using records available in JDK 14

### ISSUE THREAD

**Issue by gasparbarancelli** [querydsl/querydsl#2551]
When adding a record like the example below, the data processing fails.

```java
public record VariaveisContrato(int id, String value)
```

```log
[INFO] --- apt-maven-plugin:1.1.3:process (default) @ contrato ---
C:\viasoft\contrato\src\main\java\br\com\viasoft\contrato\modeloContrato\VariaveisContrato.java:12: error: records are a preview feature and are disabled by default.
public record VariaveisContrato(int id, String value) {
       ^
  (use --enable-preview to enable records)
1 error
```

Exclude class doesn't work either
```xml
<options>
<querydsl.excludedClasses>......VariaveisContrato</querydsl.excludedClasses>
</options>
```

**Comment by felixgilioli** [comment]
I also have this problem.

**Comment by kamko** [comment]
Is the jvm running with preview features enabled?

**Comment by gasparbarancelli** [comment]
Enabled preview is set @kamko 
```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>3.8.1</version>
    <configuration>
        <source>14</source>
        <target>14</target>
        <release>14</release>
        <compilerArgs>
            --enable-preview
        </compilerArgs>
    </configuration>
</plugin>
```

**Comment by gasparbarancelli** [comment]
> Is the jvm running with preview features enabled?

Is there any way to run the plugin with the --enable-preview compilation parameter?

**Comment by rsandtner** [comment]
just ran into this problem to not be able to enable preview in another case but maybe this will help here too?
specify a compiler option that does not hurt and doesn't expect a value and specify ```--enable-preview``` as value

```                            
<compilerOptions>
  <source>${java.version}</source>
  <deprecation>--enable-preview</deprecation>
</compilerOptions>
```

I know its a bloody workaround but this works for me

**Comment by schrepfler** [comment]
I'm not sure how relevant this is but I've noticed that when trying to query using the collections module via Alias I'm getting a ```
java.lang.IllegalArgumentException: Cannot subclass final class ...
```
as it seems CGLIB is trying to extend the record which is final class so likely this will need to be rethought.

**Comment by eacdy** [comment]
@schrepfler same problem. 
```java
Exception in thread "main" java.lang.IllegalArgumentException: Cannot subclass final class com.example.querydsltest.Cat
	at net.sf.cglib.proxy.Enhancer.generateClass(Enhancer.java:565)
	at net.sf.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
	at net.sf.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:332)
	at net.sf.cglib.proxy.Enhancer.generate(Enhancer.java:492)
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:96)
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:94)
	at net.sf.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at net.sf.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
	at net.sf.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:119)
	at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:294)
	at net.sf.cglib.proxy.Enhancer.createHelper(Enhancer.java:480)
	at net.sf.cglib.proxy.Enhancer.create(Enhancer.java:305)
	at com.querydsl.core.alias.AliasFactory.createProxy(AliasFactory.java:113)
	at com.querydsl.core.alias.AliasFactory.lambda$createAliasForExpr$1(AliasFactory.java:61)
	at java.base/java.util.Map.computeIfAbsent(Map.java:1054)
	at java.base/java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2760)
	at com.querydsl.core.alias.AliasFactory.createAliasForExpr(AliasFactory.java:61)
	at com.querydsl.core.alias.AliasFactory.createAliasForVariable(AliasFactory.java:89)
	at com.querydsl.core.alias.Alias.alias(Alias.java:388)
	at com.example.querydsltest.QuerydslTestApplication.main(QuerydslTestApplication.java:23)
```
