### ISSUE TITLE
Wrong generated left join when selecting attributes in several child-classes (singleTable) contains underscore, fails later with org.hibernate.hql.internal.ast.QuerySyntaxException

### ISSUE THREAD

**Issue by githubIsBugtrack** [querydsl/querydsl#2570]
There is an underscore in the autogenerated left join where a point would be expected.
Problem only for childclasses.

### Minimalexample: Description - Classes - Exceptions

**Description**
I have a class Mandant which contains TulleEntity.

TulleEntity is an abstract class (but abstract or not does not matter for the problem) and has two children: TulleA and Tulle B. When asked for an attribute in Parentclass, everything is fine, so 
`QMandant.mandant.tulle.kurs `
translates to

```sql
select mandant
from Mandant mandant
  left join mandant.tulle as mandant_tulle
where ?1 = ?1
```

...but
`QMandant.mandant.tulle.as(TulleB.class).kursb`

translates to
```sql
select mandant
from Mandant mandant
  left join mandant.tulle as mandant_tulle
  left join mandant_tulle as mandant_tulle
where ?1 = ?1
..some order but not relevant for example..
```

**Classes**
==========The main Entity which contains the parent attribute  ======================
```java
@Entity
public class Mandant extends BasisEntity {

    @OneToOne(fetch = FetchType.LAZY, orphanRemoval = true, cascade = CascadeType.ALL)
    private TulleEntity tulle;

    public TulleEntity getTulle() {
        return tulle;
    }

    public void setTulle(TulleEntity tulle) {
        this.tulle = tulle;
    }
// and so on
}
```

=========== the abstract parent attribute with one field =====================
```java
@Entity
public abstract class TulleEntity extends BasisEntity {

    private String kurs;

    public String getKurs() {
        return this.kurs;

    }
    public void setKurs(String kurs) {
        this.kurs = kurs;
    }

}
```
==============first child ===================
```java
@Entity
@DiscriminatorValue("AAA")
public class TulleA extends TulleEntity {

    private String kursa;

    public String getKursa() {
        return kursa;
    }

    public void setKurs(String kursa) {
        this.kursa = kursa;
    }

}
```

=============second child ==================
```java
@Entity
@DiscriminatorValue("BBB")
public class TulleB extends TulleEntity {

    private String kursb;

    public String getKursb() {
        return kursb;
    }

    public void setKursb(String kursb) {
        this.kursb = kursb;
    }
}
```
==========================================
dependencies
```xml
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.2.6.RELEASE</version>
	</parent>
                
               <dependency>
			<groupId>com.querydsl</groupId>
			<artifactId>querydsl-jpa</artifactId>
		</dependency>
		<dependency>
			<groupId>com.querydsl</groupId>
			<artifactId>querydsl-apt</artifactId>
		</dependency>
```

==================================================

**Exception**

```
org.springframework.dao.InvalidDataAccessApiUsageException: org.hibernate.hql.internal.ast.QuerySyntaxException: Path expected for join!
select mandant
from Mandant mandant
  left join mandant.tulle as mandant_tulle
  left join mandant_tulle as mandant_tulle
where ?1 = ?1
..some order but not relevant for example..
	at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:374) ~[spring-orm-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:257) ~[spring-orm-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:528) ~[spring-orm-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61) ~[spring-tx-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242) ~[spring-tx-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:153) ~[spring-tx-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:178) ~[spring-data-jpa-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95) ~[spring-aop-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at com.sun.proxy.$Proxy180.findAll(Unknown Source) ~[na:na]
..my code ..
```

**Comment by jwgmeligmeyling** [comment]
I think `QMandant.mandant.tulle.as(TulleB.class).kursb` is invalid. Shouldn't this be `QMandant.mandant.tulle.as(QTulleB.class).kursb`? See also the example in [`JPACollectionAnyVisitorTest`](https://github.com/querydsl/querydsl/blob/master/querydsl-jpa/src/test/java/com/querydsl/jpa/JPACollectionAnyVisitorTest.java#L116-L121). You may also want to use a `TREAT` join instead, for this see the example in https://github.com/querydsl/querydsl/pull/705/files#diff-f208b512cfb32710b5c3db287221f23fR210 . I've also proposed a solution for TREATED Paths that can be used for this: #2530
