### ISSUE TITLE
querydsl-mongodb: usage of concat gives illegal operation

### ISSUE THREAD

**Issue by kesslerj** [querydsl/querydsl#2585]
Hi,
with querydsl-mongodb version 4.2.2 or 4.3.1 concatenating fields using

`QNotification.notification.name2.concat(" ").concat(QNotification.notification.name1)          .containsIgnoreCase(searchString)`

gives an StackTrace containing

`Caused by: java.lang.UnsupportedOperationException: Illegal operation notification.name2 +   + notification.name1
	at org.springframework.data.mongodb.repository.support.MongodbDocumentSerializer.visit(MongodbDocumentSerializer.java:323)
	at org.springframework.data.mongodb.repository.support.MongodbDocumentSerializer.visit(MongodbDocumentSerializer.java:54)`

when executing the query.

**Comment by kesslerj** [comment]
It seems as if the mongo db itself does not support this operation, so this not an issue with querydsl. My solution was to store `name2 + '  ' + name1` as separate field in the database to be able to execute my desired query.
