### ISSUE TITLE
querydsl-maven-plugin haven't not support customTypes?

### ISSUE THREAD

**Issue by coderhuang** [querydsl/querydsl#2613]
I use the plugin to generate bean and Qobject
`<groupId>com.querydsl</groupId>
<artifactId>querydsl-maven-plugin</artifactId>
<version>4.3.0</version>`

it works well without cutomTypes,when i add an customType like below
`<customTypes>
						<customType>com.testing.domain.base.query.type.BookCategoryEnumType</customType>
					</customTypes>`

`package com.testing.domain.base.query.type;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;

import com.querydsl.sql.types.Type;
import com.testing.domain.base.BookCategoryEnum;

public class BookCategoryEnumType implements Type<BookCategoryEnum> {

	@Override
	public Class<BookCategoryEnum> getReturnedClass() {
		
		return BookCategoryEnum.class;
	}

	@Override
	public BookCategoryEnum getValue(ResultSet rs, int startIndex) throws SQLException {
		
		int code = rs.getInt(startIndex);
		
		return BookCategoryEnum.getEnumInstance(getReturnedClass(), code);
	}

	@Override
	public void setValue(PreparedStatement st, int startIndex, BookCategoryEnum value) throws SQLException {
		
		st.setInt(startIndex, value.getCode());
	}

	@Override
	public int[] getSQLTypes() {
		
		return new int[Types.INTEGER];
	}

	@Override
	public String getLiteral(BookCategoryEnum value) {
		
		return value.getCode().toString();
	}

	
}
`
`package com.testing.domain.base;

import org.apache.commons.lang3.ArrayUtils;

import com.testing.domain.base.define.BaseIntegerEnumInterface;

public enum BookCategoryEnum implements BaseIntegerEnumInterface {

	/**
	 * 科学类图书
	 */
	SICENCE(1, "科学"),

	/**
	 * 技术类图书
	 */
	TECHNOLOGY(2, "技术"),

	/**
	 * 生物类图书
	 */
	BIOLOGICAL(3, "生物"),
	
	
	/**
	 * 其他类图书
	 */
	OTHERS(100, "其他");

	Integer code;

	String label;

	private BookCategoryEnum(Integer code, String label) {

		this.code = code;
		this.label = label;
	}

	@Override
	public Integer getCode() {

		return code;
	}

	@Override
	public String getLabel() {

		return label;
	}
	
	public static BookCategoryEnum getEnumInstance(Class<?> clazz, Integer code) {
		
		Class<BookCategoryEnum> originClazz = BookCategoryEnum.class;
		if (!clazz.isAssignableFrom(originClazz)) {
			
			throw new IllegalStateException(String.format("%1$s 不是 %2$s的子类", clazz.getName(), originClazz.getName()));
		}
		
		BookCategoryEnum[] enumArray = originClazz.getEnumConstants();
		if (ArrayUtils.isEmpty(enumArray)) {
			
			throw new IllegalStateException(String.format("%1$s 枚举没有合法的值", originClazz.getName()));
		}
		
		for (int i = 0; i < enumArray.length; i++) {
			
			if (enumArray[i].getCode().equals(code)) {
				
				return enumArray[i];
			}
		}
		
		throw new IllegalStateException(String.format("入参：%1$d ;不是%2$s的合法值", code, originClazz.getName()));
	}
}
`
`package com.testing.domain.base.define;

import java.io.Serializable;

public interface BaseIntegerEnumInterface extends Serializable {

	/**
	 * @return
	 */
	Integer getCode();
	
	/**
	 * @return
	 */
	String getLabel();
	
}
`
it throw exception like below 
`com.testing.domain.base.query.type.BookCategoryEnumType (com.querydsl:querydsl-maven-plugin:4.3.0:export:default:generate-sources)

org.apache.maven.plugin.MojoExecutionException: com.testing.domain.base.query.type.BookCategoryEnumType
	at com.querydsl.maven.AbstractMetaDataExportMojo.execute(AbstractMetaDataExportMojo.java:545)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:332)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.lambda$8(MavenImpl.java:1379)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:179)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:114)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1378)
	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:54)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:135)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:169)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$1(MavenBuilder.java:114)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:179)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:114)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$0(MavenBuilder.java:105)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:179)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:153)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:101)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:88)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:197)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:832)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:371)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:392)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.ClassNotFoundException: com.testing.domain.base.query.type.BookCategoryEnumType
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at `

**Comment by wo3002807** [comment]
you should add dependency jar contain that class into pom.xml. for example:
<plugin>
       <groupId>com.querydsl</groupId>
       <artifactId>querydsl-maven-plugin</artifactId>
        <version>4.3.1</version>
        <executions>
             <execution>
             <goals>
                <goal>export</goal>
               </goals>
          </execution>
        </executions>
        <configuration>
              .........
        </configuration>
                <dependencies>
                    <dependency>
                        <groupId>mysql</groupId>
                        <artifactId>mysql-connector-java</artifactId>
                        <version>5.1.46</version>
                    </dependency>
                   ..... that depency container that class. or show ClassNotFoundException
                </dependencies>
            </plugin>

**Comment by coderhuang** [comment]
> you should add dependency jar contain that class into pom.xml. for example:
> `
> ```
>    <groupId>com.querydsl</groupId>
>    <artifactId>querydsl-maven-plugin</artifactId>
>     <version>4.3.1</version>
>     <executions>
>          <execution>
>          <goals>
>             <goal>export</goal>
>            </goals>
>       </execution>
>     </executions>
>     <configuration>
>           .........
>     </configuration>
>     <dependencies>
>          <dependency>
>             <groupId>mysql</groupId>
>             <artifactId>mysql-connector-java</artifactId>
>              <version>5.1.46</version>
>            </dependency>
>         ..... that depency container that class. or show ClassNotFoundException
>       </dependencies>
> ```
> 
> `

第二天我自己也意识到这个问题了
不过还是感谢前来回答

**Comment by coderhuang** [comment]
第二天我自己也意识到这个问题了
不过还是感谢前来回答

**Comment by coderhuang** [comment]
第二天我自己也意识到这个问题了，只是不知道如何引用我本地的工程进去
