### ISSUE TITLE
why Unexpected gap in ordinal parameter labels [1 -> 4] : [1,4,5]

### ISSUE THREAD

**Issue by Little0Sheep** [querydsl/querydsl#2624]
`JPAQuery<QUserTEntity> jpaQuery = (JPAQuery<QUserTEntity>) jpaQueryFactory
                .from(qUserTEntity).leftJoin(qDeptTEntity)
                .on(qUserTEntity.deptId.eq(qDeptTEntity.deptId)).where(qUserTEntity.userId.in(1,2,3));`

`java.lang.IllegalArgumentException: org.hibernate.QueryException: Unexpected gap in ordinal parameter labels [1 -> 4] : [1,4,5]
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:138) ~[hibernate-core-5.4.8.Final.jar:5.4.8.Final]
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1535) ~[hibernate-core-5.4.8.Final.jar:5.4.8.Final]
	at org.hibernate.query.internal.QueryImpl.list(QueryImpl.java) ~[hibernate-core-5.4.8.Final.jar:5.4.8.Final]
	at org.hibernate.query.internal.AbstractProducedQuery.getSingleResult(AbstractProducedQuery.java:1574) ~[hibernate-core-5.4.8.Final.jar:5.4.8.Final]
	at com.querydsl.jpa.impl.AbstractJPAQuery.fetchCount(AbstractJPAQuery.java:82) ~[querydsl-jpa-4.3.1.jar:na]`

Why is this so

querydsl version:4.3.1

help me，thanks

**Comment by Little0Sheep** [comment]
List<UserTEntity> userTEntityList = jpaQueryFactory
                .select(qUserTEntity)
                .from(qUserTEntity)
                .where(qUserTEntity.userId.in(1, 2, 3))
                .fetch();

java.lang.IllegalArgumentException: org.hibernate.QueryException: Unexpected gap in ordinal parameter labels [1 -> 4] : [1,4,5]
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:138) ~[hibernate-core-5.4.15.Final.jar:5.4.15.Final]
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1542) ~[hibernate-core-5.4.15.Final.jar:5.4.15.Final]
	at org.hibernate.query.internal.QueryImpl.list(QueryImpl.java) ~[hibernate-core-5.4.15.Final.jar:5.4.15.Final]
	at org.hibernate.query.Query.getResultList(Query.java:165) ~[hibernate-core-5.4.15.Final.jar:5.4.15.Final]

what's wrong?

**Comment by jwgmeligmeyling** [comment]
Could you provide a full stack trace? The relevant portion is omitted, we only see Hibernate logs now.

**Comment by Little0Sheep** [comment]
> Could you provide a full stack trace? The relevant portion is omitted, we only see Hibernate logs now. Also, from the stack trace, it seems you're calling `fetchCount()` or `fetchResults()` and not `fetch()` as you mention in your code snippet. It's better to always use `fetch()` in JPA.

thank you for your reply

springBoot:2.3.0
jpa:2.3.0
querydsl:4.3.1

simple example，use in condition

        List<Long> userIds=jpaQueryFactory.from(qUserTEntity)
                .select(qUserTEntity.userId)
                .where(qUserTEntity.userId.in(1,2,3))
                .fetch();

full stack trace

java.lang.IllegalArgumentException: org.hibernate.QueryException: Unexpected gap in ordinal parameter labels [1 -> 4] : [1,4,5]
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:138) ~[hibernate-core-5.4.15.Final.jar:5.4.15.Final]
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1542) ~[hibernate-core-5.4.15.Final.jar:5.4.15.Final]
	at org.hibernate.query.internal.QueryImpl.list(QueryImpl.java) ~[hibernate-core-5.4.15.Final.jar:5.4.15.Final]
	at org.hibernate.query.Query.getResultList(Query.java:165) ~[hibernate-core-5.4.15.Final.jar:5.4.15.Final]
	at com.querydsl.jpa.impl.AbstractJPAQuery.getResultList(AbstractJPAQuery.java:160) ~[querydsl-jpa-4.3.1.jar:na]
	at com.querydsl.jpa.impl.AbstractJPAQuery.fetch(AbstractJPAQuery.java:202) ~[querydsl-jpa-4.3.1.jar:na]
	at com.lt.userorg.service.impl.em.UserServiceImpl.findAllUserByPage(UserServiceImpl.java:264) ~[classes/:na]
	at com.lt.userorg.service.impl.em.UserServiceImpl$$FastClassBySpringCGLIB$$47b1b80b.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687) ~[spring-aop-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at com.lt.userorg.service.impl.em.UserServiceImpl$$EnhancerBySpringCGLIB$$edd99dba.findAllUserByPage(<generated>) ~[classes/:na]
	at com.lt.userorg.controller.SysUserController.findAllUserByPage(SysUserController.java:39) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105) ~[spring-webmvc-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879) ~[spring-webmvc-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793) ~[spring-webmvc-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) ~[spring-webmvc-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) ~[spring-webmvc-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.35.jar:9.0.35]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123) ~[druid-1.1.10.jar:1.1.10]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.apache.catalina.core.StandardContextValve.__invoke(StandardContextValve.java:96) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:41002) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) [tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.35.jar:9.0.35]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.35.jar:9.0.35]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
Caused by: org.hibernate.QueryException: Unexpected gap in ordinal parameter labels [1 -> 4] : [1,4,5]
	at org.hibernate.query.internal.ParameterMetadataImpl.<init>(ParameterMetadataImpl.java:75) ~[hibernate-core-5.4.15.Final.jar:5.4.15.Final]
	at org.hibernate.engine.query.spi.HQLQueryPlan.buildParameterMetadata(HQLQueryPlan.java:430) ~[hibernate-core-5.4.15.Final.jar:5.4.15.Final]
	at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:130) ~[hibernate-core-5.4.15.Final.jar:5.4.15.Final]
	at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:73) ~[hibernate-core-5.4.15.Final.jar:5.4.15.Final]
	at org.hibernate.engine.query.spi.QueryPlanCache.getHQLQueryPlan(QueryPlanCache.java:155) ~[hibernate-core-5.4.15.Final.jar:5.4.15.Final]
	at org.hibernate.internal.AbstractSharedSessionContract.getQueryPlan(AbstractSharedSessionContract.java:604) ~[hibernate-core-5.4.15.Final.jar:5.4.15.Final]
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1394) ~[hibernate-core-5.4.15.Final.jar:5.4.15.Final]
	at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1565) ~[hibernate-core-5.4.15.Final.jar:5.4.15.Final]
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1533) ~[hibernate-core-5.4.15.Final.jar:5.4.15.Final]
	... 64 common frames omitted

**Comment by Little0Sheep** [comment]
> Could you provide a full stack trace? The relevant portion is omitted, we only see Hibernate logs now. Also, from the stack trace, it seems you're calling `fetchCount()` or `fetchResults()` and not `fetch()` as you mention in your code snippet. It's better to always use `fetch()` in JPA.

Only one value is normal

        List<Long> userIds=jpaQueryFactory.from(qUserTEntity)
                .select(qUserTEntity.userId)
                .where(qUserTEntity.userId.in(1))
                .fetch();

Hibernate: 
    select
        usertentit0_.user_id as col_0_0_ 
    from
        user_t usertentit0_ 
    where
        usertentit0_.user_id=?
2020-07-14 17:20:52.150 TRACE 15732 --- [nio-8863-exec-5] o.h.type.descriptor.sql.BasicBinder      : binding parameter [1] as [BIGINT] - [1]

**Comment by Little0Sheep** [comment]
![image](https://user-images.githubusercontent.com/23427472/87513956-178ccf00-c6ac-11ea-9f97-cc125417e226.png)

oh my god

locate by debug

The same version actually has this kind of thing?

**Comment by jwgmeligmeyling** [comment]
I do these kind of queries all the time. Could you downgrade Hibernate to a slightly lower 5.4.x? I'm still investigating this.

**Comment by Little0Sheep** [comment]
> Could you provide a full stack trace? The relevant portion is omitted, we only see Hibernate logs now. Also, from the stack trace, it seems you're calling `fetchCount()` or `fetchResults()` and not `fetch()` as you mention in your code snippet. It's better to always use `fetch()` in JPA.

Hello, my problem is solved, because there are multiple versions of hibernate

**Comment by Little0Sheep** [comment]
> I do these kind of queries all the time. Could you downgrade Hibernate to a slightly lower 5.4.x? I'm still investigating this.

I use idea development tools，multiple modules are introduced in one project

There are two versions of hibernate in this one, one is 5.3.10 and the other is 5.4.15, which runs with errors

I took out the modules inside and downloaded the maven dependencies again, my in query was normal

I currently suspect maven dependency conflict

I'm working on the same version of the project, and the in-condition query is normal

thank you

**Comment by jwgmeligmeyling** [comment]
Good luck with your application 😄
