### ISSUE TITLE
ListPath has error on query

### ISSUE THREAD

**Issue by wenslo** [querydsl/querydsl#2651]
My entity used @Convert at Entity
like this :
```
    @Convert(converter = StringListConverter.class)
    private List<String> economyItem11;
```
My converter is :
```
    @Override
    public String convertToDatabaseColumn(List<String> attribute) {
        if (Objects.nonNull(attribute) && !attribute.isEmpty()) {
            return String.join(",", attribute);
        }
        return null;
    }

    @Override
    public List<String> convertToEntityAttribute(String dbData) {
        if (StringUtils.isNoneBlank(dbData)) {
            return Arrays.stream(dbData.split(",")).collect(Collectors.toList());
        }
        return Lists.newArrayList();
    }
```
When I query used JPAQuery, it throw a error(NullPointerException), I don't understand why it is not useful? How can I use ListPath with @Convert on queryDSL?
My query is 
```
        if (StringUtils.isNotBlank(economyItem10)) {
            builder.and(profile.economyItem10.any().isNotNull().and(profile.economyItem10.contains(economyItem10)));
        }
```
Exception is
```
java.lang.NullPointerException: null
	at org.hibernate.hql.internal.ast.HqlSqlWalker.createFromJoinElement(HqlSqlWalker.java:429)
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.joinElement(HqlSqlBaseWalker.java:3920)
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.fromElement(HqlSqlBaseWalker.java:3706)
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.fromElementList(HqlSqlBaseWalker.java:3584)
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.fromClause(HqlSqlBaseWalker.java:720)
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.query(HqlSqlBaseWalker.java:576)
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.collectionFunctionOrSubselect(HqlSqlBaseWalker.java:4927)
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.comparisonExpr(HqlSqlBaseWalker.java:4624)
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.logicalExpr(HqlSqlBaseWalker.java:2138)
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.logicalExpr(HqlSqlBaseWalker.java:2063)
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.whereClause(HqlSqlBaseWalker.java:815)
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.query(HqlSqlBaseWalker.java:609)
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.selectStatement(HqlSqlBaseWalker.java:313)
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.statement(HqlSqlBaseWalker.java:261)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.analyze(QueryTranslatorImpl.java:271)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.doCompile(QueryTranslatorImpl.java:191)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.compile(QueryTranslatorImpl.java:143)
	at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:119)
	at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:80)
	at org.hibernate.engine.query.spi.QueryPlanCache.getHQLQueryPlan(QueryPlanCache.java:153)
	at org.hibernate.internal.AbstractSharedSessionContract.getQueryPlan(AbstractSharedSessionContract.java:595)
	at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:704)
	at org.hibernate.internal.AbstractSessionImpl.createQuery(AbstractSessionImpl.java:23)
	at sun.reflect.GeneratedMethodAccessor124.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.orm.jpa.ExtendedEntityManagerCreator$ExtendedEntityManagerInvocationHandler.invoke(ExtendedEntityManagerCreator.java:350)
	at com.sun.proxy.$Proxy140.createQuery(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor124.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:308)
	at com.sun.proxy.$Proxy140.createQuery(Unknown Source)
	at com.querydsl.jpa.impl.AbstractJPAQuery.createQuery(AbstractJPAQuery.java:101)
	at com.querydsl.jpa.impl.AbstractJPAQuery.createQuery(AbstractJPAQuery.java:94)
	at com.querydsl.jpa.impl.AbstractJPAQuery.fetch(AbstractJPAQuery.java:201)
	at org.springframework.data.jpa.repository.support.QuerydslJpaPredicateExecutor.findAll(QuerydslJpaPredicateExecutor.java:151)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:359)
	at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:200)
```

**Comment by wenslo** [comment]
QueryDSL version is 4.2.1

**Comment by jwgmeligmeyling** [comment]
Columns mapped through a Converter, are basic types. In queries they cannot be treated as collections. The only valid comparisons are null-ness and equality checks, for which the value compared against is also first converted through the converter.

I.e. the "collection" contains is not possible here, because its not possible in JPQL. Where the underlying type of the field is a string, you might be able to do regular string operations on it.

The bug in QueryDSL here lies in the fact that the determination of the metamodel property type is determined by the field type (in this case `List`). In this case, the JPA annotations should have been regarded. Instead of a `ListExpression`, a `StringExpression` should have been used here.

To work around this issue in the metamodel, simply wrap the List path expression in a String expression: `Expressions.stringPath(profile.economyItem10).contains(economyItem10)`.

That said, due to limitations in how JPA Attribute converters work, you still might not get the desired result. When using PostgreSQL, you might find a string-array to be a viable alternative. When this array is mapped using a custom type from Hibernate-Types, you can also use this in QueryDSL using the https://github.com/jwgmeligmeyling/hibernate-types-querydsl-apt extension.

**Comment by jwgmeligmeyling** [comment]
Actually, a better work around might be to specify the `QueryType` on the field instead:

```java
@QueryType(PropertyType.STRING)
@Convert(converter = StringListConverter.class)
private List<String> economyItem11;
```

**Comment by wenslo** [comment]
@jwgmeligmeyling Thank you very much!

**Comment by jwgmeligmeyling** [comment]
Did any of the suggested methods work?

**Comment by Credo-Zhao** [comment]
> Did any of the suggested methods work?

I tested it and it didn't work.

Exception:
java.lang.IllegalArgumentException: Parameter value [[{"bizDate":"2020-09-30T12:09:26.119566","notes":"1xxxxx"},{"bizDate":"2020-09-30T12:09:26.119599","notes":"2xxxxx"}]] did not match expected type [java.util.List (n/a)]
at org.hibernate.query.spi.QueryParameterBindingValidator.validate(QueryParameterBindingValidator.java:54)
	at org.hibernate.query.spi.QueryParameterBindingValidator.validate(QueryParameterBindingValidator.java:27)
	at org.hibernate.query.internal.QueryParameterBindingImpl.validate(QueryParameterBindingImpl.java:90)
	at org.hibernate.query.internal.QueryParameterBindingImpl.setBindValue(QueryParameterBindingImpl.java:55)
	at org.hibernate.query.internal.AbstractProducedQuery.setParameter(AbstractProducedQuery.java:508)
	at org.hibernate.query.internal.AbstractProducedQuery.setParameter(AbstractProducedQuery.java:111)
	at com.querydsl.jpa.impl.JPAUtil.setConstants(JPAUtil.java:56)
	at com.querydsl.jpa.impl.JPAUpdateClause.execute(JPAUpdateClause.java:76)

**Comment by jwgmeligmeyling** [comment]
There's a difference between setting and applying functions on the expression. `@QueryType(PropertyType.STRING)` is needed to render a String representation in the metamodel, which is required for proper handling of `contains`. If you want to set the value to an instance, you need the normal type because it will pass the converters in this case.

Bottom line: just wrap the expression in the appropiate expression type depending on where you need it.

For contains: `Expressions.stringPath((Path) profile.economyItem10`
For set: `Expressions.path(List.class, (Path)  profile.economyItem10`

There actually seems no way to handle Converters better than we already do. I suggest to just avoid them actually.

**Comment by Credo-Zhao** [comment]
> There's a difference between setting and applying functions on the expression. `@QueryType(PropertyType.STRING)` is needed to render a String representation in the metamodel, which is required for proper handling of `contains`. If you want to set the value to an instance, you need the normal type because it will pass the converters in this case.
> 
> Bottom line: just wrap the expression in the appropiate expression type depending on where you need it.
> 
> For contains: `Expressions.stringPath((Path) profile.economyItem10).contains(...)`
> For set: `Expressions.path(List.class, (Path) profile.economyItem10)`
> 
> There actually seems no way to handle Converters better than we already do. I suggest to just avoid them actually.

ok......I will avoid it.
