### ISSUE TITLE
Integration with others annotation processors

### ISSUE THREAD

**Issue by wesleytamiarana** [querydsl/querydsl#2654]
Hi,

I am trying using it on a conceptual project but I am facing some issues since we have others annotation processors (Lombok, MapStruct and Immutables). I have tried many combinations the only one that export the classes properly is using the querydsl-maven-plugin but, some configurations does not work properly, mas last configuration was:

```
<plugin>
	<groupId>com.querydsl</groupId>
	<artifactId>querydsl-maven-plugin</artifactId>
	<version>4.3.1</version>
	<configuration>
		<namePrefix>""</namePrefix>
		<nameSuffix>Specification</nameSuffix>
		<targetFolder>target/generated-sources/annotations</targetFolder>
		<packages>
			<package>xx.yyyy.zzz</package>
		</packages>
	</configuration>
	<executions>
		<execution>
			<phase>process-classes</phase>
			<goals>
				<goal>jpa-export</goal>
			</goals>
		</execution>
	</executions>
</plugin>

<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-compiler-plugin</artifactId>
	<version>3.8.1</version>
	<configuration>
		<useIncrementalCompilation>false</useIncrementalCompilation>
		<annotationProcessorPaths>
			<annotationProcessorPath>
				<groupId>org.immutables</groupId>
				<artifactId>value</artifactId>
				<version>2.8.8</version>
			</annotationProcessorPath>
			<annotationProcessorPath>
				<groupId>org.projectlombok</groupId>
				<artifactId>lombok</artifactId>
				<version>1.18.12</version>
			</annotationProcessorPath>
			<annotationProcessorPath>
				<groupId>org.mapstruct</groupId>
				<artifactId>mapstruct-processor</artifactId>
				<version>1.4.0.CR1</version>
			</annotationProcessorPath>
		</annotationProcessorPaths>
	</configuration>
</plugin>
```
But, even I define the namePrefix and nameSufix the plugin continue generating names by default Qxxx not xxSpecification .

Best,

**Comment by jwgmeligmeyling** [comment]
There is no need to use the `querydsl-maven-plugin`, you can just add `querydsl-apt` als `annotationProcessorPath`. It will automatically register the APT plugin.

**Comment by wesleytamiarana** [comment]
It does not work, adding the `querydsl-apt` to the `annotationProcessorPath` together the configuration mentioned before, no class is generated.

**Comment by HJK181** [comment]
For me it's also not working:
```
<dependencies>
<dependency>
				<groupId>com.querydsl</groupId>
				<artifactId>querydsl-jpa</artifactId>
				<version>${querydsl.version}</version>
			</dependency>

<dependencies>
...
<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>${compiler.maven.plugin}</version>
					<configuration>
						<source>${java.version}</source>
						<target>${java.version}</target>
						<configuration>
							<generatedSourcesDirectory>target/generated-sources/annotations</generatedSourcesDirectory>
							<compilerArgs>
								<arg>-Aquerydsl.entityAccessors=true</arg>
								<arg>-Aquerydsl.useFields=false</arg>
							</compilerArgs>
							<annotationProcessorPaths>
								<path>
									<groupId>org.mapstruct</groupId>
									<artifactId>mapstruct-processor</artifactId>
									<version>${mapstruct.version}</version>
								</path>
								<path>
									<groupId>org.projectlombok</groupId>
									<artifactId>lombok</artifactId>
									<version>${lombok.version}</version>
								</path>
								<path>
									<groupId>org.springframework.boot</groupId>
									<artifactId>spring-boot-configuration-processor</artifactId>
									<version>${spring-boot.version}</version>
								</path>
								<dependencies>
									<dependency>
										<groupId>com.querydsl</groupId>
										<artifactId>querydsl-apt</artifactId>
										<version>${querydsl.version}</version>
									</dependency>
								</dependencies>
							</annotationProcessorPaths>
						</configuration>
					</configuration>
				</plugin>
```

**Comment by jwgmeligmeyling** [comment]
Try specifiying `<classifier>jpa</classifier>`  for your `querydsl-apt` dependencies.

**Comment by HJK181** [comment]
Tried it without success, even when I uncomment all the mapstruct/lombok/spring related stuff
```
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-compiler-plugin</artifactId>
  <version>${compiler.maven.plugin}</version>
  <configuration>
	<source>${java.version}</source>
	<target>${java.version}</target>
	<generatedSourcesDirectory>target/generated-sources/annotations</generatedSourcesDirectory>
	<compilerArgs>
	  <arg>-Aquerydsl.entityAccessors=true</arg>
	  <arg>-Aquerydsl.useFields=false</arg>
	</compilerArgs>
<!-- 						<annotationProcessorPaths> -->
<!-- 							<path> -->
<!-- 								<groupId>org.mapstruct</groupId> -->
<!-- 								<artifactId>mapstruct-processor</artifactId> -->
<!-- 								<version>${mapstruct.version}</version> -->
<!-- 							</path> -->
<!-- 							<path> -->
<!-- 								<groupId>org.projectlombok</groupId> -->
<!-- 								<artifactId>lombok</artifactId> -->
<!-- 								<version>${lombok.version}</version> -->
<!-- 							</path> -->
<!-- 							<path> -->
<!-- 								<groupId>org.springframework.boot</groupId> -->
<!-- 								<artifactId>spring-boot-configuration-processor</artifactId> -->
<!-- 								<version>${spring-boot.version}</version> -->
<!-- 							</path> -->
<!-- 						</annotationProcessorPaths> -->
  </configuration>
  <dependencies>
    <dependency>
	  <groupId>com.querydsl</groupId>
	  <artifactId>querydsl-apt</artifactId>
	  <version>${querydsl.version}</version>
	  <classifier>jpa</classifier>
	</dependency>	
  </dependencies>
</plugin>
``

**Comment by jwgmeligmeyling** [comment]
Please provide a full working example so I can have a look. This issue will be impossible to resolve with only parts of the configuration.

**Comment by HJK181** [comment]
Hi @jwgmeligmeyling,

please see https://github.com/HJK181/querydsl-2654

**Comment by HJK181** [comment]
I can see the following error in the eclipse error log:
```
java.lang.Exception: java.lang.NoClassDefFoundError: javax/persistence/Entity
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:172)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:124)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:171)
	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:138)
	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotationsInternal(Compiler.java:957)
	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:931)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:450)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:426)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:386)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:214)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:318)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:79)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:275)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:198)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:832)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:371)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:392)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.NoClassDefFoundError: javax/persistence/Entity
	at com.querydsl.apt.jpa.JPAAnnotationProcessor.createConfiguration(JPAAnnotationProcessor.java:37)
	at com.querydsl.apt.AbstractQuerydslProcessor.process(AbstractQuerydslProcessor.java:83)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:142)
	... 25 more
```

**Comment by HJK181** [comment]
This configuration works
```
<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>${java.version}</source>
					<target>${java.version}</target>
					<generatedSourcesDirectory>target/generated-sources/annotations</generatedSourcesDirectory>
					<compilerArgs>
						<arg>-Aquerydsl.entityAccessors=true</arg>
						<arg>-Aquerydsl.useFields=false</arg>
					</compilerArgs>
					<annotationProcessorPaths>
						<path>
							<groupId>org.mapstruct</groupId>
							<artifactId>mapstruct-processor</artifactId>
							<version>${mapstruct.version}</version>
						</path>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
							<version>${lombok.version}</version>
						</path>
						<path>
							<groupId>com.querydsl</groupId>
							<artifactId>querydsl-apt</artifactId>
							<version>${querydsl.version}</version>
							<classifier>jpa</classifier>
						</path>
						<path>
							<groupId>jakarta.persistence</groupId>
							<artifactId>jakarta.persistence-api</artifactId>
							<version>2.2.3</version>
						</path>
						<path>
							<groupId>javax.annotation</groupId>
							<artifactId>javax.annotation-api</artifactId>
							<version>1.3.1</version>
						</path>
					</annotationProcessorPaths>
				</configuration>
			</plugin>
```

**Comment by jwgmeligmeyling** [comment]
I think you can move the JPA and javax API dependencies to the `<dependencies>` section of the plugin configuration. There is no need to have them listed under `annotationsProcessorPaths`.

Also, I am surprised that `jakarta.persistence-api` isn't a transitive dependency of your project anyway. Did you exclude it elsewhere?

**Comment by HJK181** [comment]
As I wrote in my previous comment, `jakarta.persistence-api` is a transitive dependency of `spring-boot-starter-data-jpa`. However, if i don't include it in the `annotationProcessorPaths` I'm getting `java.lang.Exception: java.lang.NoClassDefFoundError: javax/persistence/Entity`. It also does not help to move it in the `dependecies` section of the plugin like suggested. but please see you self with the example provided.

**Comment by HJK181** [comment]
One additional side note, with the working example my Spring boot unit test do not start with the following error:
`Caused by: java.lang.NoClassDefFoundError: javassist/bytecode/ClassFile` 
I need to add 
```
<dependency>
				<groupId>org.javassist</groupId>
				<artifactId>javassist</artifactId>
				<version>3.23.2-GA</version>
</dependency>
```
to solve the issue. This was not needed before. Can't imagine how this is related in any way...

**Comment by wesleytamiarana** [comment]
> This configuration works
> 
> ```
> <plugin>
> 				<groupId>org.apache.maven.plugins</groupId>
> 				<artifactId>maven-compiler-plugin</artifactId>
> 				<configuration>
> 					<source>${java.version}</source>
> 					<target>${java.version}</target>
> 					<generatedSourcesDirectory>target/generated-sources/annotations</generatedSourcesDirectory>
> 					<compilerArgs>
> 						<arg>-Aquerydsl.entityAccessors=true</arg>
> 						<arg>-Aquerydsl.useFields=false</arg>
> 					</compilerArgs>
> 					<annotationProcessorPaths>
> 						<path>
> 							<groupId>org.mapstruct</groupId>
> 							<artifactId>mapstruct-processor</artifactId>
> 							<version>${mapstruct.version}</version>
> 						</path>
> 						<path>
> 							<groupId>org.projectlombok</groupId>
> 							<artifactId>lombok</artifactId>
> 							<version>${lombok.version}</version>
> 						</path>
> 						<path>
> 							<groupId>com.querydsl</groupId>
> 							<artifactId>querydsl-apt</artifactId>
> 							<version>${querydsl.version}</version>
> 							<classifier>jpa</classifier>
> 						</path>
> 						<path>
> 							<groupId>jakarta.persistence</groupId>
> 							<artifactId>jakarta.persistence-api</artifactId>
> 							<version>2.2.3</version>
> 						</path>
> 						<path>
> 							<groupId>javax.annotation</groupId>
> 							<artifactId>javax.annotation-api</artifactId>
> 							<version>1.3.1</version>
> 						</path>
> 					</annotationProcessorPaths>
> 				</configuration>
> 			</plugin>
> ```

Does MapStruct work properly for you with that configuration? In my case, the mappers are not generated/updated.

**Comment by HJK181** [comment]
Yes, it works for me. Added a working example to my project.
