### ISSUE TITLE
Spring-boot 2.3 upgrade generates java.lang.UnsupportedOperationException: null

### ISSUE THREAD

**Issue by renanleandrof** [querydsl/querydsl#2696]
Hello,

My project was using querydsl 4.1.3 and spring-boot 2.1.x
After upgrading to querydsl 4.4 and spring-boot 2.3.x i'm having this error:
```

2020-11-19 18:24:22.683 ERROR 26060 --- [  XNIO-1 task-2] io.undertow.request                      : UT005023: Exception handling request to /eaud/login

java.lang.UnsupportedOperationException: null
	at java.util.Collections$UnmodifiableMap.put(Collections.java:1457)
	at com.querydsl.jpa.JPQLSerializer.visitConstant(JPQLSerializer.java:327)
	at com.querydsl.core.support.SerializerBase.visit(SerializerBase.java:221)
	at com.querydsl.core.support.SerializerBase.visit(SerializerBase.java:36)
	at com.querydsl.core.types.ConstantImpl.accept(ConstantImpl.java:140)
	at com.querydsl.core.support.SerializerBase.handle(SerializerBase.java:122)
	at com.querydsl.core.support.SerializerBase.visitOperation(SerializerBase.java:301)
	at com.querydsl.jpa.JPQLSerializer.visitOperation(JPQLSerializer.java:437)
	at com.querydsl.core.support.SerializerBase.visit(SerializerBase.java:262)
	at com.querydsl.core.support.SerializerBase.visit(SerializerBase.java:36)
	at com.querydsl.core.types.OperationImpl.accept(OperationImpl.java:83)
	at com.querydsl.core.support.SerializerBase.handle(SerializerBase.java:122)
	at com.querydsl.jpa.JPQLSerializer.serialize(JPQLSerializer.java:220)
	at com.querydsl.jpa.JPAQueryBase.serialize(JPAQueryBase.java:60)
	at com.querydsl.jpa.JPAQueryBase.serialize(JPAQueryBase.java:50)
	at com.querydsl.jpa.impl.AbstractJPAQuery.createQuery(AbstractJPAQuery.java:98)
	at com.querydsl.jpa.impl.AbstractJPAQuery.fetchOne(AbstractJPAQuery.java:252)
	at br.gov.cgu.eaud.negocio.auth.UsuarioRepository.getPorCpfSeExistir(UsuarioRepository.java:63)
```

The query that produces the error is a very simple one:

```java
  private QUsuario usuario = QUsuario.usuario;

  public Usuario getPorCpfSeExistir(String cpf) {
        return getJPAQuery()
                .select(this.usuario)
                .from(this.usuario)
                .where(this.usuario.cpf.eq(cpf))
                .fetchOne();
    }
```
The method getJPAQuery is a simple `return new JPAQueryFactory(this.getEntityManager());`

I've tried using the version that comes with spring-boot 2.3, i.e, querydsl:4.3.1, but it won't work either. The version 4.1.3 also doesn't work.

Any clues on what could be causing this?

**Comment by jwgmeligmeyling** [comment]
This seems to be a version mismatch between the `querydsl-jpa` and `querydsl-core` dependencies.

**Comment by jwgmeligmeyling** [comment]
@idosal you've seen this issue before right? (I can't seem to find it)

**Comment by idosal** [comment]
@jwgmeligmeyling Are you referring to #2628 and #2611? 

It does seem likely that this is caused by a version mismatch. I have a project running with Querydsl 4.3.1 and Spring Boot 2.3.4 and I don't have an issue.

@renanleandrof Would you care to share your build configuration?

**Comment by harinduliyanage** [comment]
use these dependencies with given apt plugin if you are on the POM base project to resolve this issue. you should use 2.4.X spring version as well 

<dependency>
        <groupId>com.querydsl</groupId>
        <artifactId>querydsl-apt</artifactId>
        <version>4.1.3</version>
        <scope>provided</scope>
    </dependency>

    <dependency>
        <groupId>com.querydsl</groupId>
        <artifactId>querydsl-jpa</artifactId>
        <version>4.1.3</version>
    </dependency>

<plugin>
    <groupId>com.mysema.maven</groupId>
    <artifactId>apt-maven-plugin</artifactId>
    <version>1.1.3</version>
    <executions>
        <execution>
            <goals>
                <goal>process</goal>
            </goals>
            <configuration>
                <outputDirectory>target/generated-sources/java</outputDirectory>
                <processor>com.querydsl.apt.jpa.JPAAnnotationProcessor</processor>
            </configuration>
        </execution>
    </executions>
</plugin>

**Comment by harinduliyanage** [comment]
use these dependencies with given apt plugin if you are on the POM base project to resolve this issue. you should use 2.4.X spring version as well
`<dependency>
        <groupId>com.querydsl</groupId>
        <artifactId>querydsl-apt</artifactId>
        <version>4.1.3</version>
        <scope>provided</scope>
    </dependency>

    <dependency>
        <groupId>com.querydsl</groupId>
        <artifactId>querydsl-jpa</artifactId>
        <version>4.1.3</version>
    </dependency>
    
    
    
    <plugin>
    <groupId>com.mysema.maven</groupId>
    <artifactId>apt-maven-plugin</artifactId>
    <version>1.1.3</version>
    <executions>
        <execution>
            <goals>
                <goal>process</goal>
            </goals>
            <configuration>
                <outputDirectory>target/generated-sources/java</outputDirectory>
                <processor>com.querydsl.apt.jpa.JPAAnnotationProcessor</processor>
            </configuration>
        </execution>
    </executions>
    </plugin>`

**Comment by jwgmeligmeyling** [comment]
Thanks for posting, but Querydsl 5 works with both Spring Data 2.3 and 2.4 just fine.
