### ISSUE TITLE
JPASQLQuery vs JPAQuery inconsistency

### ISSUE THREAD

**Issue by Navodar22** [querydsl/querydsl#2702]
## Observed vs. expected behavior
```
Caused by: org.hibernate.MappingException: No Dialect mapping for JDBC type: 1111
	at org.hibernate.dialect.TypeNames.get(TypeNames.java:71)
	at org.hibernate.dialect.TypeNames.get(TypeNames.java:103)
	at org.hibernate.dialect.Dialect.getHibernateTypeName(Dialect.java:706)
	at org.hibernate.loader.custom.JdbcResultMetadata.getHibernateType(JdbcResultMetadata.java:100)
	at org.hibernate.loader.custom.ScalarResultColumnProcessor.performDiscovery(ScalarResultColumnProcessor.java:45)
	at org.hibernate.loader.custom.CustomLoader.autoDiscoverTypes(CustomLoader.java:494)
	at org.hibernate.loader.Loader.preprocessResultSet(Loader.java:2357)
	at org.hibernate.loader.Loader.getResultSet(Loader.java:2313)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2064)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2026)
	at org.hibernate.loader.Loader.doQuery(Loader.java:951)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:352)
	at org.hibernate.loader.Loader.doList(Loader.java:2857)
	at org.hibernate.loader.Loader.doList(Loader.java:2839)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2671)
	at org.hibernate.loader.Loader.list(Loader.java:2666)
	at org.hibernate.loader.custom.CustomLoader.list(CustomLoader.java:338)
	at org.hibernate.internal.SessionImpl.listCustomQuery(SessionImpl.java:2139)
	at org.hibernate.internal.AbstractSharedSessionContract.list(AbstractSharedSessionContract.java:1163)
	at org.hibernate.query.internal.NativeQueryImpl.doList(NativeQueryImpl.java:173)
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1533)
	... 98 more
```
expected would be that it's mapped also for JPASQLQuery 

## Steps to reproduce
Schema.id is type of UUID,
Schema.name is type of String.

```
QSchema qSchema = QSchema.schema;
QBean<Schema> fields = Projections.fields(Schema.class, qSchema.id, qSchema.name);

JPASQLQuery<QSchema> jpasqlQuery = new JPASQLQuery<>(entityManager, PostgreSQLTemplates.DEFAULT);
jpasqlQuery
        .select(fields)
        .from(qSchema)
        .where(qSchema.id.eq(UUID.fromString("8f2865d6-8fbb-4d61-b1bf-a31bc1eda846")));

JPAQuery<QSchema> jpaQuery = new JPAQuery<>();
jpaQuery.select(fields)
        .from(qSchema)
        .where(qSchema.id.eq(UUID.fromString("8f2865d6-8fbb-4d61-b1bf-a31bc1eda846")));
```

I tried also just simple option
```
jpasqlQuery
        .select(qSchema.id)
        .from(qSchema)
        .where(qSchema.id.eq(UUID.fromString("8f2865d6-8fbb-4d61-b1bf-a31bc1eda846")));
```

Last thing, this works:
```
JPASQLQuery<QSchema> jpasqlQuery = new JPASQLQuery<>(entityManager, PostgreSQLTemplates.DEFAULT);
jpasqlQuery
        .select(qSchema)
        .from(qSchema)
        .where(qSchema.id.eq(UUID.fromString("8f2865d6-8fbb-4d61-b1bf-a31bc1eda846")));
```
## Environment
Hibernate version 5.4.18.Final

Querydsl version: 4.4.0

Querydsl module: QueryDSL-jpa

Database: Postgresql

**Comment by jwgmeligmeyling** [comment]
In Hibernate, when doing a tuple projection in a native query, you have to specify custom type mappings through a ResultMapping.

Querydsl doesn’t use named native queries or result mappings, so I don’t think this can be supported on our side. You’d need to ask @ Hibernate if they could add type inference for native queries.

**Comment by shivamtiwari2009** [comment]
I am getting same issue how can I fix it?

**Comment by shivamtiwari2009** [comment]
Figured it out, here is complete code

```
import com.querydsl.jpa.HibernateHandler;
import javax.persistence.EntityManager;
import javax.persistence.Query;
import org.hibernate.SessionFactory;
import org.hibernate.query.NativeQuery;
import org.hibernate.type.BasicType;

public class CustomHibernateHandler extends HibernateHandler {

    private EntityManager entityManager;

    public CustomHibernateHandler(EntityManager entityManager) {
        this.entityManager = entityManager;
    }

    @Override
    public void addScalar(Query query, String alias, Class<?> type) {
        final BasicType basic = entityManager
                .getEntityManagerFactory()
                .unwrap(SessionFactory.class)
                .getTypeHelper()
                .basic(type);

        query.unwrap(NativeQuery.class).addScalar(alias, basic);
    }
}
```
Usage
```
pass entity manager here.

protected JPASQLQuery<T> getJPASQLQuery() {
    return new JPASQLQuery<>(
            entityManager,
            new Configuration(
                    PostgreSQLTemplates.builder().printSchema().build()),
            new CustomHibernateHandler(entityManager)

    );
  }
```
