### ISSUE TITLE
SQLException gets translated to null which leads to NullPointerException and loss of original exception

### ISSUE THREAD

**Issue by gavvvr** [querydsl/querydsl#2833]
I do not know exactly if it is an Oracle, Querydsl or Spring problem, but decided to submit an issue here since `NullPointerException` happens inside of QueryDsl code

## Steps to reproduce

Below is a simple query. `select '1L' from dual`. Notice that `'1L'` is not a number, it is a quoted string. Below is how I could write this query using querydsl:

```kotlin
@Test
fun `unexpectedly throws NPE on incompatible type`() {
    val num = Expressions.numberTemplate(Long::class.java, "'1L'")
    sql.select(num)
        .from(Expressions.stringTemplate("dual"))
        .fetch()
}
```

It is expected to fail since selected value is supposed to be of type `Long` while it is a quoted string. But it fails not with type incompatibility exception but with a NPE:

```
java.lang.NullPointerException
	at com.querydsl.sql.AbstractSQLQuery.fetch(AbstractSQLQuery.java:493)
	at example.QuerydslNpe.throws NPE on incompatible type(QuerydslNpeIT.kt:22)
```

## Observed vs. expected behavior

This happens because `SQLException` gets translated by `AbstractFallbackSQLExceptionTranslator` to `null`:

https://github.com/spring-projects/spring-framework/blob/b1280ffeaaa3d666606fbe92f34219303fa5bbd7/spring-jdbc/src/main/java/org/springframework/jdbc/support/AbstractFallbackSQLExceptionTranslator.java#L81-L82

and querydsl fails with NPE on attempt to `throw` translated `null`:
https://github.com/querydsl/querydsl/blob/eb32e3f162a0b7f4ae1dc013bd1eb0d5ea977819/querydsl-sql/src/main/java/com/querydsl/sql/AbstractSQLQuery.java#L491-L493

## Environment

Querydsl version: 4.4.0 (latest)

Querydsl module: querydsl-sql

Database: Oracle 11

JDK: 1.8

## Additional details

Where does `null` come from?

```
null gets returned from org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:82)
	at com.querydsl.sql.spring.SpringExceptionTranslator.translate(SpringExceptionTranslator.java:49)
	at com.querydsl.sql.Configuration.translate(Configuration.java:508)
	at com.querydsl.sql.AbstractSQLQuery.fetch(AbstractSQLQuery.java:493)
	at example.QuerydslNpe.throws NPE on incompatible type(QuerydslNpeIT.kt:22)
```

**Comment by gavvvr** [comment]
In case I initialise `SQLQueryFactory` with a simple `Provider<Connection>` there is no problem and exception gets correctly translated to `com.querydsl.core.QueryException`.

But in my Spring app I use `SpringConnectionProvider` wrapping `HikariDataSource` which leads to described NPE

**Comment by Tarrowren** [comment]
The problem is here at `org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate`
```java
Configuration configuration = new Configuration(templates);
configuration.setExceptionTranslator(new SpringExceptionTranslator());

```

```java
public class SpringExceptionTranslator implements com.querydsl.sql.SQLExceptionTranslator {

    private final SQLExceptionTranslator translator;

    public SpringExceptionTranslator() {
        this.translator = new SQLStateSQLExceptionTranslator();
    }

    ...
}

```

```java
public class SQLStateSQLExceptionTranslator extends AbstractFallbackSQLExceptionTranslator {

    @Override
    @Nullable
    protected DataAccessException doTranslate(String task, @Nullable String sql, SQLException ex) {
        // First, the getSQLState check...
        String sqlState = getSqlState(ex);
        if (sqlState != null && sqlState.length() >= 2) {
            String classCode = sqlState.substring(0, 2);
            if (logger.isDebugEnabled()) {
                logger.debug("Extracted SQL state class '" + classCode + "' from value '" + sqlState + "'");
            }
            if (BAD_SQL_GRAMMAR_CODES.contains(classCode)) {
                return new BadSqlGrammarException(task, (sql != null ? sql : ""), ex);
            ...
        }

        // For MySQL: exception class name indicating a timeout?
        // (since MySQL doesn't throw the JDBC 4 SQLTimeoutException)
        if (ex.getClass().getName().contains("Timeout")) {
            return new QueryTimeoutException(buildMessage(task, sql, ex), ex);
        }

        // Couldn't resolve anything proper - resort to UncategorizedSQLException.
        return null;
    }

    ...
}

```

fix it
```java
public class Hello extends SQLStateSQLExceptionTranslator {

    @Override
    protected DataAccessException doTranslate(String task, String sql, SQLException ex) {
        DataAccessException e = super.doTranslate(task, sql, ex);

        if (e != null) {
            return e;
        }

        return new UncategorizedSQLException(task, sql, ex);
    }
}

```

```java
Configuration configuration = new Configuration(templates);
configuration.setExceptionTranslator(new SpringExceptionTranslator(new Hello()));

```
