### ISSUE TITLE
Unknown column 'count_total_cursos' in 'having clause'

### ISSUE THREAD

**Issue by macario1983** [querydsl/querydsl#2990]
## Observed vs. expected behavior

I am trying to execute this query

```
    private List<FindMeuPercursoTemaTransient> findTemas(Long profissionalId, Long marcaId, Long funcaoPrincipalId, List<Long> funcoesTransientIds) {

        JPAQuery<FindMeuPercursoTemaTransient> query = new JPAQuery<>(entityManager);

        NumberPath<Long> aliasCountTotalCursos = Expressions.numberPath(Long.class, "count_total_cursos");
        NumberPath<Long> aliasSumCursosConcluidos = Expressions.numberPath(Long.class, "sum_total_cursos_concluidos");
        NumberPath<Integer> aliasCaseTemaFuncaoPrincipal = Expressions.numberPath(Integer.class, "case_tema_funcao_principal");

        NumberExpression<Long> countTotalCursos = getCountTotalCursos();
        NumberExpression<Long> sumCursosConcluidos = getSumCursosConcluidos();
        NumberExpression<Integer> caseTemaFuncaoPrincipal = getCaseTemaFuncaoPrincipal(funcaoPrincipalId);

        query.select(Projections.constructor(
                        FindMeuPercursoTemaTransient.class,
                        qTema.id,
                        qTema.nome,
                        qTema.imagemCapaIdIntegracao,
                        countTotalCursos.as(aliasCountTotalCursos),
                        sumCursosConcluidos.as(aliasSumCursosConcluidos),
                        caseTemaFuncaoPrincipal.as(aliasCaseTemaFuncaoPrincipal)))
                .from(qTema)
                .innerJoin(qTema.cursos, qCursoTema)
                .innerJoin(qCursoTema.curso, qCurso)
                .innerJoin(qCurso.apresentacoes, qApresentacao)
                .innerJoin(qApresentacao.disponibilidade, qDisponibilidadeApresentacao)
                .leftJoin(qCurso.realizacoesCurso, qRealizacaoCurso)
                .innerJoin(qRealizacaoCurso.profissional, qProfissional).on(qProfissional.id.eq(profissionalId))
                .where(getWhere(marcaId, funcoesTransientIds))
                .groupBy(qTema.id, qTema.nome, qTema.imagemCapaIdIntegracao)
                .having(aliasCountTotalCursos.gt(aliasSumCursosConcluidos))
                .orderBy(aliasCaseTemaFuncaoPrincipal.desc(), qTema.dataCriacao.asc(), qTema.nome.asc())
                .distinct()
                .limit(LIMITE_TEMAS);

        return query.fetch();
    }

    private NumberExpression<Long> getCountTotalCursos() {
        return qCurso.id.countDistinct();
    }

    private NumberExpression<Long> getSumCursosConcluidos() {
        return new CaseBuilder()
                .when(qRealizacaoCurso.id.isNotNull()
                        .and(qRealizacaoCurso.statusAprovacao.eq(StatusAprovacaoCursoEnum.APROVADO)))
                .then(1L)
                .otherwise(0L)
                .sum();
    }

    private NumberExpression<Integer> getCaseTemaFuncaoPrincipal(Long funcaoPrincipalId) {
        return new CaseBuilder()
                .when(qTema.funcaoIdIntegracao.eq(funcaoPrincipalId))
                .then(1)
                .otherwise(0);
    }
```

It gerenates in JPAQuery this:

```
SELECT DISTINCT tema.id,
                tema.nome,
                tema.imagemCapaIdIntegracao,
                count(DISTINCT curso.id) AS count_total_cursos,
                sum(CASE WHEN (realizacaoCurso.id IS NOT NULL
                               AND realizacaoCurso.statusAprovacao = ?1) THEN ?2 ELSE 0 END) AS sum_total_cursos_concluidos,
                (CASE
                     WHEN (tema.funcaoIdIntegracao = ?3) THEN ?4
                     ELSE 0
                 END) AS case_tema_funcao_principal
FROM Tema tema
INNER JOIN tema.cursos AS cursoTema
INNER JOIN cursoTema.curso AS curso
INNER JOIN curso.apresentacoes AS apresentacao
INNER JOIN apresentacao.disponibilidade AS disponibilidadeApresentacao
LEFT JOIN curso.realizacoesCurso AS realizacaoCurso
INNER JOIN realizacaoCurso.profissional AS profissional WITH profissional.id = ?5
WHERE tema.marcaIdIntegracao = ?6
  AND tema.funcaoIdIntegracao IN (?7)
  AND tema.tipo = ?8
  AND tema.tipoUnidadeNegocio IS NULL
  AND disponibilidadeApresentacao.marcaIdIntegracao = ?6
  AND (disponibilidadeApresentacao.funcaoIdIntegracao IS NULL
       OR disponibilidadeApresentacao.funcaoIdIntegracao IN (?7))
  AND cursoTema.dataInicioVigente < ?9
  AND (cursoTema.dataTerminoVigente IS NULL
       OR cursoTema.dataTerminoVigente > ?9)
  AND tema.categoriaTema = ?10
GROUP BY tema.id,
         tema.nome,
         tema.imagemCapaIdIntegracao HAVING count_total_cursos > sum_total_cursos_concluidos
ORDER BY case_tema_funcao_principal DESC,
         tema.dataCriacao ASC,
         tema.nome ASC
```

 But the output in console is:

```
SELECT DISTINCT tema0_.id AS col_0_0_,
                tema0_.nome AS col_1_0_,
                tema0_.imagem_capa_id_integracao AS col_2_0_,
                count(DISTINCT curso2_.id) AS col_3_0_,
                sum(CASE WHEN (realizacoe5_.id IS NOT NULL)
                    AND realizacoe5_.status_aprovacao=? THEN ? ELSE 0 END) AS col_4_0_,
                CASE
                    WHEN tema0_.funcao_id_integracao=? THEN ?
                    ELSE 0
                END AS col_5_0_
FROM tema tema0_
INNER JOIN curso_tema cursos1_ ON tema0_.id=cursos1_.tema_id
INNER JOIN curso curso2_ ON cursos1_.curso_id=curso2_.id
INNER JOIN apresentacao apresentac3_ ON curso2_.id=apresentac3_.curso_id
INNER JOIN disponibilidade_apresentacao disponibil4_ ON apresentac3_.id=disponibil4_.apresentacao_id
LEFT OUTER JOIN realizacao_curso realizacoe5_ ON curso2_.id=realizacoe5_.curso_id
INNER JOIN profissional profission6_ ON realizacoe5_.profissional_id=profission6_.id
AND (profission6_.id=?)
WHERE tema0_.marca_id_integracao=?
  AND (tema0_.funcao_id_integracao IN (? ,
                                       ?))
  AND tema0_.tipo=?
  AND (tema0_.tipo_unidade_negocio IS NULL)
  AND disponibil4_.marca_id_integracao=?
  AND (disponibil4_.funcao_id_integracao IS NULL
       OR disponibil4_.funcao_id_integracao IN (? ,
                                                ?))
  AND cursos1_.data_inicio_vigente<?
  AND (cursos1_.data_termino_vigente IS NULL
       OR cursos1_.data_termino_vigente>?)
  AND tema0_.categoria_tema=?
GROUP BY tema0_.id ,
         tema0_.nome ,
         tema0_.imagem_capa_id_integracao HAVING count_total_cursos>sum_total_cursos_concluidos
ORDER BY col_5_0_ DESC,
         tema0_.data_criacao ASC,
         tema0_.nome ASC LIMIT ?
```

And gave me a error:

```
[localhost] 2021-08-04 15:50:23 - SQL Error: 1054, SQLState: 42S22
[localhost] 2021-08-04 15:50:23 - Unknown column 'count_total_cursos' in 'having clause'
[localhost] 2021-08-04 15:50:23 - Ocorreu um erro inesperado! 
 ExceptionType: class javax.persistence.PersistenceException 
 ExceptionMessage: org.hibernate.exception.SQLGrammarException: could not extract ResultSet 
```

## Steps to reproduce

Trying to execute the JpaQuery but not works.

## Environment

OS: Manjaro
Database: Docker Mysql 5.7.31

Querydsl version:

4.2.1

Database: Mysql 

JDK: 1.8

**Comment by jwgmeligmeyling** [comment]
Please retest on Querydsl 5.0.0. Querydsl 4.2.1 is no longer maintained.

**Comment by macario1983** [comment]
@jwgmeligmeyling, updated the version, but not worked. Still getting the same error.

```
Hibernate: select distinct tema0_.id as col_0_0_, tema0_.nome as col_1_0_, tema0_.imagem_capa_id_integracao as col_2_0_, count(distinct curso2_.id) as col_3_0_, sum(case when (realizacoe5_.id is not null) and realizacoe5_.status_aprovacao=? then ? else 0 end) as col_4_0_, case when tema0_.funcao_id_integracao=? then ? else 0 end as col_5_0_ from tema tema0_ inner join curso_tema cursos1_ on tema0_.id=cursos1_.tema_id inner join curso curso2_ on cursos1_.curso_id=curso2_.id inner join apresentacao apresentac3_ on curso2_.id=apresentac3_.curso_id inner join disponibilidade_apresentacao disponibil4_ on apresentac3_.id=disponibil4_.apresentacao_id left outer join realizacao_curso realizacoe5_ on curso2_.id=realizacoe5_.curso_id inner join profissional profission6_ on realizacoe5_.profissional_id=profission6_.id and (profission6_.id=?) where tema0_.marca_id_integracao=? and (tema0_.funcao_id_integracao in (? , ?)) and tema0_.tipo=? and (tema0_.tipo_unidade_negocio is null) and disponibil4_.marca_id_integracao=? and (disponibil4_.funcao_id_integracao is null or disponibil4_.funcao_id_integracao in (? , ?)) and cursos1_.data_inicio_vigente<? and (cursos1_.data_termino_vigente is null or cursos1_.data_termino_vigente>?) and tema0_.categoria_tema=? group by tema0_.id , tema0_.nome , tema0_.imagem_capa_id_integracao having count_total_cursos>sum_total_cursos_concluidos order by col_5_0_ desc, tema0_.data_criacao asc, tema0_.nome asc limit ?
[localhost] 2021-08-04 21:13:56 - SQL Error: 1054, SQLState: 42S22
[localhost] 2021-08-04 21:13:56 - Unknown column 'count_total_cursos' in 'having clause'
[localhost] 2021-08-04 21:14:00 - Ocorreu um erro inesperado! 
 ExceptionType: class javax.persistence.PersistenceException 
 ExceptionMessage: org.hibernate.exception.SQLGrammarException: could not extract ResultSet 
 StackTrace: 
javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1535)
	at org.hibernate.query.Query.getResultList(Query.java:165)
	at com.querydsl.jpa.impl.AbstractJPAQuery.getResultList(AbstractJPAQuery.java:191)
	at com.querydsl.jpa.impl.AbstractJPAQuery.fetch(AbstractJPAQuery.java:243)
	at isvor.ldap.academicoapi.application.handler.v2.home_default.FindTemaMeuPercursoHandler.findTemas(FindTemaMeuPercursoHandler.java:145)
	at isvor.ldap.academicoapi.application.handler.v2.home_default.FindTemaMeuPercursoHandler.handle(FindTemaMeuPercursoHandler.java:100)
	at isvor.ldap.academicoapi.application.handler.v2.home_default.FindTemaMeuPercursoHandler.handle(FindTemaMeuPercursoHandler.java:43)
	at isvor.ldap.academicoapi.application.handler.v2.home_default.FindTemaMeuPercursoHandler$$FastClassBySpringCGLIB$$44e4509d.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at net.bull.javamelody.MonitoringSpringInterceptor.invoke(MonitoringSpringInterceptor.java:76)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at isvor.ldap.academicoapi.application.handler.v2.home_default.FindTemaMeuPercursoHandler$$EnhancerBySpringCGLIB$$d37f7f5f.handle(<generated>)
	at isvor.ldap.core.mediator.MediatorImpl.send(MediatorImpl.java:77)
	at isvor.ldap.core.mediator.MediatorImpl$$FastClassBySpringCGLIB$$1208f607.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at net.bull.javamelody.MonitoringSpringInterceptor.invoke(MonitoringSpringInterceptor.java:76)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at isvor.ldap.core.mediator.MediatorImpl$$EnhancerBySpringCGLIB$$24da6f3e.send(<generated>)
	at isvor.ldap.academicoapi.web.controller.v2.HomeDefaultController.findMeuPercurso(HomeDefaultController.java:68)
	at isvor.ldap.academicoapi.web.controller.v2.HomeDefaultController$$FastClassBySpringCGLIB$$4b09b110.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at isvor.ldap.core.security.SecurityInterceptor.around(SecurityInterceptor.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.cache.interceptor.CacheInterceptor.lambda$invoke$0(CacheInterceptor.java:53)
	at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:365)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:420)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:345)
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at net.bull.javamelody.MonitoringSpringInterceptor.invoke(MonitoringSpringInterceptor.java:76)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at isvor.ldap.academicoapi.web.controller.v2.HomeDefaultController$$EnhancerBySpringCGLIB$$20895a39.findMeuPercurso(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:199)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:239)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:215)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:108)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at isvor.ldap.core.security.CorsFilter.doFilter(CorsFilter.java:50)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1579)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:63)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:67)
	at org.hibernate.loader.Loader.getResultSet(Loader.java:2292)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2050)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2012)
	at org.hibernate.loader.Loader.doQuery(Loader.java:953)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:354)
	at org.hibernate.loader.Loader.doList(Loader.java:2815)
	at org.hibernate.loader.Loader.doList(Loader.java:2797)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2629)
	at org.hibernate.loader.Loader.list(Loader.java:2624)
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:506)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:396)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:219)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1396)
	at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1558)
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1526)
	... 127 common frames omitted
Caused by: java.sql.SQLSyntaxErrorException: Unknown column 'count_total_cursos' in 'having clause'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.bull.javamelody.JdbcWrapper.doExecute(JdbcWrapper.java:422)
	at net.bull.javamelody.JdbcWrapper$StatementInvocationHandler.invoke(JdbcWrapper.java:142)
	at net.bull.javamelody.JdbcWrapper$DelegatingInvocationHandler.invoke(JdbcWrapper.java:300)
	at com.sun.proxy.$Proxy238.executeQuery(Unknown Source)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:57)
	... 142 common frames omitted
[localhost] 2021-08-04 21:14:00 - Resolved [javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet]
[] 2021-08-04 21:14:01 - HikariPool-1 - Before cleanup stats (total=2, active=0, idle=2, waiting=0)
[] 2021-08-04 21:14:01 - HikariPool-1 - After cleanup  stats (total=2, active=0, idle=2, waiting=0)
[] 2021-08-04 21:14:31 - HikariPool-1 - Before cleanup stats (total=2, active=0, idle=2, waiting=0)
[] 2021-08-04 21:14:31 - HikariPool-1 - After cleanup  stats (total=2, active=0, idle=2, waiting=0)
[] 2021-08-04 21:15:01 - HikariPool-1 - Before cleanup stats (total=2, active=0, idle=2, waiting=0)
[] 2021-08-04 21:15:01 - HikariPool-1 - After cleanup  stats (total=2, active=0, idle=2, waiting=0)
[] 2021-08-04 21:15:31 - HikariPool-1 - Before cleanup stats (total=2, active=0, idle=2, waiting=0)
[] 2021-08-04 21:15:31 - HikariPool-1 - After cleanup  stats (total=2, active=0, idle=2, waiting=0)

```

**Comment by jwgmeligmeyling** [comment]
Querydsl generates the "right" JPQL. It is your ORM (in this case Hibernate) thats responsible for rendering the SQL, which is where the fault lies in this case. The problem is that you try to reference an alias in the having clause, which although allowed in some SQL languages, is not allowed in ANSI SQL nor in JPQL. The work around is to reuse the underlying expression instead of the alias instead.

I think it can be extended in Hibernate fairly easy, as I've already shown for grouping by alias for supporting dialects: https://github.com/hibernate/hibernate-orm/pull/3022

It could be worthwhile to upgrade Hibernate to the newest version and see if it makes a difference.
