### ISSUE TITLE
Connection leak when using FetchableQueryBase#transform outside of a transaction

### ISSUE THREAD

**Issue by schosin** [querydsl/querydsl#3089]
## Observed vs. expected behavior

When using `FetchableQueryBase#transform` without an active transaction, `HibernateHandler#iterate` creates a connection by calling `Query.scroll(ScrollMode)`. This connection is never returned to a configured HikariCP pool and causes a connection leak.

This problem is not present when using `AbstractJPAQuery#fetch`.

## Steps to reproduce

https://github.com/schosin/QueryDslTransformConnectionLeak

Run the tests or start the application and use http://localhost:8080/active to check the connections and call http://localhost:8080/transactional, http://localhost:8080/txtemplate and http://localhost:8080/notransaction to see changes.

## Environment

Querydsl version: 4.4.0

Querydsl module: JPA

Database: H2, MSSQL, MySQL 5.7.x

JDK: 11, 16, 17

## Additional details

Related to #2291.

**Comment by mychalvlcek** [comment]
I have similar issue.. after upgrade from Springboot 2.5.6 to 2.6.1..

- querydsl was updated from 4.3.1 --> 5.0.0
- hibernate-core 5.4.32 --> 5.6.1

usage of `.transform()` leads to leak

```java
java.lang.Exception: Apparent connection leak detected
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
	at org.springframework.jdbc.datasource.lookup.AbstractRoutingDataSource.getConnection(AbstractRoutingDataSource.java:194)
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)
	at org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:38)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:108)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:138)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.connection(StatementPreparerImpl.java:50)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:149)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:176)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:151)
	at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:2122)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2059)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2037)
	at org.hibernate.loader.Loader.scroll(Loader.java:2945)
	at org.hibernate.loader.hql.QueryLoader.scroll(QueryLoader.java:610)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.scroll(QueryTranslatorImpl.java:452)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performScroll(HQLQueryPlan.java:353)
	at org.hibernate.internal.SessionImpl.scroll(SessionImpl.java:1610)
	at org.hibernate.query.internal.AbstractProducedQuery.doScroll(AbstractProducedQuery.java:1588)
	at org.hibernate.query.internal.AbstractProducedQuery.scroll(AbstractProducedQuery.java:1574)
	at org.hibernate.query.internal.AbstractProducedQuery.scroll(AbstractProducedQuery.java:122)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.orm.jpa.SharedEntityManagerCreator$DeferredQueryInvocationHandler.invoke(SharedEntityManagerCreator.java:406)
	at com.sun.proxy.$Proxy494.scroll(Unknown Source)
	at com.querydsl.jpa.HibernateHandler.iterate(HibernateHandler.java:60)
	at com.querydsl.jpa.impl.AbstractJPAQuery.iterate(AbstractJPAQuery.java:222)
	at com.querydsl.core.group.GroupByMap.transform(GroupByMap.java:54)
	at com.querydsl.core.group.GroupByMap.transform(GroupByMap.java:35)
	at com.querydsl.core.support.FetchableQueryBase.transform(FetchableQueryBase.java:55)
```

**Comment by mat-mik** [comment]
Thanks for report, we ran in exactly same issue upgrading `4.3.1` to `4.4.0`. We also checked that leak is present on version `5.0.0` as well! 

To reproduce just take @schosin's code, upgrade QueryDSL to `5.0.0` and call `GET /notransaction`. Leak is present in exactly the same place.

**Comment by valentin-braun** [comment]
We are experiencing the same behavior of leaking connections when trying to upgrade `4.3.1` to `4.4.0`. The leak also exist in `5.0.0`. A bugfix is highly appreciated.

**Comment by valentin-braun** [comment]
@jwgmeligmeyling 

We are currently blocked by this bug and are not able to upgrade to `4.4.0` or `5.0.0`. Is there any chance to get a fix for this important bug? 

As @mychalvlcek has already figured out, maybe it is a feasible way to just revert the changes made in `HibernateHandler` (see https://github.com/querydsl/querydsl/commit/8cd82e879271a10afbeb3ac808c3a22e81d5d2fc)?

**Comment by jwgmeligmeyling** [comment]
I don't think this is a Querydsl bug.

Yes, `transform` uses `iterate` under the hood. This returns a `CloseableIterator`. The `CloseableIterator` delegates the close call to the `ScrollableResultSet`. Querydsl expects the ORM to close all resources when it closes the Iterator/ScrollableResultSet.

Querydsl does not start a connection when no transaction is active, rather Hibernate does so. Therefore its not Querydsl's  responsibility to close the transaction, rather its Hibernates. I think the "bug" is here, that Hibernate doesn't close its connection when the `CloseableIterator` is closed.

The only reason why this worked before, is because the Hibernate handler didn't work at all and the `ScrollableResultSet` wasn't used at all. So instead of streaming it would fall back to `.list().iterator()`.

I'd suggest reporting the issue to Hibernate.

In the meanwhile, probably best to make all methods doing queries `@Transactional`.

**Comment by valentin-braun** [comment]
Thanks a lot for the quick reply and your advices. 👍 I'll have a look.

**Comment by jwgmeligmeyling** [comment]
Thanks! If it turns out to be possible, I am willing to fix it here. But from looking at the code I don't really see how to close the connection.

Can you try with the `JPAHandler` instead of the `HibernateHandler`?

```
new JPAQueryFactory(JPQLTemplates.DEFAULT, entityManager)
```

Or 


```
new JPAQuery(JPQLTemplates.DEFAULT, entityManager)
```

This uses the `DefaultQueryHandler` instead of the `HibernateHandler` which also uses `.list().iterator()` instead of `.getResultStream().iterator()`.

**Comment by KammererTob** [comment]
Just a heads up: I have investigated a bit and found a more minimal example of this leak happening. Although i am not sure if it really is Hibernate or Spring, it definitely does not seem to be related to the code in Querydsl. I've opened a question on Stackoverflow before opening an issue in the Hibernate issue tracker, just to make sure that i am not doing anything wrong.

Here is the post:
https://stackoverflow.com/questions/76008518/spring-hibernate-connection-leak-with-scrollableresults

And i will update this post if/once i've opened in issue in Hibernate as well.

**Comment by KammererTob** [comment]
I continued to investigate and have a bit more information. At least in regards to how Spring works. I am not entirely sure where to go from here, tho.
Spring's `EntityManager` proxies all calls to the actual `EntityManager` and if the result of a call implements the `Query` interface it will proxy that object as well. 
In there it has something it calls `queryTerminatingMethods`, which are methods on the Query interface that are terminating. It will automatically close the shared `EntityManager` after the invocation. This is the list:

```
	private static final Set<String> queryTerminatingMethods = Set.of(
			"execute",  // jakarta.persistence.StoredProcedureQuery.execute()
			"executeUpdate", // jakarta.persistence.Query.executeUpdate()
			"getSingleResult",  // jakarta.persistence.Query.getSingleResult()
			"getResultStream",  // jakarta.persistence.Query.getResultStream()
			"getResultList",  // jakarta.persistence.Query.getResultList()
			"list",  // org.hibernate.query.Query.list()
			"stream",  // org.hibernate.query.Query.stream()
			"uniqueResult",  // org.hibernate.query.Query.uniqueResult()
			"uniqueResultOptional"  // org.hibernate.query.Query.uniqueResultOptional()
		);
```

so for "normal" queries it will automatically clean up afterwards, but since ´scroll` is not terminating it will not do that. This is the reason why a normal `fetch` works without @Transactional. Obviously querydsl can use any `EntityManager` implementation and not only the one supplied by Spring, so this is only one half of the puzzle. 
I think this is as far as i can help since i am not very versed in how that is supposed to work for other implementation. You obviously cannot just start a transaction in querydsl since the provided `EntityManager` from Spring will throw a Exception if you call `getTransaction()`.
One "solution" might be to change all the `transforms`, which are the only places `iterate` is used (if i am not mistaken), to use `getResultStream` instead. This would at least fix the issue for Spring, but i am not sure if this isn't a deeper issue.

**Comment by jwgmeligmeyling** [comment]
The only difference between the Hibernate handler and the regular JPA handler, is that it uses `ScrollableResultSet` over `Query.getResultStream` so that it can support Hibernate <= 5 on Java < 8. If you're using a modern version of Hibernate, you can just use the `DefaultQueryHandler`.  I think that would solve the closing issue then too.  Did you end up trying https://github.com/querydsl/querydsl/issues/3089#issuecomment-1486593397 ?

**Comment by KammererTob** [comment]
The `DefaultQueryHandler` seems to work fine for Hibernate 5.6.9.Final on Java 8, without a transaction around transform. Thanks!

**Comment by UserNotFoundErrorException** [comment]
new JPAQueryFactory(JPQLTemplates.DEFAULT, entityManager) leads to `Cannot invoke "org.hibernate.type.Type.sqlTypes(org.hibernate.engine.spi.Mapping)" because "type" is null` for queries that uses "when-then-sum".

**Comment by valentin-braun** [comment]
As a workaround, we finally make use of `new JPAQueryFactory(JPQLTemplates.DEFAULT, entityManager)` and set  `@Transactional` for all the methods doing queries.

**Environment**
Querydsl: 5.1.0
JDK: 17
Spring: 6.0.19
Hibernate: 6.5.1.Final
Database: Oracle
