### ISSUE TITLE
when I delete data with querydsl-jpa, throw javax.persistence.TransactionRequiredException: Executing an update/delete query

### ISSUE THREAD

**Issue by loujiaye** [querydsl/querydsl#3136]
## Observed vs. expected behavior

when I delete data with querydsl-jpa, throw javax.persistence.TransactionRequiredException: Executing an update/delete query
```java
javax.persistence.TransactionRequiredException: Executing an update/delete query
        at org.hibernate.internal.AbstractSharedSessionContract.checkTransactionNeededForUpdateOperation(AbstractSharedSessionContract.java:422)
        at org.hibernate.query.internal.AbstractProducedQuery.executeUpdate(AbstractProducedQuery.java:1668)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.orm.jpa.SharedEntityManagerCreator$DeferredQueryInvocationHandler.invoke(SharedEntityManagerCreator.java:406)
        at com.sun.proxy.$Proxy226.executeUpdate(Unknown Source)
        at com.querydsl.jpa.impl.JPADeleteClause.execute(JPADeleteClause.java:70)
        at cn.sm.data.hanoispring.schedulerx.ImportDayIndicatorProcessor.clearData(ImportDayIndicatorProcessor.java:134)
        at cn.sm.data.hanoispring.schedulerx.BaseImportProcessor.runTask(BaseImportProcessor.java:58)
        at cn.sm.data.hanoispring.schedulerx.BaseImportProcessor.process(BaseImportProcessor.java:43)
        at com.alibaba.schedulerx.worker.container.ThreadContainer.start(ThreadContainer.java:91)
        at com.alibaba.schedulerx.worker.container.ThreadContainer.run(ThreadContainer.java:59)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

### QuerydslConfig.java.   create JPAQueryFactory
```java
package cn.sm.data.hanoispring.configure;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import com.querydsl.jpa.impl.JPAQueryFactory;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Describe class QuerydslConfig here.
 *
 *
 * Created: Wed Dec 22 19:14:14 2021
 *
 * @author <a href="mailto:tom.wy@alibaba-inc.com">wangyu</a>
 * @version 1.0
 */
@Configuration
public class QuerydslConfig {
    @Autowired
    @PersistenceContext
    private EntityManager entityManager;
    
    @Bean
    public JPAQueryFactory getJPAQueryFactory(){
        
        return new JPAQueryFactory(entityManager);
    }
}
```
### ScIndicator.java Entity
ScIndicatorPK is Identity
```java
@Entity(name = "sc_indicator")
public class ScIndicator {
    @EmbeddedId
    private ScIndicatorPK pk;

   ... other field and getter/setter...
```

### ImportDayIndicatorProcessor.java   
here, when i call method delete scIndicator, it throw Exception
```java
@Component
@Scope("prototype")
public class ImportDayIndicatorProcessor extends BaseImportProcessor {
    protected final String partitionPattern = "yyyy-MM-dd 00:00:00";
    protected Set<ScIndicator> scIndicators = new HashSet<>();

    @Autowired
    private ScIndicatorRepository scIndicatorRepository;
    
    @Autowired
    private JPAQueryFactory queryFactory;

    @Override
    @Transactional     
    protected long clearData(Date time) {
        QScIndicator qScIndicator = QScIndicator.scIndicator;

        long num = queryFactory.delete(qScIndicator)
            .where(qScIndicator.pk.time.eq(time).and(qScIndicator.pk.timeType.eq(TimeType.DAY)))
            .execute();
		return num;
      }
   ... other method...
```
### error log
```
javax.persistence.TransactionRequiredException: Executing an update/delete query
        at org.hibernate.internal.AbstractSharedSessionContract.checkTransactionNeededForUpdateOperation(AbstractSharedSessionContract.java:422)
        at org.hibernate.query.internal.AbstractProducedQuery.executeUpdate(AbstractProducedQuery.java:1668)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.orm.jpa.SharedEntityManagerCreator$DeferredQueryInvocationHandler.invoke(SharedEntityManagerCreator.java:406)
        at com.sun.proxy.$Proxy226.executeUpdate(Unknown Source)
        at com.querydsl.jpa.impl.JPADeleteClause.execute(JPADeleteClause.java:70)
        at cn.sm.data.hanoispring.schedulerx.ImportDayIndicatorProcessor.clearData(ImportDayIndicatorProcessor.java:134)
        at cn.sm.data.hanoispring.schedulerx.BaseImportProcessor.runTask(BaseImportProcessor.java:58)
        at cn.sm.data.hanoispring.schedulerx.BaseImportProcessor.process(BaseImportProcessor.java:43)
        at com.alibaba.schedulerx.worker.container.ThreadContainer.start(ThreadContainer.java:91)
        at com.alibaba.schedulerx.worker.container.ThreadContainer.run(ThreadContainer.java:59)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

## Environment

Querydsl version: 4.4.0

Querydsl module: querydsl-jpa

Database: mysql

JDK: java8

## Additional details

dependency tree

```
-*- mode: compilation; default-directory: "~/program/web/hanoi-spring/" -*-
Compilation started at Wed Dec 22 21:05:19

mvn dependency:tree
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------------< cn.sm.data:hanoi-spring >-----------------------
[INFO] Building hanoi-spring 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ hanoi-spring ---
[WARNING] The artifact xml-apis:xml-apis:jar:2.0.2 has been relocated to xml-apis:xml-apis:jar:1.0.b2
[INFO] cn.sm.data:hanoi-spring:jar:1.0.0-SNAPSHOT
[INFO] +- org.springframework.boot:spring-boot-starter-actuator:jar:2.4.3:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter:jar:2.4.3:compile
[INFO] |  |  +- org.springframework.boot:spring-boot:jar:2.4.3:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-logging:jar:2.4.3:compile
[INFO] |  |  |  +- ch.qos.logback:logback-classic:jar:1.2.3:compile
[INFO] |  |  |  |  \- ch.qos.logback:logback-core:jar:1.2.3:compile
[INFO] |  |  |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.13.3:compile
[INFO] |  |  |  |  \- org.apache.logging.log4j:log4j-api:jar:2.13.3:compile
[INFO] |  |  |  \- org.slf4j:jul-to-slf4j:jar:1.7.30:compile
[INFO] |  |  +- jakarta.annotation:jakarta.annotation-api:jar:1.3.5:compile
[INFO] |  |  \- org.yaml:snakeyaml:jar:1.27:compile
[INFO] |  +- org.springframework.boot:spring-boot-actuator-autoconfigure:jar:2.4.3:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-actuator:jar:2.4.3:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.11.4:compile
[INFO] |  |  \- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.11.4:compile
[INFO] |  \- io.micrometer:micrometer-core:jar:1.6.4:compile
[INFO] |     +- org.hdrhistogram:HdrHistogram:jar:2.1.12:compile
[INFO] |     \- org.latencyutils:LatencyUtils:jar:2.0.3:runtime
[INFO] +- com.alibaba.boot:infrastructure-spring-boot-starters:jar:2.4.3.2.M2:compile
[INFO] |  +- com.alibaba.boot:diamond-spring-boot-starter:jar:3.9.0:compile
[INFO] |  |  +- com.alibaba.boot:alibaba-spring-boot:jar:2.4.3.2.M2:compile
[INFO] |  |  |  \- com.alibaba.alimonitor:alimonitor-jmonitor:jar:1.3.2:compile
[INFO] |  |  +- com.taobao.middleware:logger.api:jar:0.2.5.1-SETLEVEL:compile
[INFO] |  |  |  +- com.taobao.middleware:logger.core:jar:0.2.5.1-SETLEVEL:compile
[INFO] |  |  |  \- com.taobao.middleware:logger.pandolet:jar:0.2.5.1-SETLEVEL:compile
[INFO] |  |  +- org.springframework.cloud:spring-cloud-starter-config:jar:3.0.2:compile
[INFO] |  |  |  \- org.springframework.cloud:spring-cloud-starter:jar:3.0.1:compile
[INFO] |  |  |     +- org.springframework.cloud:spring-cloud-context:jar:3.0.1:compile
[INFO] |  |  |     |  \- org.springframework.security:spring-security-crypto:jar:5.4.5:compile
[INFO] |  |  |     +- org.springframework.cloud:spring-cloud-commons:jar:3.0.1:compile
[INFO] |  |  |     \- org.springframework.security:spring-security-rsa:jar:1.0.9.RELEASE:compile
[INFO] |  |  |        \- org.bouncycastle:bcpkix-jdk15on:jar:1.64:compile
[INFO] |  |  |           \- org.bouncycastle:bcprov-jdk15on:jar:1.64:compile
[INFO] |  |  \- com.fasterxml.jackson.dataformat:jackson-dataformat-xml:jar:2.11.4:compile
[INFO] |  |     +- org.codehaus.woodstox:stax2-api:jar:4.2.1:compile
[INFO] |  |     \- com.fasterxml.woodstox:woodstox-core:jar:6.2.3:compile
[INFO] |  +- com.alibaba.boot:eagleeye-spring-boot-starter:jar:1.9.2.1.1:compile
[INFO] |  |  +- javax.servlet:javax.servlet-api:jar:4.0.1:compile
[INFO] |  |  +- com.alibaba.middleware:eagleeye-sdk:jar:1.8.1:compile
[INFO] |  |  |  \- com.alibaba.middleware:healthcheck-api:jar:1.1:compile
[INFO] |  |  +- com.alibaba.security:security-spring-boot-starter:jar:2.1.4-SNAPSHOT:compile
[INFO] |  |  |  \- com.alibaba.security:security-spring-webmvc:jar:2.1.4-SNAPSHOT:compile
[INFO] |  |  |     +- com.alibaba.security:securitysdk-logging-api:jar:0.1.1-SNAPSHOT:compile
[INFO] |  |  |     |  \- com.alibaba.security:securitysdk-util:jar:0.1.1-SNAPSHOT:compile
[INFO] |  |  |     |     \- com.alibaba.security:typesafe-config-shade:jar:1.3.3-jdk7:compile
[INFO] |  |  |     +- com.alibaba.security:security-all:jar:2.0.5-SNAPSHOT:compile
[INFO] |  |  |     |  +- com.alibaba.security:security-facade:jar:2.0.5.9:compile
[INFO] |  |  |     |  +- com.alibaba.security:security-interface:jar:2.0.5.9:compile
[INFO] |  |  |     |  +- com.alibaba.security:security-core:jar:2.0.5.9:compile
[INFO] |  |  |     |  |  +- com.alibaba.security:securitysdk-resource:jar:0.1.1-SNAPSHOT:compile
[INFO] |  |  |     |  |  |  \- com.alibaba.security:securitysdk-circuit-breaker:jar:0.1.1-SNAPSHOT:compile
[INFO] |  |  |     |  |  +- com.alibaba.security:security-css:jar:2.0.5.9:compile
[INFO] |  |  |     |  |  +- com.alibaba.securitysdk:nekohtml:jar:1.9.22.r1:compile
[INFO] |  |  |     |  |  |  \- com.alibaba.securitysdk:xerces:jar:2.8.1.r1:compile
[INFO] |  |  |     |  |  |     \- com.alibaba.securitysdk:xml-commons-resolver:jar:1.2.r1:compile
[INFO] |  |  |     |  |  |        \- com.alibaba.securitysdk:xml-apis:jar:1.4.01.r1:compile
[INFO] |  |  |     |  |  \- com.alibaba.securitysdk:fastjson-shade:jar:1.2.68.noneautotype:compile
[INFO] |  |  |     |  \- com.alibaba.security:security-resources:jar:2.0.5.0:compile
[INFO] |  |  |     +- commons-collections:commons-collections:jar:3.2.2:compile
[INFO] |  |  |     +- com.alibaba.spring:spring-context-support-extras:jar:1.0.0:compile
[INFO] |  |  |     +- com.alibaba.spring:spring-webmvc-extras:jar:1.0.3:compile
[INFO] |  |  |     |  \- com.alibaba.spring:spring-context-extras:jar:1.0.2:compile
[INFO] |  |  |     +- com.alibaba.spring:security-extras:jar:1.0.1:compile
[INFO] |  |  |     +- org.springframework.security:spring-security-web:jar:5.4.5:compile
[INFO] |  |  |     +- org.springframework.security:spring-security-core:jar:5.4.5:compile
[INFO] |  |  |     \- org.springframework.security:spring-security-config:jar:5.4.5:compile
[INFO] |  |  +- com.taobao.eagleeye:eagleeye-core:jar:1.9.2.1:compile
[INFO] |  |  |  +- com.alibaba.middleware.apm:stat:jar:1.2.3.1:compile
[INFO] |  |  |  |  \- com.alibaba.middleware.apm:util:jar:1.2.3.1:compile
[INFO] |  |  |  +- com.alibaba.middleware.apm:heap:jar:1.2.3.1:compile
[INFO] |  |  |  +- com.alibaba.middleware.apm:scenario:jar:1.2.3.1:compile
[INFO] |  |  |  +- com.alibaba.middleware.apm:local:jar:1.2.3.1:compile
[INFO] |  |  |  +- com.alibaba.middleware.apm:trace-common:jar:1.2.3.1:compile
[INFO] |  |  |  +- com.alibaba.middleware.apm:jstack-plus:jar:1.2.3.1:compile
[INFO] |  |  |  +- com.alibaba.middleware.apm:elog:jar:1.2.3.1:compile
[INFO] |  |  |  +- com.alibaba.middleware.apm:eagleeye-common:jar:1.2.3.1:compile
[INFO] |  |  |  +- com.alibaba:transmittable-thread-local:jar:2.5.1:compile
[INFO] |  |  |  +- org.benf:cfr:jar:0.122:compile
[INFO] |  |  |  \- org.eclipse.paho:org.eclipse.paho.client.mqttv3:jar:1.2.0:compile
[INFO] |  |  +- com.alibaba.middleware:metrics-core-api:jar:2.0.6:compile
[INFO] |  |  +- com.alibaba.middleware:metrics-core-impl:jar:2.0.6:compile
[INFO] |  |  +- com.alibaba.middleware:metrics-bin:jar:2.0.6:compile
[INFO] |  |  +- com.alibaba.middleware:metrics-common:jar:2.0.6:compile
[INFO] |  |  +- com.alibaba.middleware:metrics-druid:jar:2.0.6:compile
[INFO] |  |  +- com.alibaba.middleware:metrics-integrate:jar:2.0.6:compile
[INFO] |  |  +- com.alibaba.middleware:metrics-jvm:jar:2.0.6:compile
[INFO] |  |  +- com.alibaba.middleware:metrics-nginx:jar:2.0.6:compile
[INFO] |  |  +- com.alibaba.middleware:metrics-os:jar:2.0.6:compile
[INFO] |  |  |  \- com.github.votoanthuan:sigar:jar:1.6.4:compile
[INFO] |  |  +- com.alibaba.middleware:metrics-pandolet:jar:2.0.6:compile
[INFO] |  |  +- com.alibaba.middleware:metrics-reporter:jar:2.0.6:compile
[INFO] |  |  +- com.alibaba.middleware:metrics-tomcat:jar:2.0.6:compile
[INFO] |  |  \- com.alibaba.middleware:metrics-rest:jar:2.0.6:compile
[INFO] |  |     +- javax.ws.rs:javax.ws.rs-api:jar:2.1.1:compile
[INFO] |  |     +- org.glassfish.jersey.containers:jersey-container-jdk-http:jar:2.32:compile
[INFO] |  |     |  +- org.glassfish.jersey.core:jersey-common:jar:2.32:compile
[INFO] |  |     |  |  +- org.glassfish.hk2.external:jakarta.inject:jar:2.6.1:compile
[INFO] |  |     |  |  \- org.glassfish.hk2:osgi-resource-locator:jar:1.0.3:compile
[INFO] |  |     |  +- org.glassfish.jersey.core:jersey-server:jar:2.32:compile
[INFO] |  |     |  |  +- org.glassfish.jersey.core:jersey-client:jar:2.32:compile
[INFO] |  |     |  |  +- org.glassfish.jersey.media:jersey-media-jaxb:jar:2.32:compile
[INFO] |  |     |  |  \- jakarta.validation:jakarta.validation-api:jar:2.0.2:compile
[INFO] |  |     |  \- jakarta.ws.rs:jakarta.ws.rs-api:jar:2.1.6:compile
[INFO] |  |     +- javax.activation:javax.activation-api:jar:1.2.0:compile
[INFO] |  |     \- org.glassfish.jersey.inject:jersey-hk2:jar:2.32:compile
[INFO] |  |        \- org.glassfish.hk2:hk2-locator:jar:2.6.1:compile
[INFO] |  |           +- org.glassfish.hk2.external:aopalliance-repackaged:jar:2.6.1:compile
[INFO] |  |           +- org.glassfish.hk2:hk2-api:jar:2.6.1:compile
[INFO] |  |           \- org.glassfish.hk2:hk2-utils:jar:2.6.1:compile
[INFO] |  +- com.alibaba.boot:maven-spring-boot-starter:jar:1.1.3.SB2:compile
[INFO] |  \- com.alibaba.boot:docker-spring-boot-starter:jar:2.0.0-SB2:compile
[INFO] |     \- io.dropwizard.metrics:metrics-core:jar:4.1.17:compile
[INFO] +- org.springframework.boot:spring-boot-starter-thymeleaf:jar:2.4.3:compile
[INFO] |  +- org.thymeleaf:thymeleaf-spring5:jar:3.0.12.RELEASE:compile
[INFO] |  |  \- org.thymeleaf:thymeleaf:jar:3.0.12.RELEASE:compile
[INFO] |  |     +- org.attoparser:attoparser:jar:2.0.5.RELEASE:compile
[INFO] |  |     \- org.unbescape:unbescape:jar:1.1.6.RELEASE:compile
[INFO] |  \- org.thymeleaf.extras:thymeleaf-extras-java8time:jar:3.0.4.RELEASE:compile
[INFO] +- com.alibaba.boot:buc-spring-boot-starter:jar:1.5.1:compile
[INFO] |  +- org.springframework.boot:spring-boot-autoconfigure:jar:2.4.3:compile
[INFO] |  +- com.alibaba.platform.shared:buc.sso.client:jar:1.4.1:compile
[INFO] |  |  +- com.alibaba.platform.shared:buc.sso.common:jar:1.4.1:compile
[INFO] |  |  +- com.alibaba.platform.shared:buc.sso.client.log:jar:1.4.1:compile
[INFO] |  |  |  \- com.aliyun.openservices:aliyun-sls-v0.6-inner:jar:0.4.7:compile
[INFO] |  |  |     +- net.sf.json-lib:json-lib:jar:jdk15:2.4:compile
[INFO] |  |  |     |  \- net.sf.ezmorph:ezmorph:jar:1.0.6:compile
[INFO] |  |  |     \- net.jpountz.lz4:lz4:jar:1.3.0:compile
[INFO] |  |  \- commons-validator:commons-validator:jar:1.4.0:compile
[INFO] |  |     +- commons-beanutils:commons-beanutils:jar:1.8.3:compile
[INFO] |  |     \- commons-digester:commons-digester:jar:1.8:compile
[INFO] |  \- com.taobao.diamond:diamond-client:jar:3.9.0:compile
[INFO] |     +- com.taobao.diamond:diamond-utils:jar:3.2.12:compile
[INFO] |     |  \- org.codehaus.jackson:jackson-mapper-lgpl:jar:1.9.13:compile
[INFO] |     |     \- org.codehaus.jackson:jackson-core-lgpl:jar:1.9.13:compile
[INFO] |     \- com.alibaba.middleware:tls-sslsocketfactory:jar:1.0.4:compile
[INFO] |        \- com.alibaba.middleware:tls-common:jar:1.0.3:compile
[INFO] +- com.aliyun.odps:odps-sdk-core:jar:0.40.0:compile
[INFO] |  +- com.aliyun.odps:odps-sdk-commons:jar:0.40.0:compile
[INFO] |  |  \- commons-logging:commons-logging:jar:1.2:compile
[INFO] |  +- com.aliyun.odps:odps-compiler-hive-parser:jar:3.37.0.59:compile
[INFO] |  +- commons-codec:commons-codec:jar:1.15:compile
[INFO] |  +- org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13:compile
[INFO] |  |  \- org.codehaus.jackson:jackson-core-asl:jar:1.9.13:compile
[INFO] |  +- org.antlr:antlr4:jar:4.9:compile
[INFO] |  |  +- org.antlr:antlr4-runtime:jar:4.9:compile
[INFO] |  |  +- org.antlr:antlr-runtime:jar:3.5.2:compile
[INFO] |  |  +- org.antlr:ST4:jar:4.3:compile
[INFO] |  |  +- org.abego.treelayout:org.abego.treelayout.core:jar:1.0.3:compile
[INFO] |  |  +- org.glassfish:javax.json:jar:1.0.4:compile
[INFO] |  |  \- com.ibm.icu:icu4j:jar:61.1:compile
[INFO] |  +- com.google.guava:guava:jar:20.0:compile
[INFO] |  +- com.google.code.gson:gson:jar:2.8.6:compile
[INFO] |  +- net.sourceforge.javacsv:javacsv:jar:2.0:compile
[INFO] |  +- org.xerial.snappy:snappy-java:jar:1.1.1.6:compile
[INFO] |  +- org.lz4:lz4-pure-java:jar:1.8.0:compile
[INFO] |  +- com.google.protobuf:protobuf-java:jar:3.13.0:compile
[INFO] |  +- commons-io:commons-io:jar:2.4:compile
[INFO] |  +- javax.mail:mail:jar:1.4.7:compile
[INFO] |  |  \- javax.activation:activation:jar:1.1:compile
[INFO] |  +- commons-lang:commons-lang:jar:2.6:compile
[INFO] |  +- stax:stax-api:jar:1.0.1:compile
[INFO] |  +- stax:stax:jar:1.2.0:compile
[INFO] |  +- xpp3:xpp3:jar:1.1.3.3:compile
[INFO] |  +- org.apache.arrow:arrow-vector:jar:1.0.0:compile
[INFO] |  |  +- org.apache.arrow:arrow-format:jar:1.0.0:compile
[INFO] |  |  +- org.apache.arrow:arrow-memory-core:jar:1.0.0:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-core:jar:2.11.4:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.11.4:compile
[INFO] |  |  +- io.netty:netty-common:jar:4.1.59.Final:compile
[INFO] |  |  \- com.google.flatbuffers:flatbuffers-java:jar:1.9.0:compile
[INFO] |  \- io.netty:netty-all:jar:4.1.59.Final:compile
[INFO] +- com.alibaba.schedulerx:schedulerx2-spring-boot-starter:jar:1.2.7:compile
[INFO] |  +- com.alibaba.schedulerx:schedulerx-worker:jar:1.2.7:compile
[INFO] |  |  \- com.alibaba:fastjson:jar:1.2.78:compile
[INFO] |  \- joda-time:joda-time:jar:2.9.2:compile
[INFO] +- org.springframework.boot:spring-boot-starter-web:jar:2.4.3:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-json:jar:2.4.3:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.11.4:compile
[INFO] |  |  \- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.11.4:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-tomcat:jar:2.4.3:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-core:jar:9.0.43:compile
[INFO] |  |  +- org.glassfish:jakarta.el:jar:3.0.3:compile
[INFO] |  |  \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:9.0.43:compile
[INFO] |  +- org.springframework:spring-web:jar:5.3.4:compile
[INFO] |  \- org.springframework:spring-webmvc:jar:5.3.4:compile
[INFO] |     \- org.springframework:spring-expression:jar:5.3.4:compile
[INFO] +- org.springframework.boot:spring-boot-starter-test:jar:2.4.3:test
[INFO] |  +- org.springframework.boot:spring-boot-test:jar:2.4.3:test
[INFO] |  +- org.springframework.boot:spring-boot-test-autoconfigure:jar:2.4.3:test
[INFO] |  +- com.jayway.jsonpath:json-path:jar:2.4.0:test
[INFO] |  |  \- net.minidev:json-smart:jar:2.3:test
[INFO] |  |     \- net.minidev:accessors-smart:jar:1.2:test
[INFO] |  |        \- org.ow2.asm:asm:jar:5.0.4:test
[INFO] |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.3:compile
[INFO] |  |  \- jakarta.activation:jakarta.activation-api:jar:1.2.2:compile
[INFO] |  +- org.assertj:assertj-core:jar:3.18.1:test
[INFO] |  +- org.hamcrest:hamcrest:jar:2.2:compile
[INFO] |  +- org.junit.jupiter:junit-jupiter:jar:5.7.1:test
[INFO] |  |  +- org.junit.jupiter:junit-jupiter-api:jar:5.7.1:test
[INFO] |  |  |  +- org.apiguardian:apiguardian-api:jar:1.1.0:test
[INFO] |  |  |  +- org.opentest4j:opentest4j:jar:1.2.0:test
[INFO] |  |  |  \- org.junit.platform:junit-platform-commons:jar:1.7.1:test
[INFO] |  |  +- org.junit.jupiter:junit-jupiter-params:jar:5.7.1:test
[INFO] |  |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.7.1:test
[INFO] |  |     \- org.junit.platform:junit-platform-engine:jar:1.7.1:test
[INFO] |  +- org.mockito:mockito-core:jar:3.6.28:test
[INFO] |  |  +- net.bytebuddy:byte-buddy:jar:1.10.20:compile
[INFO] |  |  +- net.bytebuddy:byte-buddy-agent:jar:1.10.20:test
[INFO] |  |  \- org.objenesis:objenesis:jar:3.1:test
[INFO] |  +- org.mockito:mockito-junit-jupiter:jar:3.6.28:test
[INFO] |  +- org.skyscreamer:jsonassert:jar:1.5.0:test
[INFO] |  |  \- com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1:test
[INFO] |  +- org.springframework:spring-core:jar:5.3.4:compile
[INFO] |  |  \- org.springframework:spring-jcl:jar:5.3.4:compile
[INFO] |  +- org.springframework:spring-test:jar:5.3.4:compile
[INFO] |  \- org.xmlunit:xmlunit-core:jar:2.7.0:test
[INFO] +- org.springframework.boot:spring-boot-starter-data-jpa:jar:2.4.3:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-aop:jar:2.4.3:compile
[INFO] |  |  \- org.aspectj:aspectjweaver:jar:1.9.6:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-jdbc:jar:2.4.3:compile
[INFO] |  |  +- com.zaxxer:HikariCP:jar:3.4.5:compile
[INFO] |  |  \- org.springframework:spring-jdbc:jar:5.3.4:compile
[INFO] |  +- jakarta.transaction:jakarta.transaction-api:jar:1.3.3:compile
[INFO] |  +- jakarta.persistence:jakarta.persistence-api:jar:2.2.3:compile
[INFO] |  +- org.hibernate:hibernate-core:jar:5.4.28.Final:compile
[INFO] |  |  +- org.jboss.logging:jboss-logging:jar:3.4.1.Final:compile
[INFO] |  |  +- org.javassist:javassist:jar:3.27.0-GA:compile
[INFO] |  |  +- antlr:antlr:jar:2.7.7:compile
[INFO] |  |  +- org.jboss:jandex:jar:2.2.3.Final:compile
[INFO] |  |  +- com.fasterxml:classmate:jar:1.5.1:compile
[INFO] |  |  +- org.dom4j:dom4j:jar:2.1.3:compile
[INFO] |  |  +- org.hibernate.common:hibernate-commons-annotations:jar:5.1.2.Final:compile
[INFO] |  |  \- org.glassfish.jaxb:jaxb-runtime:jar:2.3.3:compile
[INFO] |  |     +- org.glassfish.jaxb:txw2:jar:2.3.3:compile
[INFO] |  |     +- com.sun.istack:istack-commons-runtime:jar:3.0.11:compile
[INFO] |  |     \- com.sun.activation:jakarta.activation:jar:1.2.2:runtime
[INFO] |  \- org.springframework:spring-aspects:jar:5.3.4:compile
[INFO] +- org.springframework.data:spring-data-jpa:jar:2.5.4:compile
[INFO] |  +- org.springframework.data:spring-data-commons:jar:2.4.5:compile
[INFO] |  +- org.springframework:spring-orm:jar:5.3.4:compile
[INFO] |  +- org.springframework:spring-context:jar:5.3.4:compile
[INFO] |  +- org.springframework:spring-aop:jar:5.3.4:compile
[INFO] |  +- org.springframework:spring-tx:jar:5.3.4:compile
[INFO] |  +- org.springframework:spring-beans:jar:5.3.4:compile
[INFO] |  +- org.aspectj:aspectjrt:jar:1.9.6:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.30:compile
[INFO] +- mysql:mysql-connector-java:jar:8.0.22:compile
[INFO] +- com.querydsl:querydsl-jpa:jar:4.4.0:compile
[INFO] |  +- com.querydsl:querydsl-core:jar:4.4.0:compile
[INFO] |  |  +- com.google.code.findbugs:jsr305:jar:1.3.9:compile
[INFO] |  |  +- com.mysema.commons:mysema-commons-lang:jar:0.2.4:compile
[INFO] |  |  \- com.infradna.tool:bridge-method-annotation:jar:1.13:compile
[INFO] |  \- javax.inject:javax.inject:jar:1:compile
[INFO] +- com.vladmihalcea:hibernate-types-52:jar:2.12.1:compile
[INFO] |  \- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.11.4:compile
[INFO] +- org.mapstruct:mapstruct:jar:1.4.2.Final:compile
[INFO] +- org.apache.thrift:libthrift:jar:0.15.0:compile
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.5.13:compile
[INFO] |  +- org.apache.httpcomponents:httpcore:jar:4.4.14:compile
[INFO] |  \- javax.annotation:javax.annotation-api:jar:1.3.2:compile
[INFO] +- commons-pool:commons-pool:jar:1.6:compile
[INFO] +- org.apache.zookeeper:zookeeper:jar:3.4.6:compile
[INFO] |  +- org.slf4j:slf4j-log4j12:jar:1.7.30:compile
[INFO] |  +- log4j:log4j:jar:1.2.16:compile
[INFO] |  +- jline:jline:jar:0.9.94:compile
[INFO] |  |  \- junit:junit:jar:4.13.2:compile
[INFO] |  |     \- org.hamcrest:hamcrest-core:jar:2.2:compile
[INFO] |  \- io.netty:netty:jar:3.7.0.Final:compile
[INFO] +- org.apache.curator:curator-recipes:jar:2.7.1:compile
[INFO] |  \- org.apache.curator:curator-framework:jar:2.11.1:compile
[INFO] |     \- org.apache.curator:curator-client:jar:2.11.1:compile
[INFO] \- org.projectlombok:lombok:jar:1.18.10:provided
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.347 s
[INFO] Finished at: 2021-12-22T21:05:23+08:00
[INFO] ------------------------------------------------------------------------

Compilation finished at Wed Dec 22 21:05:23
```

**Comment by lickerish** [comment]
@loujiaye What is the import that you have for `@Transactional` in ImportDayIndicatorProcessor?
I believe this one should be in use: `org.springframework.transaction.annotation.Transactional` 
instead of this one: `javax.transaction.Transactional`.
There is a chance that this can fix the issue

**Comment by MMD-Coding** [comment]
You are probably just using the `@Transactional` annotation incorrectly, because it is placed on a `protected` method, but it must be `public`. Also see [this StackOverflow question](https://stackoverflow.com/questions/34197964/why-doesnt-springs-transactional-work-on-protected-methods) for details.
