### ISSUE TITLE
DateTimeOperation Functnion ADD_HOURS Is Missing

### ISSUE THREAD

**Issue by tjmeal** [querydsl/querydsl#3178]
Hello, i have an object with LocalDateTime and int (duration) and i want to create a query where i take LocalDateTime add the duration (in hours) and compare with LocalDateTime.Now().

Bellow Is My code: 

 `@Override
    public List<Transfer> findAllOrganizedTransfersByDriver(@Nonnull final Long driverId) {
        final QTransfer qTransfer = QTransfer.transfer;
        final QDriver qDriver = QDriver.driver;
        
        return from(qTransfer)
                .innerJoin(qTransfer.driver, qDriver)
                .where(qTransfer.myCompany.id.eq(qDriver.company.id)
                                .and(qTransfer.driver.id.eq(driverId)
                                )
                )
                .where(qTransfer.transferDateTime.before(
                                //DateTimeExpression.currentTimestamp(LocalDateTime.class)
                                Expressions.dateTimeOperation(
                                        LocalDateTime.class, Ops.DateTimeOps.ADD_HOURS,
                                        DateTimeExpression.currentTimestamp(LocalDateTime.class),
                                        //Expressions.asNumber(2)
                                        ConstantImpl.create(5)
                                )
                        )
                )
                .orderBy(qTransfer.transferStatus.desc())
                .orderBy(qTransfer.transferDateTime.asc())
                .fetch();
    }`

## Environment    BigSur

Querydsl version:
    implementation group: 'com.querydsl', name: 'querydsl-jpa', version: '4.2.1'
    annotationProcessor group: 'com.querydsl', name: 'querydsl-apt', version: '4.2.1'

Database: mysql-connector-java-8.0.19

JDK: 11

## Additional details

 Here is the error log i get:

Caused by: java.sql.SQLSyntaxErrorException: FUNCTION transfers_new(this is my db name).add_hours does not exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[HikariCP-java7-2.4.13.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[HikariCP-java7-2.4.13.jar:na]
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:57) ~[hibernate-core-5.4.12.Final.jar:5.4.12.Final]
	... 170 common frames omitted

Thanks a lot i will be waiting your reply.

**Comment by zqr95518** [comment]
```
public class MySQL5InnoDBDialectExt extends MySQL5InnoDBDialect {

    public MySQL5InnoDBDialectExt() {
        super();
//        registerFunction("add_years", new SQLFunctionTemplate(StandardBasicTypes.DATE, "?1 + ?2 years"));
//        registerFunction("add_months", new SQLFunctionTemplate(StandardBasicTypes.DATE, "?1 + ?2 months"));
//        registerFunction("add_weeks", new SQLFunctionTemplate(StandardBasicTypes.DATE, "?1 + 7 * ?2"));
//        registerFunction("add_days", new SQLFunctionTemplate(StandardBasicTypes.DATE, "?1 + ?2"));
        registerFunction("add_hours", new SQLFunctionTemplate(StandardBasicTypes.DATE, "DATE_ADD(?1, INTERVAL ?2 HOUR)"));
        registerFunction("diff_seconds", new SQLFunctionTemplate(StandardBasicTypes.LONG, "TIMESTAMPDIFF(SECOND,?1,?2)"));
        registerFunction("diff_minutes", new SQLFunctionTemplate(StandardBasicTypes.LONG, "TIMESTAMPDIFF(MINUTE,?1,?2)"));
        registerFunction("diff_hours", new SQLFunctionTemplate(StandardBasicTypes.LONG, "TIMESTAMPDIFF(HOUR,?1,?2)"));
        registerFunction("diff_days", new SQLFunctionTemplate(StandardBasicTypes.LONG, "TIMESTAMPDIFF(DAY,?1,?2)"));
    }
}
```
Can use this Dialect for MYSQL.

**Comment by jwgmeligmeyling** [comment]
Yes, the issue here is that JPQL does not define any add_hours or date_add function by itself. You'll have to extend your ORM dialect to use it.
