### ISSUE TITLE
The transform method throws a ClassCastException when working with joinFetch since 4.4.0

### ISSUE THREAD

**Issue by miki1029** [querydsl/querydsl#3264]
## Observed vs. expected behavior

The transform method throws a ClassCastException when working with joinFetch.

## Steps to reproduce

I upload code here.
https://github.com/miki1029/querydsl-transform-bug

```java
// no error
    @Transactional(readOnly = true)
    public Map<Long, Parent> getWithoutFetchJoin(Long id) {
        return from(parent)
                .leftJoin(parent.children)
                .where(parent.id.eq(id))
                .transform(groupBy(parent.id).as(parent));
    }

// error
    @Transactional(readOnly = true)
    public Map<Long, Parent> getWithFetchJoin(Long id) {
        return from(parent)
                .leftJoin(parent.children)
                .fetchJoin()
                .where(parent.id.eq(id))
                .distinct()
                .transform(groupBy(parent.id).as(parent));
    }
```

## Environment

https://github.com/miki1029/querydsl-transform-bug/blob/master/build.gradle

Querydsl version: 5.0.0 (I got the same error in 4.4.0, not in 4.3.1.)

Querydsl module:

```groovy
    implementation "com.querydsl:querydsl-jpa"
    annotationProcessor "jakarta.persistence:jakarta.persistence-api"
    annotationProcessor "jakarta.annotation:jakarta.annotation-api"
    annotationProcessor group: "com.querydsl", name: "querydsl-apt", classifier: "jpa"
```

Database: H2

JDK: openjdk11

## Additional details

```
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:780) ~[spring-boot-2.6.7.jar:2.6.7]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:761) ~[spring-boot-2.6.7.jar:2.6.7]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:310) ~[spring-boot-2.6.7.jar:2.6.7]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1312) ~[spring-boot-2.6.7.jar:2.6.7]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301) ~[spring-boot-2.6.7.jar:2.6.7]
	at com.example.querydsltransformbug.QuerydslTransformBugApplication.main(QuerydslTransformBugApplication.java:26) ~[main/:na]
Caused by: java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class com.querydsl.core.Tuple ([Ljava.lang.Object; is in module java.base of loader 'bootstrap'; com.querydsl.core.Tuple is in unnamed module of loader 'app')
	at com.querydsl.core.group.GroupByMap.transform(GroupByMap.java:57) ~[querydsl-core-5.0.0.jar:na]
	at com.querydsl.core.group.GroupByMap.transform(GroupByMap.java:35) ~[querydsl-core-5.0.0.jar:na]
	at com.querydsl.core.support.FetchableQueryBase.transform(FetchableQueryBase.java:55) ~[querydsl-core-5.0.0.jar:na]
	at com.example.querydsltransformbug.ParentService.getWithFetchJoin(ParentService.java:45) ~[main/:na]
	at com.example.querydsltransformbug.ParentService$$FastClassBySpringCGLIB$$a913a3eb.invoke(<generated>) ~[main/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.19.jar:5.3.19]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.19.jar:5.3.19]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.19.jar:5.3.19]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.19.jar:5.3.19]
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137) ~[spring-tx-5.3.19.jar:5.3.19]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.19.jar:5.3.19]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.19.jar:5.3.19]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-5.3.19.jar:5.3.19]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388) ~[spring-tx-5.3.19.jar:5.3.19]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-5.3.19.jar:5.3.19]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.19.jar:5.3.19]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.19.jar:5.3.19]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.19.jar:5.3.19]
	at com.example.querydsltransformbug.ParentService$$EnhancerBySpringCGLIB$$82705e06.getWithFetchJoin(<generated>) ~[main/:na]
	at com.example.querydsltransformbug.QuerydslTransformBugApplication.run(QuerydslTransformBugApplication.java:36) ~[main/:na]
	at com.example.querydsltransformbug.QuerydslTransformBugApplication$$FastClassBySpringCGLIB$$123f3653.invoke(<generated>) ~[main/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.19.jar:5.3.19]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.19.jar:5.3.19]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.19.jar:5.3.19]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.19.jar:5.3.19]
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137) ~[spring-tx-5.3.19.jar:5.3.19]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.19.jar:5.3.19]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.19.jar:5.3.19]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.19.jar:5.3.19]
	at com.example.querydsltransformbug.QuerydslTransformBugApplication$$EnhancerBySpringCGLIB$$f479204c.run(<generated>) ~[main/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:777) ~[spring-boot-2.6.7.jar:2.6.7]
	... 5 common frames omitted
```

**Comment by jwgmeligmeyling** [comment]
You're only allowed to `fetchJoin` relations that are selected in the select clause.

Instead of throwing an exception Hibernate probably implicitly adds the children to the selection but this unfortunately means that the output from the query differs from what Querydsl expects.

Adding the child relation to your projection should fix the issue.

**Comment by svenrienstra** [comment]
I'm pretty sure this is actually a bug in Hibernate. The `ResultTransformer` to transform the result into a `Tuple` is not applied by Hibernate when `FetchingScrollableResultsImpl` is used. `FetchingScrollableResultsImpl` simply returns:
```
currentRow = new Object[] {row};
```

while `ScrollableResultsImpl` applies the `ResultTransformer` through the `HolderInstantiator`:
```
currentRow = new Object[] { getHolderInstantiator().instantiate( currentRow ) };
```
```
	public Object instantiate(Object[] row) {
		if (transformer==null) {
			return row;
		}
		else {
			return transformer.transformTuple(row, getQueryReturnAliases());
		}
	}
```

To workaround this I've changed the `AbstractGroupByTransformer` implementations from:
```
 while (iter.hasNext()) {
                @SuppressWarnings("unchecked") //This type is mandated by the key type
                K[] row = (K[]) iter.next().toArray();
```

to

```
 while (iter.hasNext()) {
                Object next = iter.next();
                Tuple tuple;
                if (next instanceof Tuple) {
                    tuple = (Tuple) next;
                } else if (next instanceof Object[]) {
                    tuple = Projections.tuple(expressions).newInstance((Object[])next);
                } else {
                    throw new IllegalArgumentException(String.format("Could not translate %s into tuple", next));
                }

                K[] row = (K[]) tuple.toArray();
```

**Comment by kamilkrzywanski** [comment]
https://github.com/OpenFeign/querydsl/pull/534 created pr here :)

**Comment by kamilkrzywanski** [comment]
@miki1029 
created pr here: https://github.com/OpenFeign/querydsl/pull/534
