### ISSUE TITLE
java.lang.NoSuchMethodError: 'java.lang.Object org.hibernate.ScrollableResults.get(int)' with Hibernate 6.1.5.Final

### ISSUE THREAD

**Issue by rimuln** [querydsl/querydsl#3428]
## Observed vs. expected behavior
Observed:
Caused by: java.lang.NoSuchMethodError: 'java.lang.Object org.hibernate.ScrollableResults.get(int)'
	at deployment.acoset-server-ear.ear//com.querydsl.jpa.ScrollableResultsIterator.next(ScrollableResultsIterator.java:70)
	at deployment.acoset-server-ear.ear//com.querydsl.core.group.GroupByMap.transform(GroupByMap.java:57)
	at deployment.acoset-server-ear.ear//com.querydsl.core.group.GroupByMap.transform(GroupByMap.java:35)
	at deployment.acoset-server-ear.ear//com.querydsl.core.support.FetchableQueryBase.transform(FetchableQueryBase.java:55)
	at deployment.acoset-server-ear.ear.acoset-server-ejb.jar//de.ids.acos.et.server.dao.ooe.factory.TypeCacheDao.findTypeIdToEffectiveSuperTypeIdsAndSelfByLevel(TypeCacheDao.java:42)

Expected no exception and query works.

## Environment
Wildfly 27.0.0.Final

Querydsl version: 5.0.0 with clasifier Jakarta

Querydsl module: querydsl-jpa

Database: PostgreSQL

JDK: 11.0.16-8

## Additional details
Hibernate 6.1.5.Final

Change was done in https://github.com/hibernate/hibernate-orm/commit/26ff169db2405f6cd9e59f4c50632bad1e62f7fd#diff-1a843877538f892512c24e5d544d9f60a527dc87cfc05901fcccb35557a537d1

Query:
    return query()
        .select(typeHierarchyEntity.lowerId, typeHierarchyEntity.upperId)
        .orderBy(typeHierarchyEntity.sortValue.asc())
        .from(typeHierarchyEntity)
        .transform(
            groupBy(typeHierarchyEntity.lowerId)
                .as(sortedMap(typeHierarchyEntity.level, list(typeHierarchyEntity.upperId))));
  }

**Comment by mmm8955405** [comment]
It's time to update the document. I also encountered this problem, but it was solved

**Comment by PatrickGotthard** [comment]
Same here, every "transform" is broken.
@mmm8955405 how did you solve the problem?

**Comment by jwgmeligmeyling** [comment]
For Hibernate 6.x you want to use the `DefaultQueryHandler` instead of the `HibernateHandler`.

**Comment by rimuln** [comment]
@jwgmeligmeyling  What you mean?. We don't call any of this mentioned class.

We are using
`  @PersistenceContext
  protected EntityManager entityManager;

  protected JPAQueryFactory query() {
    return new JPAQueryFactory(entityManager);
  }
`
for query initialization.

**Comment by jwgmeligmeyling** [comment]
Yes, try `new JPAQueryFactory(JPQLTemplates.DEFAULT, entityManager)`. It should give better results on Hibernate 6.x.

**Comment by jwgmeligmeyling** [comment]
Yes a work around would be  `AbstractJPAQuery.stream()` which uses `Query.stream()` which is part of JPA since version 2.2 and is the preferred way of streaming results.

It is true that `iterate` currently does not stream. I guess thats something we could change. However, you can quite easily work around that using a custom handler:

```java
JPAQueryFactory jpaQueryFactory = new JPAQueryFactory(new JPQLTemplates(DEFAULT_ESCAPE, new QueryHandler() {

            @Override
            public void addEntity(Query query, String alias, Class<?> type) {
                // do nothing
            }

            @Override
            public void addScalar(Query query, String alias, Class<?> type) {
                // do nothing
            }

            @Override
            public boolean createNativeQueryTyped() {
                return true;
            }

            @SuppressWarnings("unchecked")
            @Override
            public <T> CloseableIterator<T> iterate(Query query, final FactoryExpression<?> projection) {
                Stream<T> stream = stream(query, projection);
                return new IteratorAdapter<T>(stream.iterator(), stream::close);
            }

            @Override
            public <T> Stream<T> stream(Query query, FactoryExpression<?> projection) {
                final Stream resultStream = query.getResultStream();
                if (projection != null) {
                    return resultStream.map(element -> projection.newInstance((Object[]) (element.getClass().isArray() ? element : new Object[]{element})));
                }
                return resultStream;
            }

            @Override
            public boolean transform(Query query, FactoryExpression<?> projection) {
                return false;
            }

            @Override
            public boolean wrapEntityProjections() {
                return false;
            }

        }) {
        }, entityManager);
```

**Comment by martinufo** [comment]
@jwgmeligmeyling Thanks for the quick reply! That is exactly the missing piece I needed :smile:.

**Comment by osean-me** [comment]
@jwgmeligmeyling Thanks to you, it's settled. You'll be blessed! :^)

**Comment by yashps99** [comment]
I'm also facing this issue, @jwgmeligmeyling or anyone please let me know how can it be resolved?

**Environment**
Querydsl version: 5.0.0 with clasifier Jakarta
Querydsl module: querydsl-jpa and querydsl-apt
Database: MySQL
JDK: 17
Hibernate 6.1.7.Final

**Code snippet where issue is occurring:**
Here entityClass extends EntityPathBase of querydsl.core.types.dsl
sNo is of NumberPath<Long> type
stringPath is of StringPath type
```
getQuerydsl().createQuery()
         .from(entityClass)
         .where(predicate)
         .groupBy(entityClass.stringPath)
         .transform(GroupBy.groupBy(entityClass.stringPath).as(entityClass.sNo.count()))
```

**Logs**:

jakarta.servlet.ServletException: Handler dispatch failed: java.lang.NoSuchMethodError: 'java.lang.Object org.hibernate.ScrollableResults.get(int)'
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1096)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at com.oneassist.datawarehouse.filters.MdcFilter.doFilter(MdcFilter.java:29)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:676)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NoSuchMethodError: 'java.lang.Object org.hibernate.ScrollableResults.get(int)'
	at com.querydsl.jpa.ScrollableResultsIterator.next(ScrollableResultsIterator.java:70)
	at com.querydsl.core.group.GroupByMap.transform(GroupByMap.java:57)
	at com.querydsl.core.group.GroupByMap.transform(GroupByMap.java:35)
	at com.querydsl.core.support.FetchableQueryBase.transform(FetchableQueryBase.java:55)

**Comment by xtermi2** [comment]
we useed `org.springframework.data.jpa.repository.support.QuerydslRepositorySupport` which uses `org.springframework.data.jpa.repository.support.Querydsl` which determines the `JPQLTemplates` from the `EntityManager` somehow. Here is our Solution:

```java
class Hibernate6Querydsl extends Querydsl {
    private final EntityManager entityManager;

    public Hibernate6Querydsl(EntityManager entityManager, PathBuilder<?> builder) {
        super(entityManager, builder);
        this.entityManager = entityManager;
    }

    @Override
    public <T> AbstractJPAQuery<T, JPAQuery<T>> createQuery() {
        // https://github.com/querydsl/querydsl/issues/3428
        return new JPAQuery<>(entityManager, JPQLTemplates.DEFAULT);
    }
}


/**
 * Extension of QuerydslRepositorySupport which uses JPQLTemplates.DEFAULT instead of the Hibernate variant
 * https://github.com/querydsl/querydsl/issues/3428
 */
public abstract class Hibernate6QuerydslRepositorySupport extends QuerydslRepositorySupport {

    private Hibernate6Querydsl querydsl;

    public Hibernate6QuerydslRepositorySupport(Class<?> domainClass) {
        super(domainClass);
    }

    @Override
    protected Querydsl getQuerydsl() {
        if (null == querydsl && getEntityManager() != null) {
            this.querydsl = new Hibernate6Querydsl(getEntityManager(), getBuilder());
        }
        return this.querydsl;
    }

    @Nonnull
    private Querydsl getRequiredQuerydsl() {
        if (getQuerydsl() == null) {
            throw new IllegalStateException("Querydsl is null");
        }
        return getQuerydsl();
    }

    @Override
    protected JPQLQuery<Object> from(EntityPath<?>... paths) {
        return getRequiredQuerydsl().createQuery(paths);
    }

    @Override
    protected <T> JPQLQuery<T> from(EntityPath<T> path) {
        return getRequiredQuerydsl().createQuery(path).select(path);
    }
}
```

**Comment by GJohannes** [comment]
That worked for me. Thanks a lot

**Comment by bill-3178** [comment]
I have the same issue with **JPASQLQuery** (part of Querydsl-SQL module)
Do you know if there is a way to fix it ? Unlike JPQLTemplates , queryHandler is not an attribute of SqlTemplates and sub-classes, and HibernateHandler is used when fetching the results.

**Comment by jwgmeligmeyling** [comment]
QueryHandler can be passed as parameter to JPASqlQuery:

https://github.com/querydsl/querydsl/blob/master/querydsl-jpa/src/main/java/com/querydsl/jpa/sql/JPASQLQuery.java#L44

I have never worked with/on JPQSQLQuery so other than that I don't know any workarounds.

**Comment by bill-3178** [comment]
Thank you @jwgmeligmeyling , you're right !
I could implement a JPASQLQuery by passing a QueryHandler that provides a custom IteratorAdapter to iterate on Object[] elements and return Tuple elements : 


`
return new JPASQLQuery<>(getEntityManager(), new Configuration(mySqlTemplates), new QueryHandler() {
			@Override
			public boolean createNativeQueryTyped() {
				return true;
			}

			@Override
			public <T> CloseableIterator<T> iterate(Query query, @Nullable FactoryExpression<?> projection) {
				Stream<Object[]> stream = stream(query, projection);
				return new TupleQueryResultIteratorAdapter<>(stream.iterator(), stream::close);
			}

			@SuppressWarnings("unchecked")
			@Override
			public <T> Stream<T> stream(Query query, @Nullable FactoryExpression<?> projection) {
				final Stream resultStream = query.getResultStream();
				if (projection != null) {
					return resultStream.map(element -> projection.newInstance((Object[]) (element.getClass().isArray() ? element : new Object[]{element})));
				}
				return resultStream;
			}

			@Override
			public void addScalar(Query query, String s, Class<?> aClass) {
			}

			@Override
			public void addEntity(Query query, String s, Class<?> aClass) {
			}

			@Override
			public boolean transform(Query query, FactoryExpression<?> factoryExpression) {
				return false;
			}

			@Override
			public boolean wrapEntityProjections() {
				return false;
			}
		})
...


public class TupleQueryResultIteratorAdapter<T> implements CloseableIterator<T> {

	private final Iterator<Object[]> iter;

	private final Closeable closeable;

	public TupleQueryResultIteratorAdapter(Iterator<Object[]> iter, Closeable closeable) {
		this.iter = iter;
		this.closeable = closeable;
	}

	public TupleQueryResultIteratorAdapter(Iterator<Object[]> iter) {
		this.iter = iter;
		this.closeable = iter instanceof Closeable ? (Closeable) iter : null;
	}

	@Override
	public boolean hasNext() {
		return iter.hasNext();
	}

	@SuppressWarnings("unchecked")
	@Override
	public T next() {
		final Object[] e = iter.next();
		return (T) new TupleImpl(e);
	}

	@Override
	public void close() {
		if (closeable != null){
			try {
				closeable.close();
			} catch (IOException e) {
				throw new RuntimeException(e.getMessage(), e);
			}
		}
	}
}
`
