### ISSUE TITLE
Error when using querydsl-kotlin-codegen 5.0.0

### ISSUE THREAD

**Issue by debop** [querydsl/querydsl#3454]
## Observed vs. expected behavior

when use querydsl-kotlin-codegen with spring-data-jpa, raise exception. 
but not use (generate java class) then it works.

```
Caused by: java.lang.IllegalStateException: Could not access method or field: class org.springframework.util.ReflectionUtils cannot access a member of class examples.querydsl.domain.model.QMember with modifiers "private static final"

        at org.springframework.util.ReflectionUtils.getField(ReflectionUtils.java:661)
        at org.springframework.data.querydsl.SimpleEntityPathResolver.lambda$createPath$0(SimpleEntityPathResolver.java:74)
        at java.base/java.util.Optional.map(Optional.java:260)
        at org.springframework.data.querydsl.SimpleEntityPathResolver.createPath(SimpleEntityPathResolver.java:74)
        at org.springframework.data.jpa.repository.support.QuerydslJpaPredicateExecutor.<init>(QuerydslJpaPredicateExecutor.java:83)
        at org.springframework.data.jpa.repository.support.JpaRepositoryFactory.getRepositoryFragments(JpaRepositoryFactory.java:273)
        at org.springframework.data.jpa.repository.support.JpaRepositoryFactory.getRepositoryFragments(JpaRepositoryFactory.java:243)
        at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepositoryComposition(RepositoryFactorySupport.java:436)
        at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:301)
        at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.lambda$afterPropertiesSet$5(RepositoryFactoryBeanSupport.java:323)
        at org.springframework.data.util.Lazy.getNullable(Lazy.java:231)
        at org.springframework.data.util.Lazy.get(Lazy.java:115)
        at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.getObject(RepositoryFactoryBeanSupport.java:271)
        at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.getObject(RepositoryFactoryBeanSupport.java:58)
        at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:169)
        ... 103 more
``` 

## Environment

Querydsl version: 5.0.0

Querydsl module: querydsl-kotlin-codegen

Database: H2

JDK: GraalVM 11

## Additional details

Use querydsl-kotlin-codegen 5.0.0

in build.gradle.kts 

```
    // QueryDsl
    implementation(Libs.querydsl_jpa)
    implementation(Libs.querydsl_kotlin)
    kapt(Libs.querydsl_apt + ":jpa")
    kaptTest(Libs.querydsl_apt + ":jpa")
    kapt(Libs.querydsl_kotlin_codegen)
    kaptTest(Libs.querydsl_kotlin_codegen)
```

Entity like this 

```
@Entity
class Member {

    companion object {
        operator fun invoke(name: String, age: Int? = null, team: Team? = null): Member {
            name.requireNotEmpty("name")
            return Member().also {
                it.name = name
                it.age = age
                it.team = team
            }
        }
    }

    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    var id:Long? = null

    var name: String = ""

    var age: Int? = null

    @ManyToOne(fetch = FetchType.LAZY)
    var team: Team? = null
```

**Comment by joonseolee** [comment]
any progress?
