### ISSUE TITLE
springboot 3.0.2: java.lang.ClassNotFoundException: com.querydsl.jpa.impl.JPAQueryFactory

### ISSUE THREAD

**Issue by liming1010** [querydsl/querydsl#3466]
pox.xml
`
        <dependency>

            <groupId>com.querydsl</groupId>

            <artifactId>querydsl-apt</artifactId>

            <version>5.0.0</version>

            <scope>provided</scope>

            <classifier>jakarta</classifier>

        </dependency>

        <dependency>

            <groupId>com.querydsl</groupId>

            <artifactId>querydsl-jpa</artifactId>

            <version>5.0.0</version>

            <scope>provided</scope>

            <classifier>jakarta</classifier>

        </dependency>

`
jdk17
springboot3.0.2

`
@Configuration
public class QuerydslConfig {

    @Bean
    public JPAQueryFactory jpaQuery(EntityManager entityManager) {
        System.out.println(entityManager);
        return new JPAQueryFactory(entityManager);
    }

}
`

and Startup error:
`
java.lang.IllegalStateException: Failed to introspect Class [com.tpy.demo.config.QuerydslConfig] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@63947c6b]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:483) ~[spring-core-6.0.4.jar:6.0.4]
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:360) ~[spring-core-6.0.4.jar:6.0.4]
	at org.springframework.util.ReflectionUtils.getUniqueDeclaredMethods(ReflectionUtils.java:417) ~[spring-core-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.lambda$getTypeForFactoryMethod$1(AbstractAutowireCapableBeanFactory.java:749) ~[spring-beans-6.0.4.jar:6.0.4]
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[na:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryMethod(AbstractAutowireCapableBeanFactory.java:748) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:681) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:652) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1632) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:559) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:531) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:658) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:650) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.context.support.AbstractApplicationContext.getBeansOfType(AbstractApplicationContext.java:1276) ~[spring-context-6.0.4.jar:6.0.4]
	at org.springframework.boot.SpringApplication.getExitCodeFromMappedException(SpringApplication.java:863) ~[spring-boot-3.0.3-20230127.063751-9.jar:3.0.3-SNAPSHOT]
	at org.springframework.boot.SpringApplication.getExitCodeFromException(SpringApplication.java:851) ~[spring-boot-3.0.3-20230127.063751-9.jar:3.0.3-SNAPSHOT]
	at org.springframework.boot.SpringApplication.handleExitCode(SpringApplication.java:838) ~[spring-boot-3.0.3-20230127.063751-9.jar:3.0.3-SNAPSHOT]
	at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:778) ~[spring-boot-3.0.3-20230127.063751-9.jar:3.0.3-SNAPSHOT]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:321) ~[spring-boot-3.0.3-20230127.063751-9.jar:3.0.3-SNAPSHOT]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) ~[spring-boot-3.0.3-20230127.063751-9.jar:3.0.3-SNAPSHOT]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291) ~[spring-boot-3.0.3-20230127.063751-9.jar:3.0.3-SNAPSHOT]
	at com.tpy.demo.DemoApplication.main(DemoApplication.java:12) ~[classes/:na]
Caused by: java.lang.NoClassDefFoundError: com/querydsl/jpa/impl/JPAQueryFactory
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[na:na]
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[na:na]
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504) ~[na:na]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:465) ~[spring-core-6.0.4.jar:6.0.4]
	... 21 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.querydsl.jpa.impl.JPAQueryFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
	... 25 common frames omitted
`

But it can pass the unit test.

**Comment by kdebski85** [comment]
Why do you use `<scope>provided</scope>` for `<artifactId>querydsl-jpa</artifactId>`?
Try without it.

**Comment by liming1010** [comment]
delete <scope>provided</scope>, not work

**Comment by lukaseckert** [comment]
I got it working with Spring Boot using Gradle and dependencies like:

**build.gradle**
```
dependencies {
    annotationProcessor 'com.querydsl:querydsl-apt:5.0.0:jakarta'
    annotationProcessor 'jakarta.persistence:jakarta.persistence-api:3.1.0'
    annotationProcessor 'jakarta.annotation:jakarta.annotation-api:2.1.1'
    ...
}
```

**QueryDslConfig.java**
```
    @Bean
    public JPAQueryFactory createFactory() {
        return new JPAQueryFactory(new HQLTemplates(), () -> entityManager);
    }
```

However there at lots of issues with Hibernate 6, which I could not find a fix for yet. E.g. the order-by-Clause generated by Querydsl for an EmbeddedId field is not accepted by Hibernate 6 anymore.

**Comment by liming1010** [comment]
is work

` 
        <dependency>
            <groupId>com.querydsl</groupId>
            <artifactId>querydsl-apt</artifactId>
            <version>5.0.0</version>
            <scope>provided</scope>
            <classifier>jakarta</classifier>
        </dependency>
        <dependency>
            <groupId>com.querydsl</groupId>
            <artifactId>querydsl-jpa</artifactId>
            <version>5.0.0</version>
            <classifier>jakarta</classifier>
        </dependency>`

**Comment by ramkumarrchalla** [comment]
<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <compilerArgument>-proc:none</compilerArgument>
                </configuration>
            </plugin>

adding this along with apt plugin for dsl, build will be successful, thank you!

mvn clean compile - worked for me

**Comment by jwgmeligmeyling** [comment]
As others pointed out querydsl-jpa needs to be in the compile scope.

Only querydsl-apt should be used in provided scope.
