### ISSUE TITLE
withRecursive query has wrong SQL Server template mapping

### ISSUE THREAD

**Issue by Vidda777** [querydsl/querydsl#3478]
## Observed vs. expected behaviour

When using `withRecursive` clause against a SQL Server instance, the resulting SQL is not compliance with SQL Server. It uses `with recursive` statement that is not supported by SQL Server (it only uses `with`): [](https://learn.microsoft.com/en-us/sql/t-sql/queries/with-common-table-expression-transact-sql?view=sql-server-2017)

_(Take a look to **Additional details** at the end of this issue as I found the exact place of the error)_

## Steps to reproduce

Not sure if I have to include a detailed description of tables and the query for that ones, if you need it let me know and I would try to build up the typical example of getting all children of a parent using with recursive. But the QueryDsl sintax would be:

```
//alias for make join queries easier
DocumentQueryDsl docs = new DocumentQueryDsl("docs");
//required to reference columns of the cte table, using the alias
DocumentQueryDsl cteChildren = new DocumentQueryDsl("cteChildren");
EntityPathBase<DocumentQueryDsl> cte = new EntityPathBase<>(DocumentQueryDsl.class, "cteChildren");

SQLQuery<String> descendantsQuery = sqlQuery
    .withRecursive(cte, Q_DOC_DSL.DOCUMENT_ID, Q_DOC_DSL.PARENT_ID)
    .as(unionAll(
      select(docs.DOCUMENT_ID, docs.PARENT_ID).from(docs).where(docs.PARENT_ID.eq(documentId).and(docs.COLLECTION_ID.eq(collectionId))),
      select(docs.DOCUMENT_ID, docs.PARENT_ID).from(docs, cte).where(cteChildren.DOCUMENT_ID.eq(docs.PARENT_ID).and(docs.COLLECTION_ID.eq(collectionId))))
    )
    .select(cteChildren.DOCUMENT_ID).from(cte).distinct();
```

And this ends up generating a SQL like this: 
```
with recursive "cteChildren" ("DOCUMENT_ID", "PARENT_ID") as ((select "docs"."DOCUMENT_ID", "docs"."PARENT_ID" from "DOCOS" "docs" where "docs"."PARENT_ID" = ? and "docs"."COLLECTION_ID" = )
union
(select "docs"."DOCUMENT_ID", "docs"."PARENT_ID" from "DOCOS" "docs", "cteChildren" where "cteChildren"."DOCUMENT_ID" = "docs"."PARENT_ID" and "docs"."COLLECTION_ID" = ?))
select "cteChildren"."DOCUMENT_ID" from "cteChildren"
```

that causes the following exception:
```
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near 'cteChildren'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:260)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1547)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:528)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:461)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7342)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2688)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:224)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:204)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:383)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1471)
	at com.querydsl.sql.AbstractSQLQuery.fetch(AbstractSQLQuery.java:446)
```

## Environment

Querydsl version: **4.1.2** (although I checked the affected template on 5.0.0 version and it's the same code, so it does not change the issue)

Querydsl module: **sql**

Database: Microsoft **SQL Server 14**

JDK: **Amazon Corretto 11.9**

## Additional details

I located the issue in the `com.querydsl.query.SQLServerTemplates` class. The constructor does not override default withRecursive mapping (like OracleTemplates does) to use `with`. So the default value `with recursive` is used instead.

Adding `setWithRecursive("with ");` to the constructor fix the issue.

**Comment by Vidda777** [comment]
As a workaround I copied the `com.querydsl.query.SQLServerTemplates` class in our project and add the fix setting the `setWithRecursive("with ");` in the constructor. But obviously I prefer to have this fix in a version of this awesome library :-D
