### ISSUE TITLE
Parameter type mismatch with Hibernate 6 and Querydsl when using function in stringTemplate expression

### ISSUE THREAD

**Issue by plinkr** [querydsl/querydsl#3495]
I recently migrated my app from `"Hibernate Version":"5.6.15.Final", "Spring Version":"5.3.26", "SpringBoot Version":"2.7.10"` 
to `"Hibernate Version":"6.1.7.Final", "Spring Version":"6.0.7", "SpringBoot Version":"3.0.5"`.

I'm using PostgreSQL as the database and JDK version "17.0.6" and "17.0.2".

I changed my `pom.xml` accordingly to reflect the use of Jakarta by Querydsl:
```		
<dependency>
    <groupId>com.querydsl</groupId>
    <artifactId>querydsl-jpa</artifactId>
    <version>5.0.0</version>
    <classifier>jakarta</classifier>
</dependency>
```	
and 
```			
<dependency>
    <groupId>com.querydsl</groupId>
    <artifactId>querydsl-apt</artifactId>
    <version>5.0.0</version>
    <classifier>jakarta</classifier>
</dependency>
```

I use a customization in my repository that uses Querydsl. Here is the code snippet:

```
   @Override
    default void customize(QuerydslBindings bindings, QOfertasActivas qOfertasActivas) {

        StringPath[] multiPropertySearchPaths = new StringPath[] { qOfertasActivas.nombre,
                qOfertasActivas.nombreEmpresa, qOfertasActivas.tag, qOfertasActivas.descripcion,
                qOfertasActivas.poblacion };

        bindings.bind(multiPropertySearchPaths).all(new MultiValueBinding<StringPath, String>() {
            @Override
            public Optional<Predicate> bind(StringPath path, Collection<? extends String> values) {
                BooleanBuilder predicate = new BooleanBuilder();
                for (StringPath propertyPath : multiPropertySearchPaths) {
                    values.forEach(value -> predicate.or(
                            Expressions.stringTemplate("FUNCTION('f_unaccent', {0})", propertyPath).containsIgnoreCase(
                                    Expressions.stringTemplate("FUNCTION('f_unaccent', {0})", value))));
                }
                return Optional.of(predicate);
            }
        });
    }
```

With the previous version of Hibernate ("Hibernate Version":"5.6.15.Final"), the use of this method generated a query that looked like this (I'm removing unnecessary information):

```
Hibernate: select {...} from public.ofertas_activas ofertasact0_ where lower(f_unaccent(ofertasact0_.nombre)) like lower(((?||f_unaccent(?))||?)) escape '!' or lower(f_unaccent(ofertasact0_.nombre_empresa)) like lower(((?||f_unaccent(?))||?)) escape '!' or lower(f_unaccent(ofertasact0_.tag)) like lower(((?||f_unaccent(?))||?)) escape '!' or lower(f_unaccent(ofertasact0_.descripcion)) like lower(((?||f_unaccent(?))||?)) escape '!' or lower(f_unaccent(ofertasact0_.poblacion)) like lower(((?||f_unaccent(?))||?)) escape '!' order by ofertasact0_.creado desc limit ?
```

and this worked perfectly. However, with the new version of Hibernate (`"Hibernate Version":"6.1.7.Final"`), it fails with the following error:
```
org.hibernate.QueryException: Parameter 1 of function lower() has type STRING, but argument is of type java.lang.Object
...
	at com.querydsl.jpa.impl.AbstractJPAQuery.createQuery(AbstractJPAQuery.java:132)
	at com.querydsl.jpa.impl.AbstractJPAQuery.createQuery(AbstractJPAQuery.java:125)
	at com.querydsl.jpa.impl.AbstractJPAQuery.fetch(AbstractJPAQuery.java:242)
	at org.springframework.data.jpa.repository.support.QuerydslJpaPredicateExecutor.findAll(QuerydslJpaPredicateExecutor.java:143)
``` 

It seems that Hibernate 6 is typechecking the arguments of the query.

If you need more info I will gladly provide it.

**Comment by plinkr** [comment]
The problem only occurs when using case insensitive search and using the function on the DB, it appears that Spring intercepts the result of the `f_unaccent` DB function and Hibernate is typechecking the parameter for the `lower` function before executing it
I just changed the DB function so it lowers the result of the unaccent and change the type of search in the boolean expression of Querydsl.
The DB function now is like this:
```
CREATE OR REPLACE FUNCTION public.f_unaccent_lowercase(text)
  RETURNS text
  LANGUAGE sql IMMUTABLE PARALLEL SAFE STRICT AS
$func$
SELECT lower(public.unaccent('public.unaccent', $1))
$func$;
```

 and I changed the customize method in the repository for Querydsl to this:
 ```
    @Override
    default void customize(QuerydslBindings bindings, QOfertasActivas qOfertasActivas) {

        StringPath[] multiPropertySearchPaths = new StringPath[] { qOfertasActivas.nombre,
                qOfertasActivas.nombreEmpresa, qOfertasActivas.tag, qOfertasActivas.descripcion,
                qOfertasActivas.poblacion };

        bindings.bind(multiPropertySearchPaths).all(new MultiValueBinding<StringPath, String>() {
            @Override
            public Optional<Predicate> bind(StringPath path, Collection<? extends String> values) {
                BooleanBuilder predicate = new BooleanBuilder();
                for (StringPath propertyPath : multiPropertySearchPaths) {
                    values.forEach(value -> predicate.or(
                            Expressions.stringTemplate("FUNCTION('f_unaccent_lowercase', {0})", propertyPath).contains(
                                    Expressions.stringTemplate("FUNCTION('f_unaccent_lowercase', {0})", value))));
                }
                return Optional.of(predicate);
            }
        });
    }
 ```

Now the error doesn't occur because the 'lower' and 'unaccent' are both on the DB side.
I'm closing the issue as it appears to be more related to Spring/Hibernate.
