### ISSUE TITLE
Failed to match parameter arg0 to QClass column for class querdsl.entity.Entity

### ISSUE THREAD

**Issue by magicmayu** [querydsl/querydsl#3529]
I'm tring to integrate querydsl into spring data jdbc.
I added the  package below into my build.gradle
```gradle
    implementation 'com.infobip:infobip-spring-data-jdbc-querydsl-boot-starter:8.1.2'
   annotationProcessor 'com.infobip:infobip-spring-data-jdbc-annotation-processor:8.1.2' 
```
I made an entity and add the @AllArgsConstructor annotation from lombok.
This is my entity code
```java
@Data
@AllArgsConstructor
public class Entity implements Serializable {
  private static final long serialVersionUID = 1L;
  @Id
  private String id;
  private String name;
  private String description;
}
```
The QEntity is generated.
Then I wrote the repository and the service.
```java
public interface EntityRepository extends QuerydslJdbcRepository<Entity, String> {

}
```
```java
public class EntityService {

  @Autowired
  EntityRepository entityRepository;
}
```
But when i start the application, an exception raised.
```
Caused by: java.lang.IllegalArgumentException: Failed to match parameter arg0 to QClass column for class querdsl.entity.Entity
        at com.infobip.spring.data.common.QuerydslExpressionFactory.resolveNonColumnParameter(QuerydslExpressionFactory.java:95) ~[infobip-spring-data-common-8.1.2.jar:na]
        at com.infobip.spring.data.common.QuerydslExpressionFactory.getExpression(QuerydslExpressionFactory.java:73) ~[infobip-spring-data-common-8.1.2.jar:na]
        at com.infobip.spring.data.common.QuerydslExpressionFactory.lambda$getConstructorExpression$1(QuerydslExpressionFactory.java:54) ~[infobip-spring-data-common-8.1.2.jar:na]
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[na:na]
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[na:na]
        at com.infobip.spring.data.common.QuerydslExpressionFactory.getConstructorExpression(QuerydslExpressionFactory.java:58) ~[infobip-spring-data-common-8.1.2.jar:na]
        at com.infobip.spring.data.jdbc.QuerydslJdbcRepositoryFactory.getRepositoryFragments(QuerydslJdbcRepositoryFactory.java:74) ~[infobip-spring-data-jdbc-querydsl-8.1.2.jar:na]
        at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepositoryComposition(RepositoryFactorySupport.java:428) ~[spring-data-commons-3.0.5.jar:3.0.5]
        at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:293) ~[spring-data-commons-3.0.5.jar:3.0.5]
        at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.lambda$afterPropertiesSet$5(RepositoryFactoryBeanSupport.java:279) ~[spring-data-commons-3.0.5.jar:3.0.5]
        at org.springframework.data.util.Lazy.getNullable(Lazy.java:245) ~[spring-data-commons-3.0.5.jar:3.0.5]
        at org.springframework.data.util.Lazy.get(Lazy.java:114) ~[spring-data-commons-3.0.5.jar:3.0.5]
        at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:285) ~[spring-data-commons-3.0.5.jar:3.0.5]
        at org.springframework.data.jdbc.repository.support.JdbcRepositoryFactoryBean.afterPropertiesSet(JdbcRepositoryFactoryBean.java:201) ~[spring-data-jdbc-3.0.5.jar:3.0.5]
        at com.infobip.spring.data.jdbc.QuerydslJdbcRepositoryFactoryBean.afterPropertiesSet(QuerydslJdbcRepositoryFactoryBean.java:165) ~[infobip-spring-data-jdbc-querydsl-8.1.2.jar:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1816) ~[spring-beans-6.0.8.jar:6.0.8]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766) ~[spring-beans-6.0.8.jar:6.0.8]
        ... 68 common frames omitted
```

What can i do for this?

## Environment

Querydsl version:
8.1.2
Querydsl module:
infobip-spring-data-jdbc-querydsl
Database:
mysql 8.0
JDK:
17
## Additional details

The constructor which the Querydsl discovered is Entity(String arg0, String arg1, String arg2)，
so when the code（var field = ReflectionUtils.findField(type, name);） in the QuerydslExpressionFactory is  executed， 
the field got a null.
I don't know the parameters are not id, name and description.

**Comment by magicmayu** [comment]
i solved it. 
in the readme, i found the requirements of “Java 17 with [parameter names preserved in byte code](https://stackoverflow.com/a/20594685/607767) (used to map columns to constructor parameters)”
at the start i thought it's new feature of Java 17，but it is not，i should manually enable it.

**Comment by hrandika** [comment]
Hi @magicmayu can you please explain how you did this. Stack-overflow answer did not worked for me

**Comment by magicmayu** [comment]
> Hi @magicmayu can you please explain how you did this. Stack-overflow answer did not worked for me

The -parameters should be the argument passed to Java Compiler
I don't konw which ide you use for developing.
For eclipse compilor, I setted the global preferences. In the .settings/org.eclipse.jdt.core.prefs, I added org.eclipse.jdt.core.compiler.codegen.methodParameters=generate

This is work for me.
