### ISSUE TITLE
QueryDSL not compatible with Spring Boot 3.1 / Hibernate 6.2

### ISSUE THREAD

**Issue by cmuchinsky** [querydsl/querydsl#3543]
## Observed vs. expected behavior

When using QueryDSL 5.0.0 with Spring Boot 3.1 which includes Hibernate 6.2, the following stack trace is observed:
```
java.lang.NoClassDefFoundError: Could not initialize class com.querydsl.jpa.hibernate.HibernateUtil
	at com.querydsl.jpa.hibernate.AbstractHibernateQuery.createQuery(AbstractHibernateQuery.java:105)
	at com.querydsl.jpa.hibernate.AbstractHibernateQuery.createQuery(AbstractHibernateQuery.java:97)
	at com.querydsl.jpa.hibernate.AbstractHibernateQuery.fetch(AbstractHibernateQuery.java:185)
        ...
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: org/hibernate/type/ByteType [in thread "ForkJoinPool-1-worker-1"]
	at com.querydsl.jpa.hibernate.HibernateUtil.<clinit>(HibernateUtil.java:44)
	...
```

## Steps to reproduce

Any querydsl JPA invocation that creates a query seems to trigger this.

## Environment

Querydsl version: 5.0.0

Querydsl module: querydsl-jpa-jakarta

Database: Postgres

JDK: 17

**Comment by andygoossens** [comment]
At the moment I am still using Spring Boot 3.0, but I had success with this fork: https://github.com/marok39/querydsl

**Comment by ddxl123** [comment]
me too.

**Comment by arnosthavelka** [comment]
@cmuchinsky  It seems weird. I'm already using Querydsl with Spring Boot 3.1 and Hibernate 6.2 -> see my repo https://github.com/arnosthavelka/spring-advanced-training/tree/develop/sat-jpa. I guess I've seen this issue when I was migrating to Spring Boot 3. You can check my article https://dzone.com/articles/upgrade-guide-to-spring-boot-3-for-spring-data-jpa-3-and-querydsl-5. Have you switched to Jakarta? I guess it's not the issue, but it's a good start 😉.
