### ISSUE TITLE
QueryDSL is not Compatible with Graal VM 17/21

### ISSUE THREAD

**Issue by 5aab** [querydsl/querydsl#3646]
## Observed vs. expected behavior

QueryDSL is not Compatible with Graal VM 17/21

## Steps to reproduce

create a sample project from the spring initializer. Add QueryDSL dependencies. Try to build the native image. it will lead to build failure

## Environment

Windows, Spring Boot 3.2.0, Query DSL 5.0.0

Querydsl version: 5.0.0

Querydsl module:

```xml
 <dependency>
            <groupId>com.querydsl</groupId>
            <artifactId>querydsl-apt</artifactId>
            <version>${querydsl.version}</version>
            <classifier>jakarta</classifier>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.querydsl</groupId>
            <artifactId>querydsl-jpa</artifactId>
            <classifier>jakarta</classifier>
            <version>${querydsl.version}</version>
        </dependency>
```

Database: H2

JDK: 17

**Comment by velo** [comment]
FWIW, my fork of querydsl works well with quarkus and making sure native build works is part of the build process

https://github.com/OpenFeign/querydsl/tree/master/querydsl-examples/querydsl-example-jpa-quarkus

It's all build on docker image, but seems fine
https://app.circleci.com/pipelines/github/OpenFeign/querydsl/788/workflows/9811b105-1c80-4da0-aa1e-f34f6e0be745/jobs/5567

If there is anything needed, please let me know

**Comment by 5aab** [comment]
@velo this problem is specific to the Spring Boot project. do you have a working fork for the Spring boot project?

**Comment by velo** [comment]
Is spring fully functional with graalvm?

**Comment by 5aab** [comment]
Yes it is, starting version 3.  Rest of the libraries are working fine with
spring boot version 3.2.1. I get this issue only when I add query DSL
libraries

**Comment by velo** [comment]
@5aab  can you add the graal/native bits to https://github.com/OpenFeign/querydsl/tree/master/querydsl-examples/querydsl-example-jpa-spring ?

Just a Dockerfile that builds and test the native image (like the one I did for quarkus https://github.com/OpenFeign/querydsl/blob/master/querydsl-examples/querydsl-example-jpa-quarkus/Dockerfile)

Then I can troubleshoot and fix whatever is going wrong there.

**Comment by mirzaprangon** [comment]
Still waiting for update on this. Facing same problem.

**Comment by velo** [comment]
@mirzaprangon yeah, I would like to help, but so far, nobody seems to be willing to make an example project to reproduce the issue.

**Comment by bharathkalyans** [comment]
> @mirzaprangon yeah, I would like to help, but so far, nobody seems to be willing to make an example project to reproduce the issue.

Hey, I have a sample project where I was relearning about basics of spring boot, wile building the native image I am facing the following exception
`
java.lang.TypeNotPresentException: Type com.querydsl.core.types.Path not present
        at java.base/sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117) ~[na:na]
`

If you guys are interested then please use the following project to reproduce the error
[project](https://gitlab.com/bharathkalyans/springboot-postgresql-redis)
_Note - Make sure you have postgres and redis running!!!_

**Comment by velo** [comment]
@bharathkalyans adding this dependency

```

        <dependency>
            <groupId>io.github.openfeign.querydsl</groupId>
            <artifactId>querydsl-jpa</artifactId>
            <version>6.2.1</version>
            <scope>compile</scope>
        </dependency>
```

Fixes the first error `java.lang.TypeNotPresentException: Type com.querydsl.core.types.Path` error.

The second you need etiher switch to java 17 or find a different buildpack

**Comment by bharathkalyans** [comment]
> @bharathkalyans adding this dependency
> 
> ```
> 
>         <dependency>
>             <groupId>io.github.openfeign.querydsl</groupId>
>             <artifactId>querydsl-jpa</artifactId>
>             <version>6.2.1</version>
>             <scope>compile</scope>
>         </dependency>
> ```
> 
> Fixes the first error `java.lang.TypeNotPresentException: Type com.querydsl.core.types.Path` error.
> 
> The second you need etiher switch to java 17 or find a different buildpack

Oh cool, thanks!! It doesn't support Java 21 yet right @velo?

**Comment by velo** [comment]
My querydsl fork does support 21

**Comment by pujachowdhary27** [comment]
> > @bharathkalyans adding this dependency
> > ```
> > 
> >         <dependency>
> >             <groupId>io.github.openfeign.querydsl</groupId>
> >             <artifactId>querydsl-jpa</artifactId>
> >             <version>6.2.1</version>
> >             <scope>compile</scope>
> >         </dependency>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Fixes the first error `java.lang.TypeNotPresentException: Type com.querydsl.core.types.Path` error.
> > The second you need etiher switch to java 17 or find a different buildpack
> 
> Oh cool, thanks!! It doesn't support Java 21 yet right @velo?

I added this dependency, I see a new error while creating a build of the project - 
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.lang.Package.getName()" because the return value of "java.lang.Class.getPackage()" is null
        at org.springframework.data.util.QTypeContributor.getQueryClassName(QTypeContributor.java:83)
        at org.springframework.data.util.QTypeContributor.contributeEntityPath(QTypeContributor.java:44)
        at org.springframework.data.aot.ManagedTypesBeanRegistrationAotProcessor.contributeType(ManagedTypesBeanRegistrationAotProcessor.java:140)

**Comment by velo** [comment]
`org.springframework.data.util.QTypeContributor` well, I would say it's spring fault. 

Querydsl works fine with native quakus.

Unless you have an example without spring that is failing

**Comment by irslon** [comment]
> > > [@bharathkalyans](https://github.com/bharathkalyans) adding this dependency
> > > ```
> > > 
> > >         <dependency>
> > >             <groupId>io.github.openfeign.querydsl</groupId>
> > >             <artifactId>querydsl-jpa</artifactId>
> > >             <version>6.2.1</version>
> > >             <scope>compile</scope>
> > >         </dependency>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Fixes the first error `java.lang.TypeNotPresentException: Type com.querydsl.core.types.Path` error.
> > > The second you need etiher switch to java 17 or find a different buildpack
> > 
> > 
> > Oh cool, thanks!! It doesn't support Java 21 yet right [@velo](https://github.com/velo)?
> 
> I added this dependency, I see a new error while creating a build of the project - Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.lang.Package.getName()" because the return value of "java.lang.Class.getPackage()" is null at org.springframework.data.util.QTypeContributor.getQueryClassName(QTypeContributor.java:83) at org.springframework.data.util.QTypeContributor.contributeEntityPath(QTypeContributor.java:44) at org.springframework.data.aot.ManagedTypesBeanRegistrationAotProcessor.contributeType(ManagedTypesBeanRegistrationAotProcessor.java:140)

Have you had any success with this issue?
