### ISSUE TITLE
add support for sequence (nextval) on insert of new record

### ISSUE THREAD

**Issue by manfreddev** [querydsl/querydsl#41]
Now you can create a sequence by using a TemplateExpression...
Expression nextCustomerId = TemplateExpressionImpl.create(String.class, "nextval('customer_id_seq')");

Could this be structurally resolved within the framework?

https://groups.google.com/forum/#!topic/querydsl/k5uKUq4DngM

**Comment by inspell** [comment]
I think that this is not enough though. When I try to use the NEXTVAL with Derby it throws error.
For example this:
Expression s = SimpleOperation.create(BigInteger.class, SQLOps.NEXTVAL, ConstantImpl
                .create("test"));
s.toString(); ---> says unknown operation with operator com.mysema.query.sql.SQLOps#NEXTVAL and args [test]

At some point when I try to execute an Update query and set a field to a value of a sequence (JPAQueryFactory.set(qDoc.documentGenerationTrackingId, s))
I get a NPE because it seems that the precedence for the NEXTVAL op cannot be found (it is null).
I am using com.mysema.querydsl:querydsl-core:3.6.0

**Comment by timowest** [comment]
nextval is not supported in Querydsl JPA, that's why you get an exception. Could you provide the stacktrace for the NPE?

**Comment by inspell** [comment]
This is the stack trace:

java.lang.NullPointerException
	at com.mysema.query.types.Templates.getPrecedence(Templates.java:310)
	at com.mysema.query.support.SerializerBase.visitOperation(SerializerBase.java:277)
	at com.mysema.query.jpa.JPQLSerializer.visitOperation(JPQLSerializer.java:432)
	at com.mysema.query.support.SerializerBase.visit(SerializerBase.java:249)
	at com.mysema.query.support.SerializerBase.visit(SerializerBase.java:42)
	at com.mysema.query.types.OperationImpl.accept(OperationImpl.java:91)
	at com.mysema.query.support.SerializerBase.handle(SerializerBase.java:105)
	at com.mysema.query.support.SerializerBase.handle(SerializerBase.java:137)
	at com.mysema.query.jpa.JPQLSerializer.serializeForUpdate(JPQLSerializer.java:254)
	at com.mysema.query.jpa.impl.JPAUpdateClause.execute(JPAUpdateClause.java:61)

The is how the sequence is created:
Expression s = SimpleOperation.create(BigInteger.class, SQLOps.NEXTVAL, ConstantImpl
                .create("sequence-name"));
...
return new JPAQueryFactory(entityManager)
                .update(qclass)
                .where(predicate)
                .set....
                ...
                .set(qclass.property, s)
                .execute();
