### ISSUE TITLE
Limit gets ignored in subquery

### ISSUE THREAD

**Issue by virgo47** [querydsl/querydsl#421]
I have a Dog and Race table, dogs reference race. I wanted to do an update: "Update all dogs without race (is null) with most popular race."

My code looks like this (Pes=Dog, Rasa=Race):

```
QPes p = new QPes("pes"); QRasa r = p.rasa;
em.getTransaction().begin();
SimpleSubQuery<Rasa> mostPopularRaceSubquery = new JPASubQuery().from(p)
    .join(r).groupBy(r).orderBy(r.count().desc()).limit(1).unique(r);
long execute = new JPAUpdateClause(em, QPes.pes)
    .where(QPes.pes.rasa.id.isNull())
    .set(QPes.pes.rasa, mostPopularRaceSubquery).execute();
System.out.println("execute = " + execute);
em.getTransaction().commit();
```

Generated query misses any limit though:

```
Hibernate: update Pes set rasa_id=(select pes1_.rasa_id from Pes pes1_ inner join Rasa rasa2_ on pes1_.rasa_id=rasa2_.id group by pes1_.rasa_id order by count(pes1_.rasa_id) desc) where rasa_id is null
```

And it generates exception because of this error:

```
ERROR: Scalar subquery contains more than one row; SQL statement:
update Pes set rasa_id=(select pes1_.rasa_id from Pes pes1_ inner join Rasa rasa2_ on pes1_.rasa_id=rasa2_.id group by pes1_.rasa_id order by count(pes1_.rasa_id) desc) where rasa_id is null [90053-170]
Exception in thread "main" javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: could not execute statement
    at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1387)
    at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1310)
    at org.hibernate.ejb.AbstractEntityManagerImpl.throwPersistenceException(AbstractEntityManagerImpl.java:1397)
    at org.hibernate.ejb.AbstractQueryImpl.executeUpdate(AbstractQueryImpl.java:108)
    at com.mysema.query.jpa.impl.JPAUpdateClause.execute(JPAUpdateClause.java:67)
    at sqldemo.Main.main(Main.java:32)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)
```

The same exception occurs when I remove limit(1) from the code, generated query is the same.

Limit works fine with simple query:

```
QPes p = new QPes("pes"); QRasa r = p.rasa;
Rasa mostPopularRace = new JPAQuery(em).from(p)
    .join(r).groupBy(r).orderBy(r.count().desc()).limit(1).uniqueResult(r);
System.out.println("mostPopularRace = " + mostPopularRace);
```

Works, one result is written out.

Used version: 3.1.1

**Comment by nistal97** [comment]
hey, i know this is closed, but i think it's useful for deep pagination,  eg `select * from table where id in (select id from table limit 99999, 10)`
