### ISSUE TITLE
Support for summing Joda Money

### ISSUE THREAD

**Issue by martypitt** [querydsl/querydsl#449]
Is it possible to perform math / aggregate operations on Joda's Money type?

I'm using UserType to provide support, which essentially persists the money as a BigDecimal.

I've tried the following, to no avail:

```
 BigDecimal result = query().from($ledgerPost).singleResult($post.value.castToNum(BigDecimal.class).sum());
```

(where `$post.value` is of type `Money`).

However, this fails with a `NullPointerException`(see below).  Is there a way to support these operations?  If not in-built, then is there a way to extend QueryDSL to provide support for these user types?  (I understand why you might not want to introduce the JodaMoney dependency)

[Related discussion](https://groups.google.com/forum/#!topic/querydsl/6up-meOQlNc)

StackTrace:

```
java.lang.NullPointerException
    at org.hibernate.dialect.function.StandardAnsiSqlAggregationFunctions$SumFunction.determineJdbcTypeCode(StandardAnsiSqlAggregationFunctions.java:145)
    at org.hibernate.dialect.function.StandardAnsiSqlAggregationFunctions$SumFunction.getReturnType(StandardAnsiSqlAggregationFunctions.java:157)
    at org.hibernate.hql.internal.ast.util.SessionFactoryHelper.findFunctionReturnType(SessionFactoryHelper.java:406)
    at org.hibernate.hql.internal.ast.tree.AggregateNode.getDataType(AggregateNode.java:83)
    at org.hibernate.hql.internal.ast.tree.SelectClause.initializeExplicitSelectClause(SelectClause.java:152)
    at org.hibernate.hql.internal.ast.HqlSqlWalker.useSelectClause(HqlSqlWalker.java:859)
    at org.hibernate.hql.internal.ast.HqlSqlWalker.processQuery(HqlSqlWalker.java:649)
    at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.query(HqlSqlBaseWalker.java:663)
    at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.selectStatement(HqlSqlBaseWalker.java:299)
    at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.statement(HqlSqlBaseWalker.java:247)
    at org.hibernate.hql.internal.ast.QueryTranslatorImpl.analyze(QueryTranslatorImpl.java:248)
    at org.hibernate.hql.internal.ast.QueryTranslatorImpl.doCompile(QueryTranslatorImpl.java:183)
    at org.hibernate.hql.internal.ast.QueryTranslatorImpl.compile(QueryTranslatorImpl.java:136)
    at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:105)
    at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:80)
    at org.hibernate.engine.query.spi.QueryPlanCache.getHQLQueryPlan(QueryPlanCache.java:168)
    at org.hibernate.internal.AbstractSessionImpl.getHQLQueryPlan(AbstractSessionImpl.java:221)
    at org.hibernate.internal.AbstractSessionImpl.createQuery(AbstractSessionImpl.java:199)
    at org.hibernate.internal.SessionImpl.createQuery(SessionImpl.java:1735)
    at org.hibernate.ejb.AbstractEntityManagerImpl.createQuery(AbstractEntityManagerImpl.java:291)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:241)
    at com.sun.proxy.$Proxy88.createQuery(Unknown Source)
    at com.mysema.query.jpa.impl.AbstractJPAQuery.createQuery(AbstractJPAQuery.java:129)
    at com.mysema.query.jpa.impl.AbstractJPAQuery.uniqueResult(AbstractJPAQuery.java:293)
    at com.mysema.query.jpa.impl.AbstractJPAQuery.uniqueResult(AbstractJPAQuery.java:281)
    at com.mysema.query.support.ProjectableQuery.singleResult(ProjectableQuery.java:75)
    at com.mangofactory.concorde.dashboard.analytics.DashboardAnalyticsRepositoryTest.canSumMoney(DashboardAnalyticsRepositoryTest.java:55)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
```

**Comment by pedrocborges2** [comment]
@timowest Where would the QMoney.class come from in this case?

**Comment by Shredder121** [comment]
If you make QueryDelegates Querydsl will make a QSubclass for the type if it's not yet present.

**Comment by gdantimi** [comment]
Since this solution didn't work for me I post the one that worked (Version 4.4.1)

```
@QueryDelegate(BigMoney.class)
	public static NumberExpression<BigDecimal> sum(ComparablePath<BigMoney> money) {
		SimplePath<BigDecimal> amount = Expressions.path(BigDecimal.class, money.getRoot(), "amount");
		return Expressions.numberOperation(BigDecimal.class, Ops.AggOps.SUM_AGG, amount);
	}
```

**Comment by gdantimi** [comment]
This solution doesn't work for me. 
The main reason is that `BigMoney`and `Money` do not extend the `Number` class and therefore I have the following exception:
```
java.lang.ClassCastException: org.joda.money.BigMoney cannot be cast to java.lang.Number
		at com.querydsl.core.support.NumberConversion.newInstance(NumberConversion.java:59)
		at com.querydsl.jpa.impl.AbstractJPAQuery.getSingleResult(AbstractJPAQuery.java:178)
		at com.querydsl.jpa.impl.AbstractJPAQuery.fetchOne(AbstractJPAQuery.java:253)
		at com.querydsl.core.support.FetchableQueryBase.fetchFirst(FetchableQueryBase.java:51)
```

I tried multiple different variations but with no luck. 
Any other suggestion?

**Comment by gdantimi** [comment]
```
public BigDecimal sumAmounts(){
return jpaQueryFactory.select(mytable.amount.sum())
				.from(mytable)
				.where(condition)
				.fetchFirst();
}
```
What is not working is the cast to `BigDecimal` (actually `Number`).
I adapted Timo's code in this way:
```
@QueryDelegate(BigMoney.class)
public static NumberExpression<BigDecimal> sum(ComparablePath<BigMoney> money) {
	return Expressions.numberOperation(BigDecimal.class, Ops.AggOps.SUM_AGG, money);
}
```

**Comment by gdantimi** [comment]
@Shredder121 do you have any suggestion?
