### ISSUE TITLE
Test failure in SQLiteSuiteTest

### ISSUE THREAD

**Issue by jstaffans** [querydsl/querydsl#563]
```
Tests run: 137, Failures: 1, Errors: 0, Skipped: 3, Time elapsed: 7.18 sec <<< FAILURE! - in com.mysema.query.suites.SQLiteSuiteTest$Select
StandardTest(com.mysema.query.suites.SQLiteSuiteTest$Select)  Time elapsed: 6.619 sec  <<< FAILURE!
junit.framework.AssertionFailedError: Failed with 1 failure(s) of 402 tests
hour(e.timefield) = 3 failed

	at junit.framework.Assert.fail(Assert.java:47)
	at com.mysema.query.QueryExecution.report(QueryExecution.java:268)
	at com.mysema.query.SelectBase.StandardTest(SelectBase.java:1248)
``` 

On Mac OS X 10.8.5 using Java 1.7.

**Comment by johnktims** [comment]
All of the tests pass on my macbook pro so I'm closing this ticket.

**Comment by Shredder121** [comment]
I think it might be good to revise the outcomes, there is still one for me that fails (not hour() though, but week()).
