### ISSUE TITLE
NotSerializableException on QTuple$TupleImpl

### ISSUE THREAD

**Issue by dmiorandi** [querydsl/querydsl#640]
I've got a business code like this

``` java
List<Tuple> domande = piTreBusinessImpl.getDomandeDaProcessare();
```

if i try to serialize "domande" I've got a NotSerializableException referred to 

``` java
com.mysema.query.types.QTuple$TupleImpl
```

How can I achieve this?

All in all i need to send a tuple query result via some transports that need serialization and this issue avoid me to accomplish that task.

Tks
Denis

**Comment by caarlos0** [comment]
Hi!

I'm using version 3.3.2, and got this:

```
 No serializer found for class com.mysema.query.types.QTuple$TupleImpl and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) ) (through reference chain: java.util.ArrayList[0])
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:59) [jackson-databind-2.4.1.jar:2.4.1]
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:26) [jackson-databind-2.4.1.jar:2.4.1]
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContentsUsing(CollectionSerializer.java:145) [jackson-databind-2.4.1.jar:2.4.1]
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents(CollectionSerializer.java:87) [jackson-databind-2.4.1.jar:2.4.1]
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents(CollectionSerializer.java:23) [jackson-databind-2.4.1.jar:2.4.1]
	at com.fasterxml.jackson.databind.ser.std.AsArraySerializerBase.serialize(AsArraySerializerBase.java:183) [jackson-databind-2.4.1.jar:2.4.1]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:236) [jackson-databind-2.4.1.jar:2.4.1]
	at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:604) [jackson-databind-2.4.1.jar:2.4.1]
	at org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider.writeTo(ResteasyJackson2Provider.java:199) [resteasy-jackson2-provider-3.0.10.Final.jar:]
	at org.jboss.resteasy.core.interception.AbstractWriterInterceptorContext.writeTo(AbstractWriterInterceptorContext.java:129) [resteasy-jaxrs-3.0.10.Final.jar:]
	at org.jboss.resteasy.core.interception.ServerWriterInterceptorContext.writeTo(ServerWriterInterceptorContext.java:62) [resteasy-jaxrs-3.0.10.Final.jar:]
	at org.jboss.resteasy.core.interception.AbstractWriterInterceptorContext.proceed(AbstractWriterInterceptorContext.java:118) [resteasy-jaxrs-3.0.10.Final.jar:]
	at org.jboss.resteasy.security.doseta.DigitalSigningInterceptor.aroundWriteTo(DigitalSigningInterceptor.java:143) [resteasy-crypto-3.0.10.Final.jar:]
	at org.jboss.resteasy.core.interception.AbstractWriterInterceptorContext.proceed(AbstractWriterInterceptorContext.java:122) [resteasy-jaxrs-3.0.10.Final.jar:]
	at org.jboss.resteasy.plugins.interceptors.encoding.GZIPEncodingInterceptor.aroundWriteTo(GZIPEncodingInterceptor.java:100) [resteasy-jaxrs-3.0.10.Final.jar:]
	at org.jboss.resteasy.core.interception.AbstractWriterInterceptorContext.proceed(AbstractWriterInterceptorContext.java:122) [resteasy-jaxrs-3.0.10.Final.jar:]
	at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:99) [resteasy-jaxrs-3.0.10.Final.jar:]
	at org.jboss.resteasy.core.SynchronousDispatcher.writeResponse(SynchronousDispatcher.java:427) [resteasy-jaxrs-3.0.10.Final.jar:]
	... 32 more
```

**Comment by Shredder121** [comment]
It seems to me that [something goes wrong with jackson and resteasy](http://grepcode.com/file/repo1.maven.org/maven2/com.fasterxml.jackson.core/jackson-databind/2.4.1/com/fasterxml/jackson/databind/ser/std/CollectionSerializer.java/#87).
There seems to be a serializer, (UnknownSerializer) [that just throws exceptions](http://grepcode.com/file/repo1.maven.org/maven2/com.fasterxml.jackson.core/jackson-databind/2.4.1/com/fasterxml/jackson/databind/ser/impl/UnknownSerializer.java/#39).

[see complete backtrace here](http://grepcode.com/search/st?query=No+serializer+found+for+class+com.mysema.query.types.QTuple$TupleImpl+and+no+properties+discovered+to+create+BeanSerializer+%28to+avoid+exception,+disable+SerializationFeature.FAIL_ON_EMPTY_BEANS%29+%29+%28through+reference+chain:+java.util.ArrayList%5B0%5D%29%0D%0A++++at+com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty%28UnknownSerializer.java:59%29+%5Bjackson-databind-2.4.1.jar:2.4.1%5D%0D%0A++++at+com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize%28UnknownSerializer.java:26%29+%5Bjackson-databind-2.4.1.jar:2.4.1%5D%0D%0A++++at+com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContentsUsing%28CollectionSerializer.java:145%29+%5Bjackson-databind-2.4.1.jar:2.4.1%5D%0D%0A++++at+com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents%28CollectionSerializer.java:87%29+%5Bjackson-databind-2.4.1.jar:2.4.1%5D%0D%0A++++at+com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents%28CollectionSerializer.java:23%29+%5Bjackson-databind-2.4.1.jar:2.4.1%5D%0D%0A++++at+com.fasterxml.jackson.databind.ser.std.AsArraySerializerBase.serialize%28AsArraySerializerBase.java:183%29+%5Bjackson-databind-2.4.1.jar:2.4.1%5D%0D%0A++++at+com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue%28DefaultSerializerProvider.java:236%29+%5Bjackson-databind-2.4.1.jar:2.4.1%5D%0D%0A++++at+com.fasterxml.jackson.databind.ObjectWriter.writeValue%28ObjectWriter.java:604%29+%5Bjackson-databind-2.4.1.jar:2.4.1%5D%0D%0A++++at+org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider.writeTo%28ResteasyJackson2Provider.java:199%29+%5Bresteasy-jackson2-provider-3.0.10.Final.jar:%5D%0D%0A++++at+org.jboss.resteasy.core.interception.AbstractWriterInterceptorContext.writeTo%28AbstractWriterInterceptorContext.java:129%29+%5Bresteasy-jaxrs-3.0.10.Final.jar:%5D%0D%0A++++at+org.jboss.resteasy.core.interception.ServerWriterInterceptorContext.writeTo%28ServerWriterInterceptorContext.java:62%29+%5Bresteasy-jaxrs-3.0.10.Final.jar:%5D%0D%0A++++at+org.jboss.resteasy.core.interception.AbstractWriterInterceptorContext.proceed%28AbstractWriterInterceptorContext.java:118%29+%5Bresteasy-jaxrs-3.0.10.Final.jar:%5D%0D%0A++++at+org.jboss.resteasy.security.doseta.DigitalSigningInterceptor.aroundWriteTo%28DigitalSigningInterceptor.java:143%29+%5Bresteasy-crypto-3.0.10.Final.jar:%5D%0D%0A++++at+org.jboss.resteasy.core.interception.AbstractWriterInterceptorContext.proceed%28AbstractWriterInterceptorContext.java:122%29+%5Bresteasy-jaxrs-3.0.10.Final.jar:%5D%0D%0A++++at+org.jboss.resteasy.plugins.interceptors.encoding.GZIPEncodingInterceptor.aroundWriteTo%28GZIPEncodingInterceptor.java:100%29+%5Bresteasy-jaxrs-3.0.10.Final.jar:%5D%0D%0A++++at+org.jboss.resteasy.core.interception.AbstractWriterInterceptorContext.proceed%28AbstractWriterInterceptorContext.java:122%29+%5Bresteasy-jaxrs-3.0.10.Final.jar:%5D%0D%0A++++at+org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse%28ServerResponseWriter.java:99%29+%5Bresteasy-jaxrs-3.0.10.Final.jar:%5D%0D%0A++++at+org.jboss.resteasy.core.SynchronousDispatcher.writeResponse%28SynchronousDispatcher.java:427%29+%5Bresteasy-jaxrs-3.0.10.Final.jar:%5D)
