### ISSUE TITLE
Registering numeric type for Boolean in Oracle does not work if Boolean value is null

### ISSUE THREAD

**Issue by laurimak** [querydsl/querydsl#921]
Registering Booleans to be converted to number type does not work with the following configuration.

``` java
com.mysema.query.sql.Configuration configuration = new com.mysema.query.sql.Configuration(templates());
        configuration.registerNumeric(1, 0, Boolean.class);
```

This result in IllegalArgumentException in insert statement as follows.

``` java
Caused by: java.lang.IllegalArgumentException: java.sql.SQLException: Invalid column type: 16
    at com.mysema.query.sql.dml.AbstractSQLClause.setParameters(AbstractSQLClause.java:83) ~[querydsl-sql-3.2.4.jar:na]
    at com.mysema.query.sql.dml.SQLInsertClause.prepareStatementAndSetParameters(SQLInsertClause.java:274) ~[querydsl-sql-3.2.4.jar:na]
    at com.mysema.query.sql.dml.SQLInsertClause.createStatement(SQLInsertClause.java:235) ~[querydsl-sql-3.2.4.jar:na]
    at com.mysema.query.sql.dml.SQLInsertClause.execute(SQLInsertClause.java:313) ~[querydsl-sql-3.2.4.jar:na]
```

Configuring Boolean to numeric mapping in the following manner seems to be a workaround for this problem. 

``` java
com.mysema.query.sql.Configuration configuration = new com.mysema.query.sql.Configuration(templates());
        configuration.register(new BooleanType(Types.NUMERIC));
```

**Comment by RazmikMkrtchyan** [comment]
I think the bug is still actual.
I use Oracle and if my Boolean values is null,then occured Caused by: java.sql.SQLException: Invalid column type: 16:
